//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMapRouteSearchBaseRequest.h"

@interface AMapRidingRouteSearchRequest : AMapRouteSearchBaseRequest
{
    _Bool _requireExtension;
    long long _type;
}

+ (id)ajo_mapping;
@property(nonatomic) _Bool requireExtension; // @synthesize requireExtension=_requireExtension;
@property(nonatomic) long long type; // @synthesize type=_type;
- (id)init;

@end

