//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol AMapSearchRequestCacheProtocol;

@protocol AMapSearchRequestCacheProtocol <NSObject>
@property(copy, nonatomic) NSString *cachedKey;
- (id)cacheCopy;
- (NSString *)requestPath;
- (unsigned long long)cacheType;
- (void)formattedCachedStringWithLanguage:(NSString *)arg1;
- (_Bool)isSupportCache;

@optional
@property(copy, nonatomic) NSString *paramCompareString;
- (_Bool)compareResultWithAnother:(id <AMapSearchRequestCacheProtocol>)arg1;
- (_Bool)isNeedCompareParam;
@end

