//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AMapSearchAPI;
@protocol AMapSearchRequestCacheProtocol;

@interface AMapRequestBlockNode : NSObject
{
    id <AMapSearchRequestCacheProtocol> _request;
    AMapSearchAPI *_searchAPI;
}

- (void).cxx_destruct;
@property(nonatomic) __weak AMapSearchAPI *searchAPI; // @synthesize searchAPI=_searchAPI;
@property(retain, nonatomic) id <AMapSearchRequestCacheProtocol> request; // @synthesize request=_request;

@end

