//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSDictionary, NSError, NSString, NSURL, NSURLRequest, NSURLResponse;

@protocol AMapRequestReformerProtocol <NSObject>
@property(retain, nonatomic) NSURLResponse *netResponse;
@property(retain, nonatomic) NSURLRequest *netRequest;
- (NSDictionary *)HTTPHeaders;
- (NSData *)postData;
- (NSString *)method;
- (NSURL *)v6Url;
- (NSURL *)url;
- (long long)timeout;

@optional
- (void)request:(NSURLRequest *)arg1 response:(NSURLResponse *)arg2 metrics:(id)arg3 completeWithError:(NSError *)arg4;
- (NSDictionary *)httpHeaderAboutAPM;
- (_Bool)canDegrade;
- (_Bool)isSupportAPM;
- (_Bool)forceUseUserConfigTimeOut;
@end

