//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMapNetworkMonitorModel.h"

@class NSString;

@interface AMapNetworkPerformanceModel : AMapNetworkMonitorModel
{
    NSString *_serverTime;
    NSString *_exceptSize;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *exceptSize; // @synthesize exceptSize=_exceptSize;
@property(copy, nonatomic) NSString *serverTime; // @synthesize serverTime=_serverTime;
- (id)offline_datazize;
- (_Bool)isFail;
- (id)modelIdentifer;
- (id)description;
- (id)realTimeHeader;
- (id)initSucModelWithTransactionMetrics:(id)arg1 serverTime:(id)arg2 dataSize:(id)arg3;

@end

