//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class CLLockLabel, CLLockView, NSLayoutConstraint, NSString, UIBarButtonItem, UIButton, UIView;

@interface CLLockVC : UIViewController
{
    _Bool _hideCloseButton;
    _Bool _isDirectModify;
    int _type;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _forgetPwdBlock;
    CLLockLabel *_label;
    NSString *_msg;
    NSString *_lockPWDKey;
    CLLockView *_lockView;
    UIViewController *_vc;
    UIBarButtonItem *_resetItem;
    NSString *_modifyCurrentTitle;
    UIView *_actionView;
    UIButton *_modifyBtn;
    UIButton *_forgetBtn;
    NSLayoutConstraint *_topViewHconstraint;
    NSLayoutConstraint *_lockViewWconstraint;
    UIView *_topView;
    NSLayoutConstraint *_topViewTopconstraint;
}

+ (id)lockVC:(id)arg1;
+ (id)showModifyLockVCInVC:(id)arg1 successBlock:(CDUnknownBlockType)arg2;
+ (id)showVerifyLockVCInVC:(id)arg1 forgetPwdBlock:(CDUnknownBlockType)arg2 successBlock:(CDUnknownBlockType)arg3;
+ (id)showSettingLockVCInVC:(id)arg1 successBlock:(CDUnknownBlockType)arg2;
+ (void)removePwd;
+ (_Bool)hasPwd;
- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *topViewTopconstraint; // @synthesize topViewTopconstraint=_topViewTopconstraint;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak NSLayoutConstraint *lockViewWconstraint; // @synthesize lockViewWconstraint=_lockViewWconstraint;
@property(nonatomic) __weak NSLayoutConstraint *topViewHconstraint; // @synthesize topViewHconstraint=_topViewHconstraint;
@property(nonatomic) _Bool isDirectModify; // @synthesize isDirectModify=_isDirectModify;
@property(nonatomic) _Bool hideCloseButton; // @synthesize hideCloseButton=_hideCloseButton;
@property(nonatomic) __weak UIButton *forgetBtn; // @synthesize forgetBtn=_forgetBtn;
@property(nonatomic) __weak UIButton *modifyBtn; // @synthesize modifyBtn=_modifyBtn;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(copy, nonatomic) NSString *modifyCurrentTitle; // @synthesize modifyCurrentTitle=_modifyCurrentTitle;
@property(retain, nonatomic) UIBarButtonItem *resetItem; // @synthesize resetItem=_resetItem;
@property(nonatomic) __weak UIViewController *vc; // @synthesize vc=_vc;
@property(nonatomic) __weak CLLockView *lockView; // @synthesize lockView=_lockView;
@property(copy, nonatomic) NSString *lockPWDKey; // @synthesize lockPWDKey=_lockPWDKey;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) __weak CLLockLabel *label; // @synthesize label=_label;
@property(copy, nonatomic) CDUnknownBlockType forgetPwdBlock; // @synthesize forgetPwdBlock=_forgetPwdBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(nonatomic) int type; // @synthesize type=_type;
- (void)modifyPwdAction:(id)arg1;
- (void)forgetPwdAction:(id)arg1;
- (void)dismiss:(double)arg1;
- (void)labelWithType;
- (void)modiftyPwd;
- (void)forgetPwd;
- (void)setPwdReset;
- (void)dismiss;
- (void)vcPrepare;
- (void)dataTransfer;
- (void)event;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

