//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivity.h>

@class NSArray, NSString, NSURL, UIImage;

@interface CustomActivity : UIActivity
{
    NSString *_title;
    UIImage *_image;
    NSURL *_url;
    NSString *_type;
    NSArray *_shareContexts;
    NSArray *_activityItems;
}

+ (long long)activityCategory;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *activityItems; // @synthesize activityItems=_activityItems;
@property(retain, nonatomic) NSArray *shareContexts; // @synthesize shareContexts=_shareContexts;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)activityDidFinish:(_Bool)arg1;
- (void)performActivity;
- (void)prepareWithActivityItems:(id)arg1;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityImage;
- (id)_activityImage;
- (id)activityTitle;
- (id)activityType;
- (id)initWithTitie:(id)arg1 withActivityImage:(id)arg2 withUrl:(id)arg3 withType:(id)arg4 withShareContext:(id)arg5;

@end

