//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "Serializer-Protocol.h"

@class NSData, NSString;

@interface ESSkfRsaPublicKeyBlob : NSObject <Serializer>
{
    unsigned int _algID;
    unsigned int _bitLen;
    NSData *_n;
    NSData *_e;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *e; // @synthesize e=_e;
@property(retain, nonatomic) NSData *n; // @synthesize n=_n;
@property(nonatomic) unsigned int bitLen; // @synthesize bitLen=_bitLen;
@property(nonatomic) unsigned int algID; // @synthesize algID=_algID;
- (id)esData;
- (id)skfData;
- (id)initWithCCtype:(void *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

