//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class FWModuleModel, FWNavigationController, NSString, UIButton, UIViewController;

@interface FWAppThemeNavBtn : MTLModel <MTLJSONSerializing>
{
    NSString *_btn_id;
    NSString *_btn_name;
    NSString *_btn_func;
    NSString *_btn_func_set1;
    NSString *_btn_func_set2;
    NSString *_showorder;
    NSString *_icon_default;
    FWModuleModel *_agent;
    FWNavigationController *_navVc;
    UIViewController *_rootVc;
    UIButton *_button;
}

+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak UIViewController *rootVc; // @synthesize rootVc=_rootVc;
@property(nonatomic) __weak FWNavigationController *navVc; // @synthesize navVc=_navVc;
@property(retain, nonatomic) FWModuleModel *agent; // @synthesize agent=_agent;
@property(copy, nonatomic) NSString *icon_default; // @synthesize icon_default=_icon_default;
@property(copy, nonatomic) NSString *showorder; // @synthesize showorder=_showorder;
@property(copy, nonatomic) NSString *btn_func_set2; // @synthesize btn_func_set2=_btn_func_set2;
@property(copy, nonatomic) NSString *btn_func_set1; // @synthesize btn_func_set1=_btn_func_set1;
@property(copy, nonatomic) NSString *btn_func; // @synthesize btn_func=_btn_func;
@property(copy, nonatomic) NSString *btn_name; // @synthesize btn_name=_btn_name;
@property(copy, nonatomic) NSString *btn_id; // @synthesize btn_id=_btn_id;

@end

