//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FWAvaterRule : MTLModel <MTLJSONSerializing>
{
    int _showtype;
    NSString *_bgcolor1;
    NSString *_bgcolor2;
    NSString *_fontcolor1;
    NSString *_fontcolor2;
    NSString *_mmessagerurl;
    NSString *_fmessagerurl;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(nonatomic) int showtype; // @synthesize showtype=_showtype;
@property(copy, nonatomic) NSString *fmessagerurl; // @synthesize fmessagerurl=_fmessagerurl;
@property(copy, nonatomic) NSString *mmessagerurl; // @synthesize mmessagerurl=_mmessagerurl;
@property(copy, nonatomic) NSString *fontcolor2; // @synthesize fontcolor2=_fontcolor2;
@property(copy, nonatomic) NSString *fontcolor1; // @synthesize fontcolor1=_fontcolor1;
@property(copy, nonatomic) NSString *bgcolor2; // @synthesize bgcolor2=_bgcolor2;
@property(copy, nonatomic) NSString *bgcolor1; // @synthesize bgcolor1=_bgcolor1;

@end

