//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FWCAConfig : NSObject
{
    _Bool _openCAAuthLogin;
    _Bool _onlyCAAuthLogin;
    _Bool _localCAAuthLogin;
    _Bool _hideCASecretType;
    _Bool _gestureOrFingerAlreadyShow;
    NSString *_CAAcountUID;
    NSString *_CARealName;
    NSString *_CARealNumber;
    NSString *_CARandomNumber;
    NSString *_isCARealNameEditable;
    NSString *_isCARealNumberEditable;
    NSString *_isCARealNumberHide;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool gestureOrFingerAlreadyShow; // @synthesize gestureOrFingerAlreadyShow=_gestureOrFingerAlreadyShow;
@property(nonatomic) _Bool hideCASecretType; // @synthesize hideCASecretType=_hideCASecretType;
@property(nonatomic) _Bool localCAAuthLogin; // @synthesize localCAAuthLogin=_localCAAuthLogin;
@property(nonatomic) _Bool onlyCAAuthLogin; // @synthesize onlyCAAuthLogin=_onlyCAAuthLogin;
@property(nonatomic) _Bool openCAAuthLogin; // @synthesize openCAAuthLogin=_openCAAuthLogin;
@property(nonatomic) NSString *isCARealNumberHide; // @synthesize isCARealNumberHide=_isCARealNumberHide;
@property(nonatomic) NSString *isCARealNumberEditable; // @synthesize isCARealNumberEditable=_isCARealNumberEditable;
@property(nonatomic) NSString *isCARealNameEditable; // @synthesize isCARealNameEditable=_isCARealNameEditable;
@property(retain, nonatomic) NSString *CARandomNumber; // @synthesize CARandomNumber=_CARandomNumber;
@property(retain, nonatomic) NSString *CARealNumber; // @synthesize CARealNumber=_CARealNumber;
@property(retain, nonatomic) NSString *CARealName; // @synthesize CARealName=_CARealName;
@property(retain, nonatomic) NSString *CAAcountUID; // @synthesize CAAcountUID=_CAAcountUID;

@end

