//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FWCallRecord : MTLModel <MTLJSONSerializing>
{
    NSString *_callId;
    NSString *_callSenderId;
    long long _callType;
    long long _callTime;
    long long _callDuration;
}

+ (id)JSONKeyPathsByPropertyKey;
+ (const struct WCTProperty *)callDuration;
+ (const struct WCTProperty *)callTime;
+ (const struct WCTProperty *)callType;
+ (const struct WCTProperty *)callSenderId;
+ (const struct WCTProperty *)callId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(nonatomic) long long callDuration; // @synthesize callDuration=_callDuration;
@property(nonatomic) long long callTime; // @synthesize callTime=_callTime;
@property(nonatomic) long long callType; // @synthesize callType=_callType;
@property(retain, nonatomic) NSString *callSenderId; // @synthesize callSenderId=_callSenderId;
@property(retain, nonatomic) NSString *callId; // @synthesize callId=_callId;

@end

