//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FWCallConversation, FWCallConversationDetail, NSMutableArray, NSString, UIButton, UICollectionView, UIImageView, UILabel, UITableView, UIView;

@interface FWCallRecordsDetailViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _hasCache;
    FWCallConversation *_conversation;
    UIView *_headerView;
    UIImageView *_avatarView;
    UILabel *_nameLabel;
    UIButton *_callBtn;
    UICollectionView *_participantListView;
    NSMutableArray *_memberList;
    UITableView *_tableView;
    NSMutableArray *_callRecords;
    FWCallConversationDetail *_conversationDetail;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasCache; // @synthesize hasCache=_hasCache;
@property(retain, nonatomic) FWCallConversationDetail *conversationDetail; // @synthesize conversationDetail=_conversationDetail;
@property(retain, nonatomic) NSMutableArray *callRecords; // @synthesize callRecords=_callRecords;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *memberList; // @synthesize memberList=_memberList;
@property(retain, nonatomic) UICollectionView *participantListView; // @synthesize participantListView=_participantListView;
@property(retain, nonatomic) UIButton *callBtn; // @synthesize callBtn=_callBtn;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) FWCallConversation *conversation; // @synthesize conversation=_conversation;
- (id)getCollectionViewFlowLayout;
- (void)setupUI;
- (void)btnClick:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)handleDeviceOrientationDidChange:(id)arg1;
- (void)dataProcessing;
- (void)loadData;
- (void)userInfoDidLoad:(id)arg1;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

