//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FWChoiceModel : NSObject
{
    _Bool _open;
    _Bool _isSearchText;
    _Bool _isUser;
    NSString *_name;
    NSArray *_choiceArry;
    NSArray *_choiceValue;
    unsigned long long _type;
    NSString *_descText;
    NSString *_parmKey;
    double _height;
    double _openHeight;
}

+ (id)choiceModeWithName:(id)arg1 type:(unsigned long long)arg2 parmKey:(id)arg3;
- (void).cxx_destruct;
@property(nonatomic) double openHeight; // @synthesize openHeight=_openHeight;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) _Bool isUser; // @synthesize isUser=_isUser;
@property(nonatomic) _Bool isSearchText; // @synthesize isSearchText=_isSearchText;
@property(copy, nonatomic) NSString *parmKey; // @synthesize parmKey=_parmKey;
@property(copy, nonatomic) NSString *descText; // @synthesize descText=_descText;
@property(nonatomic, getter=isOpen) _Bool open; // @synthesize open=_open;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSArray *choiceValue; // @synthesize choiceValue=_choiceValue;
@property(retain, nonatomic) NSArray *choiceArry; // @synthesize choiceArry=_choiceArry;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;

@end

