//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UITextField;

@interface FWCommonInputViewController : UIViewController
{
    NSString *_text;
    CDUnknownBlockType _inputCompletion;
    UITextField *_textFiled;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UITextField *textFiled; // @synthesize textFiled=_textFiled;
@property(copy, nonatomic) CDUnknownBlockType inputCompletion; // @synthesize inputCompletion=_inputCompletion;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setupTextFiled;
- (void)inputCompletionClick;
- (void)viewDidLoad;

@end

