//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface FWCRDB : NSObject
{
    NSString *_dbPath;
    NSString *_tableCallRecord;
    NSString *_tableCallAttendRecord;
    NSString *_tableCallConversation;
    NSString *_tableCallConversationDetail;
    NSMutableDictionary *_lastMessageHit;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *lastMessageHit; // @synthesize lastMessageHit=_lastMessageHit;
@property(copy, nonatomic) NSString *tableCallConversationDetail; // @synthesize tableCallConversationDetail=_tableCallConversationDetail;
@property(copy, nonatomic) NSString *tableCallConversation; // @synthesize tableCallConversation=_tableCallConversation;
@property(copy, nonatomic) NSString *tableCallAttendRecord; // @synthesize tableCallAttendRecord=_tableCallAttendRecord;
@property(copy, nonatomic) NSString *tableCallRecord; // @synthesize tableCallRecord=_tableCallRecord;
@property(copy, nonatomic) NSString *dbPath; // @synthesize dbPath=_dbPath;
- (void)deleteCallConversationByChatId:(id)arg1;
- (id)queryCallConversationDetailByChatId:(id)arg1;
- (id)getAttendRecordsByCallId:(id)arg1;
- (id)getObjectsFrom:(Class)arg1;
- (void)insertObjects:(id)arg1 into:(id)arg2 needUpdate:(_Bool)arg3;
- (void)insertObject:(id)arg1 into:(id)arg2;
- (id)getCallRecordsPath;
- (id)callRecordsSqlitePath;
- (void)disconnect;
- (_Bool)isOpen;
- (id)init;

@end

