//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSMutableArray, NSString;

@interface FWDepartmentModel : MTLModel <MTLJSONSerializing>
{
    _Bool _hasnext;
    _Bool _isOpen;
    _Bool _isSelectAll;
    int _storageid;
    int _total_count;
    int _user_count;
    int _inline_count;
    int _showorder;
    int _depttype;
    NSString *_corpid;
    NSMutableArray *_userlist;
    NSString *_deptId;
    NSString *_parentid;
    NSString *_name;
    NSString *_english_name;
    NSString *_tanhan_name;
    NSString *_level;
}

+ (const struct WCTProperty *)tanhan_name;
+ (const struct WCTProperty *)depttype;
+ (const struct WCTProperty *)showorder;
+ (const struct WCTProperty *)inline_count;
+ (const struct WCTProperty *)hasnext;
+ (const struct WCTProperty *)user_count;
+ (const struct WCTProperty *)total_count;
+ (const struct WCTProperty *)english_name;
+ (const struct WCTProperty *)name;
+ (const struct WCTProperty *)parentid;
+ (const struct WCTProperty *)deptId;
+ (const struct WCTProperty *)corpid;
+ (const struct WCTProperty *)storageid;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(nonatomic) _Bool isSelectAll; // @synthesize isSelectAll=_isSelectAll;
@property(nonatomic) int depttype; // @synthesize depttype=_depttype;
@property(nonatomic) int showorder; // @synthesize showorder=_showorder;
@property(nonatomic) int inline_count; // @synthesize inline_count=_inline_count;
@property(nonatomic) int user_count; // @synthesize user_count=_user_count;
@property(nonatomic) int total_count; // @synthesize total_count=_total_count;
@property(retain, nonatomic) NSString *level; // @synthesize level=_level;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic) _Bool hasnext; // @synthesize hasnext=_hasnext;
@property(retain, nonatomic) NSString *tanhan_name; // @synthesize tanhan_name=_tanhan_name;
@property(retain, nonatomic) NSString *english_name; // @synthesize english_name=_english_name;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *parentid; // @synthesize parentid=_parentid;
@property(copy, nonatomic) NSString *deptId; // @synthesize deptId=_deptId;
@property(retain, nonatomic) NSMutableArray *userlist; // @synthesize userlist=_userlist;
@property(retain, nonatomic) NSString *corpid; // @synthesize corpid=_corpid;
@property(nonatomic) int storageid; // @synthesize storageid=_storageid;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToDepartment:(id)arg1;

@end

