//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWDoorAgentBaseController.h"

@class FWCompanyView, FWTenantModel, NSArray, NSDate, UIColor;

@interface FWDiscoverViewController : FWDoorAgentBaseController
{
    UIColor *_textColor;
    NSArray *_companies;
    FWCompanyView *_companyView;
    FWTenantModel *_refershmodel;
    NSDate *_lastDate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *lastDate; // @synthesize lastDate=_lastDate;
@property(retain, nonatomic) FWTenantModel *refershmodel; // @synthesize refershmodel=_refershmodel;
@property(nonatomic) __weak FWCompanyView *companyView; // @synthesize companyView=_companyView;
@property(retain, nonatomic) NSArray *companies; // @synthesize companies=_companies;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void)setTenantName:(id)arg1;
- (void)changeCompany:(id)arg1;
- (void)setupTitleBtnWithModel:(id)arg1;
- (void)handeleWotkBenchJsonDate:(id)arg1;
- (void)loadgentlListWithModel:(id)arg1;
- (void)loadJoinList;
- (void)loadUnreadWithModel:(id)arg1;
- (void)refershWorkBench;
- (void)viewDidLoad;

@end

