//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWWebViewController.h"

#import "FWDragCellCollectionViewDelegate-Protocol.h"
#import "FWDragCollectionViewDataSource-Protocol.h"
#import "FWDragNavgationViewDelegate-Protocol.h"
#import "FWDrapViewFlowLayoutDelegate-Protocol.h"
#import "FWModuleCollectionViewCellDelegate-Protocol.h"
#import "IMYWebViewDelegate-Protocol.h"

@class FWDragCellCollectionView, FWDragNavgationView, FWDrapViewFlowLayout, FWTitleBtn, FWWorkBenchPorTal, NSMutableArray, NSString;

@interface FWDoorAgentBaseController : FWWebViewController <FWDragCellCollectionViewDelegate, FWDragCollectionViewDataSource, FWDrapViewFlowLayoutDelegate, IMYWebViewDelegate, FWDragNavgationViewDelegate, FWModuleCollectionViewCellDelegate>
{
    _Bool _editing;
    FWTitleBtn *_titleButton;
    NSMutableArray *_modules;
    FWDragCellCollectionView *_collectionView;
    FWDrapViewFlowLayout *_customLayout;
    NSMutableArray *_dataSource;
    FWDragNavgationView *_dragNavView;
    FWWorkBenchPorTal *_porTal;
    NSMutableArray *_startDataSource;
    unsigned long long _type;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSMutableArray *startDataSource; // @synthesize startDataSource=_startDataSource;
@property(retain, nonatomic) FWWorkBenchPorTal *porTal; // @synthesize porTal=_porTal;
@property(nonatomic) __weak FWDragNavgationView *dragNavView; // @synthesize dragNavView=_dragNavView;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) FWDrapViewFlowLayout *customLayout; // @synthesize customLayout=_customLayout;
@property(nonatomic) __weak FWDragCellCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSMutableArray *modules; // @synthesize modules=_modules;
@property(retain, nonatomic) FWTitleBtn *titleButton; // @synthesize titleButton=_titleButton;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)changeStatusIsEditing:(_Bool)arg1;
- (void)dragNavgationView:(id)arg1 didClikType:(unsigned long long)arg2;
- (void)moduleCollectionViewCell:(id)arg1 didClickCycImageWithIndex:(long long)arg2 cycImage:(id)arg3;
- (void)removeElementFromCell:(id)arg1;
- (void)dragCellCollectionViewDidEndDrag:(id)arg1;
- (void)dragCellCollectionView:(id)arg1 beganDragAtPoint:(struct CGPoint)arg2 indexPath:(id)arg3;
- (_Bool)dragCellCollectionViewShouldBeginExchange:(id)arg1 sourceIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)dragCellCollectionViewShouldBeginMove:(id)arg1 indexPath:(id)arg2;
- (void)dragCellCollectionView:(id)arg1 newDataArrayAfterMove:(id)arg2;
- (id)dataSourceWithDragCellCollectionView:(id)arg1;
- (double)collectionView:(id)arg1 footerViewHeightOfItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 headerViewHeightOfItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeOfItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)handelResultWithType:(unsigned long long)arg1 request:(id)arg2 dic:(id)arg3;
- (void)setupCollectionView;
- (void)reloadRedCountView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

