//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;
@protocol FWDragNavgationViewDelegate;

@interface FWDragNavgationView : UIView
{
    id <FWDragNavgationViewDelegate> _delegate;
    UILabel *_mainLabel;
    UIButton *_leftBtn;
    UIButton *_rightBtn;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(nonatomic) __weak UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(nonatomic) __weak UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
@property(nonatomic) __weak id <FWDragNavgationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)btnClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

