//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FWEQuestion : NSObject
{
    NSString *_url;
    NSString *_question;
    NSString *_extra_column1;
    NSString *_extra_column2;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *extra_column2; // @synthesize extra_column2=_extra_column2;
@property(copy, nonatomic) NSString *extra_column1; // @synthesize extra_column1=_extra_column1;
@property(copy, nonatomic) NSString *question; // @synthesize question=_question;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;

@end

