//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FWFavoriteModel, NSString, UIImageView, UILabel;
@protocol FWFavoriteDetailViewDelegate;

@interface FWFavoriteDetailView : UIView
{
    NSString *_targetId;
    unsigned long long _type;
    NSString *_converTitle;
    FWFavoriteModel *_favoriteModel;
    id <FWFavoriteDetailViewDelegate> _delegete;
    UIView *_contentView;
    UILabel *_sendlabel;
    UIImageView *_iconView;
    UILabel *_nameLabel;
    UIView *_lineview;
    UILabel *_contentLabel;
    UIView *_bottomView;
    UIView *_sView;
    UILabel *_cancalLabel;
    UILabel *_makeLabel;
    UIView *_centerView;
    UIImageView *_arrowView;
    UIImageView *_contetImageView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *contetImageView; // @synthesize contetImageView=_contetImageView;
@property(nonatomic) __weak UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(nonatomic) __weak UIView *centerView; // @synthesize centerView=_centerView;
@property(nonatomic) __weak UILabel *makeLabel; // @synthesize makeLabel=_makeLabel;
@property(nonatomic) __weak UILabel *cancalLabel; // @synthesize cancalLabel=_cancalLabel;
@property(nonatomic) __weak UIView *sView; // @synthesize sView=_sView;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UIView *lineview; // @synthesize lineview=_lineview;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak UILabel *sendlabel; // @synthesize sendlabel=_sendlabel;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <FWFavoriteDetailViewDelegate> delegete; // @synthesize delegete=_delegete;
@property(retain, nonatomic) FWFavoriteModel *favoriteModel; // @synthesize favoriteModel=_favoriteModel;
@property(copy, nonatomic) NSString *converTitle; // @synthesize converTitle=_converTitle;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
- (void)makeSureDidClick;
- (void)centerViewdidClick;
- (void)hidden;
- (void)showFavoriteDetailViewInView:(id)arg1;
- (void)setSubViewMasory;
- (id)initWithFrame:(struct CGRect)arg1;

@end

