//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSDictionary, NSString, RCMessageContent, UIImage;

@interface FWFavoriteModel : MTLModel <MTLJSONSerializing>
{
    int _cellHeight;
    NSString *_fromUserid;
    NSString *_collectTime;
    NSString *_msgId;
    NSString *_targetId;
    NSDictionary *_msgInfo;
    NSString *_collectSource;
    RCMessageContent *_content;
    UIImage *_image;
    NSString *_contentText;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *contentText; // @synthesize contentText=_contentText;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) RCMessageContent *content; // @synthesize content=_content;
@property(nonatomic) int cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) NSString *collectSource; // @synthesize collectSource=_collectSource;
@property(retain, nonatomic) NSDictionary *msgInfo; // @synthesize msgInfo=_msgInfo;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(copy, nonatomic) NSString *msgId; // @synthesize msgId=_msgId;
@property(copy, nonatomic) NSString *collectTime; // @synthesize collectTime=_collectTime;
@property(copy, nonatomic) NSString *fromUserid; // @synthesize fromUserid=_fromUserid;

@end

