//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDictionary, RCDiscussion, UIButton, UIImageView, UILabel;

@interface FWGroupQRCodeViewController : UIViewController
{
    RCDiscussion *_currentDiscussion;
    UILabel *_nameLabel;
    UIImageView *_qrImageView;
    UIButton *_saveBtn;
    UIButton *_shareBtn;
    NSDictionary *_shareInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *shareInfo; // @synthesize shareInfo=_shareInfo;
@property(nonatomic) __weak UIButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(nonatomic) __weak UIButton *saveBtn; // @synthesize saveBtn=_saveBtn;
@property(nonatomic) __weak UIImageView *qrImageView; // @synthesize qrImageView=_qrImageView;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) RCDiscussion *currentDiscussion; // @synthesize currentDiscussion=_currentDiscussion;
- (void)shareAction:(id)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveAction:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

