//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "LFPhotoEditingControllerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "ZYQAssetPickerControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, ReviewView, TransitionDelegate, UIButton, UICollectionView, UIImage, UIView, UIWindow;
@protocol FWImagePickerViewControllerDelegate;

@interface FWImagePickerViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, UIImagePickerControllerDelegate, UINavigationControllerDelegate, ZYQAssetPickerControllerDelegate, LFPhotoEditingControllerDelegate>
{
    id <FWImagePickerViewControllerDelegate> delegate;
    ReviewView *reviewView;
    _Bool _isVisible;
    _Bool _openSingleSelection;
    TransitionDelegate *transitionController;
    double _animationTime;
    UICollectionView *_collectionView;
    UIButton *_photoLibraryBtn;
    UIButton *_cameraBtn;
    UIButton *_cancelBtn;
    UIButton *_editBtn;
    UIButton *_oriImageBtn;
    UIViewController *_targetController;
    UIWindow *_window;
    UIView *_backgroundView;
    UIView *_imagePickerView;
    NSMutableArray *_assets;
    NSMutableArray *_imageArrays;
    NSMutableArray *_selectedArray;
    UIView *_separator1;
    UIView *_separator2;
    UIView *_separator3;
    UIView *_separator4;
    UIImage *_originalImage;
    struct CGRect _imagePickerFrame;
    struct CGRect _hiddenFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) UIView *separator4; // @synthesize separator4=_separator4;
@property(retain, nonatomic) UIView *separator3; // @synthesize separator3=_separator3;
@property(retain, nonatomic) UIView *separator2; // @synthesize separator2=_separator2;
@property(retain, nonatomic) UIView *separator1; // @synthesize separator1=_separator1;
@property(retain, nonatomic) NSMutableArray *selectedArray; // @synthesize selectedArray=_selectedArray;
@property(retain, nonatomic) NSMutableArray *imageArrays; // @synthesize imageArrays=_imageArrays;
@property(retain, nonatomic) NSMutableArray *assets; // @synthesize assets=_assets;
@property(nonatomic) struct CGRect hiddenFrame; // @synthesize hiddenFrame=_hiddenFrame;
@property(nonatomic) struct CGRect imagePickerFrame; // @synthesize imagePickerFrame=_imagePickerFrame;
@property(retain, nonatomic) UIView *imagePickerView; // @synthesize imagePickerView=_imagePickerView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) UIViewController *targetController; // @synthesize targetController=_targetController;
@property(retain, nonatomic) UIButton *oriImageBtn; // @synthesize oriImageBtn=_oriImageBtn;
@property(retain, nonatomic) UIButton *editBtn; // @synthesize editBtn=_editBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIButton *cameraBtn; // @synthesize cameraBtn=_cameraBtn;
@property(retain, nonatomic) UIButton *photoLibraryBtn; // @synthesize photoLibraryBtn=_photoLibraryBtn;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool openSingleSelection; // @synthesize openSingleSelection=_openSingleSelection;
@property(nonatomic) double animationTime; // @synthesize animationTime=_animationTime;
@property _Bool isVisible; // @synthesize isVisible=_isVisible;
@property(retain, nonatomic) TransitionDelegate *transitionController; // @synthesize transitionController;
@property(nonatomic) id <FWImagePickerViewControllerDelegate> delegate; // @synthesize delegate;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismiss;
- (void)showImagePickerInController:(id)arg1 animated:(_Bool)arg2;
- (void)showImagePickerInController:(id)arg1;
- (void)backBtnPressed:(id)arg1;
- (void)rightBtnPressed:(id)arg1;
- (id)scaleImage:(id)arg1 toScale:(float)arg2;
- (id)titleViewForReviewView;
- (void)editImage:(id)arg1;
- (void)lf_PhotoEditingController:(id)arg1 didFinishPhotoEdit:(id)arg2;
- (void)lf_PhotoEditingControllerDidCancel:(id)arg1;
- (void)assetPickerControllerDidEdit:(id)arg1;
- (void)assetPickerControllerDidMaximum:(id)arg1;
- (void)assetPickerControllerDidCancel:(id)arg1;
- (void)assetPickerController:(id)arg1 didFinishPickingImageArray:(id)arg2;
- (void)assetPickerControllerDidFinishPickingVideo;
- (void)assetPickerController:(id)arg1 didFinishPickingAssets:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)selectFromLibraryWasPressed;
- (void)takePhotoWasPressed;
- (void)editPhotoWasPressed;
- (void)oriImageBtnClick:(id)arg1;
- (void)setGetFullScreenImage:(CDUnknownBlockType)arg1 asset:(id)arg2;
- (void)enumerateAssetsInAssetCollection:(id)arg1 original:(_Bool)arg2;
- (void)getCameraRollImages;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)imagePickerViewSetup;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)setupView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

