//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class FWEncryptConfig, FWLoginConfigInfo, FWLoginInfo, FWPrivacyInfo, FWWelcomeInfo, NSArray, NSString;

@interface FWLoginConfing : MTLModel <MTLJSONSerializing>
{
    int _update_check_ios;
    int _force_update_ios;
    NSString *_login_mode_app;
    NSString *_enable_register;
    NSString *_enable_retrieve;
    NSString *_enable_login_captcha;
    NSString *_enable_sms_captcha;
    NSString *_enable_update_baseinfo;
    NSString *_enable_update_password;
    NSString *_custom_login_page;
    NSString *_custom_retrieve_page;
    NSString *_cdn_url;
    NSString *_server_version;
    NSString *_security_version;
    FWWelcomeInfo *_welcome_info;
    FWLoginInfo *_login_info;
    NSArray *_langlist;
    FWLoginConfigInfo *_config_info;
    FWPrivacyInfo *_privacy_info;
    FWEncryptConfig *_h5_publickey;
}

+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(retain, nonatomic) FWEncryptConfig *h5_publickey; // @synthesize h5_publickey=_h5_publickey;
@property(retain, nonatomic) FWPrivacyInfo *privacy_info; // @synthesize privacy_info=_privacy_info;
@property(retain, nonatomic) FWLoginConfigInfo *config_info; // @synthesize config_info=_config_info;
@property(retain, nonatomic) NSArray *langlist; // @synthesize langlist=_langlist;
@property(retain, nonatomic) FWLoginInfo *login_info; // @synthesize login_info=_login_info;
@property(retain, nonatomic) FWWelcomeInfo *welcome_info; // @synthesize welcome_info=_welcome_info;
@property(copy, nonatomic) NSString *security_version; // @synthesize security_version=_security_version;
@property(copy, nonatomic) NSString *server_version; // @synthesize server_version=_server_version;
@property(copy, nonatomic) NSString *cdn_url; // @synthesize cdn_url=_cdn_url;
@property(nonatomic) int force_update_ios; // @synthesize force_update_ios=_force_update_ios;
@property(nonatomic) int update_check_ios; // @synthesize update_check_ios=_update_check_ios;
@property(copy, nonatomic) NSString *custom_retrieve_page; // @synthesize custom_retrieve_page=_custom_retrieve_page;
@property(copy, nonatomic) NSString *custom_login_page; // @synthesize custom_login_page=_custom_login_page;
@property(copy, nonatomic) NSString *enable_update_password; // @synthesize enable_update_password=_enable_update_password;
@property(copy, nonatomic) NSString *enable_update_baseinfo; // @synthesize enable_update_baseinfo=_enable_update_baseinfo;
@property(copy, nonatomic) NSString *enable_sms_captcha; // @synthesize enable_sms_captcha=_enable_sms_captcha;
@property(copy, nonatomic) NSString *enable_login_captcha; // @synthesize enable_login_captcha=_enable_login_captcha;
@property(copy, nonatomic) NSString *enable_retrieve; // @synthesize enable_retrieve=_enable_retrieve;
@property(copy, nonatomic) NSString *enable_register; // @synthesize enable_register=_enable_register;
@property(copy, nonatomic) NSString *login_mode_app; // @synthesize login_mode_app=_login_mode_app;
- (id)init;

@end

