//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIButton;

@interface FWMessageClassView : UIView
{
    id _delegate;
    UIView *_upline;
    UIView *_bottomline;
    NSMutableArray *_btns;
    UIButton *_selectBtn;
    UIButton *_deleBtn;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *deleBtn; // @synthesize deleBtn=_deleBtn;
@property(retain, nonatomic) UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(retain, nonatomic) NSMutableArray *btns; // @synthesize btns=_btns;
@property(nonatomic) __weak UIView *bottomline; // @synthesize bottomline=_bottomline;
@property(nonatomic) __weak UIView *upline; // @synthesize upline=_upline;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)hidleAllRed;
- (void)dismissRedTipWithShowMsgClassType:(long long)arg1;
- (void)showRedTipWithShowMsgClassType:(long long)arg1;
- (void)isshowNoDistrubViewWithCount:(long long)arg1;
- (void)cancalAllClassSelect;
- (void)btnDidClick:(id)arg1;
- (void)deleBtnDidClick;
- (id)initWithFrame:(struct CGRect)arg1;

@end

