//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWTableViewController.h"

#import "QRReaderViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FWMIneStatusView, FWPersonModel, NSMutableArray, NSString, NSURLSessionDataTask, UIColor, UIImageView, UILabel;

@interface FWMineViewController : FWTableViewController <UIActionSheetDelegate, QRReaderViewControllerDelegate>
{
    _Bool _cancalAnimated;
    NSMutableArray *_data;
    UIColor *_textColor;
    UIImageView *_avatarView;
    UILabel *_nameLabel;
    FWMIneStatusView *_statusView;
    UILabel *_compLabel;
    FWPersonModel *_personModel;
    NSURLSessionDataTask *_task;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(retain, nonatomic) FWPersonModel *personModel; // @synthesize personModel=_personModel;
@property(nonatomic) __weak UILabel *compLabel; // @synthesize compLabel=_compLabel;
@property(nonatomic) __weak FWMIneStatusView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) _Bool cancalAnimated; // @synthesize cancalAnimated=_cancalAnimated;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
- (void)cancelQRReaderRequest;
- (void)QRReaderDidFinishRead:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openUrlWithSysid:(id)arg1 urlType:(int)arg2;
- (void)headerTapAction;
- (void)statusAction;
- (void)qrCodeAction:(id)arg1;
- (void)hideMenuItem:(id)arg1;
- (void)dealloc;
- (void)setupData;
- (void)updateData;
- (void)setupHeadView;
- (void)setupTableView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

