//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FWSearchHelper, NSMutableArray, NSString, UISearchController, UITableView;

@interface FWMyGroupViewController : FWViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isSelectPersonModel;
    _Bool _isCreatChatSelPerson;
    _Bool _loadFinish;
    int _pageNumber;
    CDUnknownBlockType _didSelectGroupBlock;
    NSMutableArray *_dataSource;
    UITableView *_tableView;
    UISearchController *_searchController;
    FWSearchHelper *_searchHelper;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FWSearchHelper *searchHelper; // @synthesize searchHelper=_searchHelper;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) _Bool loadFinish; // @synthesize loadFinish=_loadFinish;
@property(nonatomic) int pageNumber; // @synthesize pageNumber=_pageNumber;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool isCreatChatSelPerson; // @synthesize isCreatChatSelPerson=_isCreatChatSelPerson;
@property(copy, nonatomic) CDUnknownBlockType didSelectGroupBlock; // @synthesize didSelectGroupBlock=_didSelectGroupBlock;
@property(nonatomic) _Bool isSelectPersonModel; // @synthesize isSelectPersonModel=_isSelectPersonModel;
- (void)didReceiveMemoryWarning;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)loadData;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

