//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UIButton, UILabel, UIScrollView;

@interface FWPersonSectionView : UIView
{
    NSArray *_perArry;
    CDUnknownBlockType _choseHrTananName;
    NSMutableArray *_totalHers;
    UIScrollView *_scrollView;
    UILabel *_complabel;
    UIButton *_selBtn;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *selBtn; // @synthesize selBtn=_selBtn;
@property(nonatomic) __weak UILabel *complabel; // @synthesize complabel=_complabel;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSMutableArray *totalHers; // @synthesize totalHers=_totalHers;
@property(copy, nonatomic) CDUnknownBlockType choseHrTananName; // @synthesize choseHrTananName=_choseHrTananName;
@property(retain, nonatomic) NSArray *perArry; // @synthesize perArry=_perArry;
- (void)layoutSubviews;
- (void)btnClick:(id)arg1;
- (void)setMoreHrWithArry:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

