//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWViewController.h"

#import "FWFriendTableViewCellDelegate-Protocol.h"
#import "MGSwipeTableCellDelegate-Protocol.h"
#import "MJNIndexViewDataSource-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FWSearchHelper, MJNIndexView, NSDictionary, NSMutableArray, NSString, UITableView;

@interface FWPersonListViewController : FWViewController <MJNIndexViewDataSource, MGSwipeTableCellDelegate, FWFriendTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isCreatChatSelPerson;
    _Bool _isTransferGroupOwnersForCurSearch;
    int _mode;
    int _showtype;
    NSString *_corpid;
    NSDictionary *_dataSourceDict;
    NSMutableArray *_dataSource;
    NSMutableArray *_sectionArray;
    UITableView *_tableView;
    FWSearchHelper *_searchHelper;
    MJNIndexView *_indexView;
    CDUnknownBlockType _haveDelePerson;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isTransferGroupOwnersForCurSearch; // @synthesize isTransferGroupOwnersForCurSearch=_isTransferGroupOwnersForCurSearch;
@property(copy, nonatomic) CDUnknownBlockType haveDelePerson; // @synthesize haveDelePerson=_haveDelePerson;
@property(retain, nonatomic) MJNIndexView *indexView; // @synthesize indexView=_indexView;
@property(nonatomic) _Bool isCreatChatSelPerson; // @synthesize isCreatChatSelPerson=_isCreatChatSelPerson;
@property(retain, nonatomic) FWSearchHelper *searchHelper; // @synthesize searchHelper=_searchHelper;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int showtype; // @synthesize showtype=_showtype;
@property(retain, nonatomic) NSMutableArray *sectionArray; // @synthesize sectionArray=_sectionArray;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSDictionary *dataSourceDict; // @synthesize dataSourceDict=_dataSourceDict;
@property(retain, nonatomic) NSString *corpid; // @synthesize corpid=_corpid;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void)personAttend:(id)arg1;
- (_Bool)swipeTableCell:(id)arg1 tappedButtonAtIndex:(long long)arg2 direction:(long long)arg3 fromExpansion:(_Bool)arg4;
- (_Bool)swipeTableCell:(id)arg1 canSwipe:(long long)arg2;
- (void)swipeTableCellWillBeginSwiping:(id)arg1;
- (void)swipeTableCellWillEndSwiping:(id)arg1;
- (void)sectionForSectionMJNIndexTitle:(id)arg1 atIndex:(long long)arg2;
- (id)sectionIndexTitlesForMJNIndexView:(id)arg1;
- (void)pushToSuboder:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)addIndexView;
- (void)reloNewDate;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

