//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "FWUserHeadViewCellDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class FWPersonModel, FWSettingItem, NSMutableArray, NSString;

@interface FWPersonInfoViewController : UITableViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate, FWUserHeadViewCellDelegate>
{
    FWPersonModel *_persomModel;
    CDUnknownBlockType _refershHeadIcon;
    NSMutableArray *_dataSources;
    FWSettingItem *_iconItem;
    NSMutableArray *_photos;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) FWSettingItem *iconItem; // @synthesize iconItem=_iconItem;
@property(retain, nonatomic) NSMutableArray *dataSources; // @synthesize dataSources=_dataSources;
@property(copy, nonatomic) CDUnknownBlockType refershHeadIcon; // @synthesize refershHeadIcon=_refershHeadIcon;
@property(retain, nonatomic) FWPersonModel *persomModel; // @synthesize persomModel=_persomModel;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)baseuserUpdateWithParm:(id)arg1 settintItem:(id)arg2 result:(id)arg3 indexpath:(id)arg4;
- (void)showInPutVcWithItem:(id)arg1 text:(id)arg2 Parmkey:(id)arg3 indexPath:(id)arg4;
- (void)showMakeSureAlertWithItem:(id)arg1 result:(id)arg2 Parmkey:(id)arg3 indexPath:(id)arg4;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)handImageRowWithItem:(id)arg1;
- (void)userHeadViewCelldidClickHeadView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)itemWithTitle:(id)arg1 SubTitle:(id)arg2;
- (void)setupData;
- (void)setupTableView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

