//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FWPersonModel, FWWorkStatus, NSLayoutConstraint, NSMutableArray, UIButton, UIImageView, UILabel;

@interface FWPersonDetailHeadView : UIView
{
    _Bool _bgCanClick;
    double _backHeight;
    FWPersonModel *_personModel;
    CDUnknownBlockType _headViewClick;
    FWWorkStatus *_status;
    UIView *_backView;
    UILabel *_nameLabel;
    UILabel *_compLabel;
    UIImageView *_iconView;
    UIButton *_sexButton;
    NSLayoutConstraint *_secHeight;
    UIImageView *_expressView;
    UILabel *_statusLabel;
    UIView *_lineView;
    double _workIconW;
    double _workViewH;
    NSLayoutConstraint *_statusIconW;
    NSLayoutConstraint *_statusViewH;
    NSMutableArray *_photos;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(nonatomic) __weak NSLayoutConstraint *statusViewH; // @synthesize statusViewH=_statusViewH;
@property(nonatomic) __weak NSLayoutConstraint *statusIconW; // @synthesize statusIconW=_statusIconW;
@property(nonatomic) double workViewH; // @synthesize workViewH=_workViewH;
@property(nonatomic) double workIconW; // @synthesize workIconW=_workIconW;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(nonatomic) __weak UIImageView *expressView; // @synthesize expressView=_expressView;
@property(nonatomic) __weak NSLayoutConstraint *secHeight; // @synthesize secHeight=_secHeight;
@property(nonatomic) __weak UIButton *sexButton; // @synthesize sexButton=_sexButton;
@property(nonatomic) __weak UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak UILabel *compLabel; // @synthesize compLabel=_compLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) FWWorkStatus *status; // @synthesize status=_status;
@property(copy, nonatomic) CDUnknownBlockType headViewClick; // @synthesize headViewClick=_headViewClick;
@property(nonatomic, getter=isBgCanClick) _Bool bgCanClick; // @synthesize bgCanClick=_bgCanClick;
@property(retain, nonatomic) FWPersonModel *personModel; // @synthesize personModel=_personModel;
@property(nonatomic) double backHeight; // @synthesize backHeight=_backHeight;
- (void)iconViewClick;
- (void)bgClick;
- (void)awakeFromNib;

@end

