//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class NSString, UIColor, UILabel;

@interface FWPlacehoderTextView : UITextView
{
    NSString *_placehoder;
    UIColor *_placehoderColor;
    UILabel *_placehoderLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *placehoderLabel; // @synthesize placehoderLabel=_placehoderLabel;
@property(retain, nonatomic) UIColor *placehoderColor; // @synthesize placehoderColor=_placehoderColor;
@property(copy, nonatomic) NSString *placehoder; // @synthesize placehoder=_placehoder;
- (void)layoutSubviews;
- (void)setFont:(id)arg1;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)textDidChange;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

