//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FWPrivacyInfo : MTLModel <MTLJSONSerializing>
{
    int _enable_login;
    int _login_check;
    int _login_default;
    int _enable_about;
    NSString *_login_txt;
    NSString *_login_color;
    NSString *_login_link;
    NSString *_login_tips;
    NSString *_about_txt;
    NSString *_about_link;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *about_link; // @synthesize about_link=_about_link;
@property(copy, nonatomic) NSString *about_txt; // @synthesize about_txt=_about_txt;
@property(nonatomic) int enable_about; // @synthesize enable_about=_enable_about;
@property(copy, nonatomic) NSString *login_tips; // @synthesize login_tips=_login_tips;
@property(copy, nonatomic) NSString *login_link; // @synthesize login_link=_login_link;
@property(copy, nonatomic) NSString *login_color; // @synthesize login_color=_login_color;
@property(copy, nonatomic) NSString *login_txt; // @synthesize login_txt=_login_txt;
@property(nonatomic) int login_default; // @synthesize login_default=_login_default;
@property(nonatomic) int login_check; // @synthesize login_check=_login_check;
@property(nonatomic) int enable_login; // @synthesize enable_login=_enable_login;
- (id)init;

@end

