//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FWSearchMsg : NSObject
{
    NSString *_msg_id;
    long long _ID;
    NSString *_target_id;
    NSString *_extra_column1;
    NSString *_extra_column2;
    NSString *_extra_column3;
}

+ (const struct WCTProperty *)extra_column3;
+ (const struct WCTProperty *)extra_column2;
+ (const struct WCTProperty *)extra_column1;
+ (const struct WCTProperty *)target_id;
+ (const struct WCTProperty *)ID;
+ (const struct WCTProperty *)msg_id;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *extra_column3; // @synthesize extra_column3=_extra_column3;
@property(copy, nonatomic) NSString *extra_column2; // @synthesize extra_column2=_extra_column2;
@property(copy, nonatomic) NSString *extra_column1; // @synthesize extra_column1=_extra_column1;
@property(copy, nonatomic) NSString *target_id; // @synthesize target_id=_target_id;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
@property(copy, nonatomic) NSString *msg_id; // @synthesize msg_id=_msg_id;

@end

