//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWMineSettingViewController.h"

#import "PGPickerViewDataSource-Protocol.h"
#import "PGPickerViewDelegate-Protocol.h"

@class FWSettingItem, NSArray, NSString, PGPickerView;

@interface FWSecutityViewController : FWMineSettingViewController <PGPickerViewDelegate, PGPickerViewDataSource>
{
    _Bool _face_hasset;
    NSArray *_intervalArray;
    PGPickerView *_pickerView;
    NSString *_pickerSelectString;
    FWSettingItem *_item10;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool face_hasset; // @synthesize face_hasset=_face_hasset;
@property(retain, nonatomic) FWSettingItem *item10; // @synthesize item10=_item10;
@property(copy, nonatomic) NSString *pickerSelectString; // @synthesize pickerSelectString=_pickerSelectString;
@property(retain, nonatomic) PGPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) NSArray *intervalArray; // @synthesize intervalArray=_intervalArray;
- (void)didReceiveMemoryWarning;
- (void)settingSwitchCellForItem:(id)arg1 didChangeStatus:(_Bool)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configData;
- (void)tapAction:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

