//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWSBaseCell.h"

@class FWSModel, NSLayoutConstraint, UIImageView, UILabel;

@interface FWSMsgCell : FWSBaseCell
{
    UILabel *_timeLabel;
    UIImageView *_headerImageVI;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    NSLayoutConstraint *_heightConstant;
    FWSModel *_model;
    UIImageView *_iconVIew;
    UIImageView *_secretImageView;
    NSLayoutConstraint *_textConstraints;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *textConstraints; // @synthesize textConstraints=_textConstraints;
@property(retain, nonatomic) UIImageView *secretImageView; // @synthesize secretImageView=_secretImageView;
@property(nonatomic) __weak UIImageView *iconVIew; // @synthesize iconVIew=_iconVIew;
@property(retain, nonatomic) FWSModel *model; // @synthesize model=_model;
@property(retain, nonatomic) NSLayoutConstraint *heightConstant; // @synthesize heightConstant=_heightConstant;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *headerImageVI; // @synthesize headerImageVI=_headerImageVI;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)ajustBottomLine:(long long)arg1 totalCount:(long long)arg2;
- (void)awakeFromNib;

@end

