//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSDictionary, NSString;

@interface FWTask : MTLModel <MTLJSONSerializing>
{
    int _task_type;
    int _task_cycle;
    int _task_time_type;
    int _location_map_type;
    int _waitTime;
    int _enable_timimg;
    int _enable_login;
    int _enable_relogin;
    int _enable_sendmsg;
    int _enable_openlink;
    NSString *_task_id;
    NSString *_task_starttime;
    NSString *_task_endtime;
    NSDictionary *_time_setting;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(nonatomic) int enable_openlink; // @synthesize enable_openlink=_enable_openlink;
@property(nonatomic) int enable_sendmsg; // @synthesize enable_sendmsg=_enable_sendmsg;
@property(nonatomic) int enable_relogin; // @synthesize enable_relogin=_enable_relogin;
@property(nonatomic) int enable_login; // @synthesize enable_login=_enable_login;
@property(nonatomic) int enable_timimg; // @synthesize enable_timimg=_enable_timimg;
@property(nonatomic) int waitTime; // @synthesize waitTime=_waitTime;
@property(retain, nonatomic) NSDictionary *time_setting; // @synthesize time_setting=_time_setting;
@property(retain, nonatomic) NSString *task_endtime; // @synthesize task_endtime=_task_endtime;
@property(retain, nonatomic) NSString *task_starttime; // @synthesize task_starttime=_task_starttime;
@property(nonatomic) int location_map_type; // @synthesize location_map_type=_location_map_type;
@property(nonatomic) int task_time_type; // @synthesize task_time_type=_task_time_type;
@property(nonatomic) int task_cycle; // @synthesize task_cycle=_task_cycle;
@property(nonatomic) int task_type; // @synthesize task_type=_task_type;
@property(retain, nonatomic) NSString *task_id; // @synthesize task_id=_task_id;
- (id)init;

@end

