//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class FWTaskFoucesModel, MJRefreshAutoNormalFooter, NSMutableArray, NSString, UITableView;

@interface FWTaskFocusReplyViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    _Bool _needRefersh;
    FWTaskFoucesModel *_taskModel;
    CDUnknownBlockType _reloadDing;
    NSMutableArray *_dataSource;
    UITableView *_tableView;
    double _lastTime;
    MJRefreshAutoNormalFooter *_footer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MJRefreshAutoNormalFooter *footer; // @synthesize footer=_footer;
@property(nonatomic, getter=isNeedRefersh) _Bool needRefersh; // @synthesize needRefersh=_needRefersh;
@property(nonatomic) double lastTime; // @synthesize lastTime=_lastTime;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(copy, nonatomic) CDUnknownBlockType reloadDing; // @synthesize reloadDing=_reloadDing;
@property(retain, nonatomic) FWTaskFoucesModel *taskModel; // @synthesize taskModel=_taskModel;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)dealloc;
- (void)didReceiveMessageNotification:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)addReplyView;
- (void)loadNewData;
- (void)loadMoreData;
- (void)setupRefersh;
- (void)setupTableView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)deleteTaskModel:(id)arg1;
- (void)setupNav;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

