//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"
#import "WCTTableCoding-Protocol.h"

@class NSDictionary, NSString;

@interface FWTenantModel : MTLModel <WCTTableCoding, MTLJSONSerializing>
{
    NSString *_tenantName;
    NSString *_internalBaseClassIdentifier;
    NSString *_createTime;
    NSString *_corpid;
    double _maxuser;
    NSDictionary *_logo;
}

+ (id)JSONKeyPathsByPropertyKey;
+ (const struct WCTProperty *)logo;
+ (const struct WCTProperty *)maxuser;
+ (const struct WCTProperty *)corpid;
+ (const struct WCTProperty *)createTime;
+ (const struct WCTProperty *)internalBaseClassIdentifier;
+ (const struct WCTProperty *)tenantName;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *logo; // @synthesize logo=_logo;
@property(nonatomic) double maxuser; // @synthesize maxuser=_maxuser;
@property(retain, nonatomic) NSString *corpid; // @synthesize corpid=_corpid;
@property(retain, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *internalBaseClassIdentifier; // @synthesize internalBaseClassIdentifier=_internalBaseClassIdentifier;
@property(retain, nonatomic) NSString *tenantName; // @synthesize tenantName=_tenantName;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

