//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class FWAppTheme, NSArray, NSString;

@interface FWThemeData : MTLModel <MTLJSONSerializing>
{
    NSArray *_tenantlist;
    NSString *_version;
    FWAppTheme *_theme;
}

+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(retain, nonatomic) FWAppTheme *theme; // @synthesize theme=_theme;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSArray *tenantlist; // @synthesize tenantlist=_tenantlist;

@end

