//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWChatViewController.h"

#import "KSPhotoBrowserDelegate-Protocol.h"

@class FWMessageModel, NSMutableArray, NSString, RCConversation;

@interface FWUniteMessageViewController : FWChatViewController <KSPhotoBrowserDelegate>
{
    NSString *_uniteMsgId;
    NSMutableArray *_photos;
    RCConversation *_FWConversation;
    FWMessageModel *_longPressSelectedModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FWMessageModel *longPressSelectedModel; // @synthesize longPressSelectedModel=_longPressSelectedModel;
@property(retain, nonatomic) RCConversation *FWConversation; // @synthesize FWConversation=_FWConversation;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
@property(copy, nonatomic) NSString *uniteMsgId; // @synthesize uniteMsgId=_uniteMsgId;
- (id)figureoutImagedataArray;
- (void)presentImagePreviewController:(id)arg1 messageCell:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)handleReadUnreadMessageWithCell:(id)arg1;
- (void)didLongPressCellPortrait:(id)arg1;
- (void)onCopyMessage:(id)arg1;
- (void)didLongTouchMessageCell:(id)arg1 inView:(id)arg2;
- (void)getNoticeHistoryData;
- (void)loadLatestHistoryMessage;
- (void)refreshIfNeeded;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

