//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSNumber, NSString;

@interface FWWaterContent : MTLModel <MTLJSONSerializing>
{
    NSString *_content_val;
    NSNumber *_font_size;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *font_size; // @synthesize font_size=_font_size;
@property(copy, nonatomic) NSString *content_val; // @synthesize content_val=_content_val;

@end

