//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FWerrorDelegate-Protocol.h"
#import "IMYWebViewDelegate-Protocol.h"
#import "QRReaderViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class AMapLocationManager, FWAppThemeNav, FWConversationModel, FWExtendModel, FWModuleModel, FWNavBarButtonHelper, FWWebView, FWerrorView, NSArray, NSDictionary, NSString, NSURL, TTPopupView, UIColor, UILabel, UIView, WKWebViewJavascriptBridge, WaterMarkView;

@interface FWWebViewController : UIViewController <UIGestureRecognizerDelegate, QRReaderViewControllerDelegate, IMYWebViewDelegate, FWerrorDelegate>
{
    _Bool _isConversationVC;
    _Bool _disableBackGesture;
    _Bool _hideNavegation;
    _Bool _hideStatusBar;
    _Bool _isTopLevel;
    _Bool _debugMode;
    _Bool _leftDefault;
    _Bool _isHiddenRightMore;
    _Bool _preLoadWorkBench;
    _Bool _isEHelper;
    _Bool _isCustomWeb;
    _Bool _isOpenOnline;
    _Bool _followScreenRotation;
    _Bool _isAddedWebView;
    _Bool _isHavedConfigUrl;
    NSString *_targetId;
    FWWebView *_webView;
    FWModuleModel *_model;
    FWExtendModel *_extendModel;
    NSDictionary *_linkMsgDict;
    NSDictionary *_applicatonDict;
    NSDictionary *_previewDict;
    NSURL *_url;
    NSURL *_baseFileURL;
    NSURL *_baseURL;
    CDUnknownBlockType _changeUrlComple;
    NSDictionary *_jsConfig;
    NSArray *_headers;
    NSDictionary *_configDict;
    FWConversationModel *_conversation;
    NSString *_barColorStr;
    UIColor *_titleColor;
    UIColor *_itemColor;
    NSDictionary *_menuDict;
    WaterMarkView *_waterView;
    UILabel *_titleLabel;
    FWAppThemeNav *_themeNav;
    NSDictionary *_prelocationDict;
    AMapLocationManager *_locationManager;
    FWerrorView *_errorView;
    CDUnknownBlockType _secondaryVerificationBlock;
    CDUnknownBlockType _leftItemClick;
    WKWebViewJavascriptBridge *_bridge;
    FWNavBarButtonHelper *_navHelper;
    id _popDelegate;
    UIView *_blankView;
    TTPopupView *_popup;
}

- (void).cxx_destruct;
@property(nonatomic) __weak TTPopupView *popup; // @synthesize popup=_popup;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(retain, nonatomic) id popDelegate; // @synthesize popDelegate=_popDelegate;
@property(nonatomic) _Bool isHavedConfigUrl; // @synthesize isHavedConfigUrl=_isHavedConfigUrl;
@property(retain, nonatomic) FWNavBarButtonHelper *navHelper; // @synthesize navHelper=_navHelper;
@property(nonatomic) _Bool isAddedWebView; // @synthesize isAddedWebView=_isAddedWebView;
@property(nonatomic) _Bool followScreenRotation; // @synthesize followScreenRotation=_followScreenRotation;
@property(retain, nonatomic) WKWebViewJavascriptBridge *bridge; // @synthesize bridge=_bridge;
@property(copy, nonatomic) CDUnknownBlockType leftItemClick; // @synthesize leftItemClick=_leftItemClick;
@property(copy, nonatomic) CDUnknownBlockType secondaryVerificationBlock; // @synthesize secondaryVerificationBlock=_secondaryVerificationBlock;
@property(retain, nonatomic) FWerrorView *errorView; // @synthesize errorView=_errorView;
@property(nonatomic) _Bool isOpenOnline; // @synthesize isOpenOnline=_isOpenOnline;
@property(nonatomic) _Bool isCustomWeb; // @synthesize isCustomWeb=_isCustomWeb;
@property(nonatomic) _Bool isEHelper; // @synthesize isEHelper=_isEHelper;
@property(retain, nonatomic) AMapLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSDictionary *prelocationDict; // @synthesize prelocationDict=_prelocationDict;
@property(nonatomic) _Bool preLoadWorkBench; // @synthesize preLoadWorkBench=_preLoadWorkBench;
@property(nonatomic) _Bool isHiddenRightMore; // @synthesize isHiddenRightMore=_isHiddenRightMore;
@property(retain, nonatomic) FWAppThemeNav *themeNav; // @synthesize themeNav=_themeNav;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak WaterMarkView *waterView; // @synthesize waterView=_waterView;
@property(retain, nonatomic) NSDictionary *menuDict; // @synthesize menuDict=_menuDict;
@property(nonatomic) _Bool leftDefault; // @synthesize leftDefault=_leftDefault;
@property(retain, nonatomic) UIColor *itemColor; // @synthesize itemColor=_itemColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSString *barColorStr; // @synthesize barColorStr=_barColorStr;
@property(retain, nonatomic) FWConversationModel *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) NSDictionary *configDict; // @synthesize configDict=_configDict;
@property(nonatomic) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) _Bool isTopLevel; // @synthesize isTopLevel=_isTopLevel;
@property(retain, nonatomic) NSArray *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSDictionary *jsConfig; // @synthesize jsConfig=_jsConfig;
@property(copy, nonatomic) CDUnknownBlockType changeUrlComple; // @synthesize changeUrlComple=_changeUrlComple;
@property(nonatomic) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property(nonatomic) _Bool hideNavegation; // @synthesize hideNavegation=_hideNavegation;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(retain, nonatomic) NSURL *baseFileURL; // @synthesize baseFileURL=_baseFileURL;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSDictionary *previewDict; // @synthesize previewDict=_previewDict;
@property(retain, nonatomic) NSDictionary *applicatonDict; // @synthesize applicatonDict=_applicatonDict;
@property(retain, nonatomic) NSDictionary *linkMsgDict; // @synthesize linkMsgDict=_linkMsgDict;
@property(retain, nonatomic) FWExtendModel *extendModel; // @synthesize extendModel=_extendModel;
@property(retain, nonatomic) FWModuleModel *model; // @synthesize model=_model;
@property(retain, nonatomic) FWWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(nonatomic) _Bool disableBackGesture; // @synthesize disableBackGesture=_disableBackGesture;
@property(nonatomic) _Bool isConversationVC; // @synthesize isConversationVC=_isConversationVC;
- (void)restoreToDeviceOrientationPortrait;
- (void)orientationChange:(_Bool)arg1;
- (void)deviceOrientationDidChange;
- (void)deviceOrientationDidChange:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)applyCertByFaceCompleted:(id)arg1;
- (void)more;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (_Bool)canSave;
- (void)webkitTouchCalloutIsNone:(_Bool)arg1;
- (void)handleLongPress:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webViewgoBackChanged:(id)arg1 canback:(_Bool)arg2;
- (void)webViewTitledidChanged:(id)arg1 title:(id)arg2;
- (void)handleErrorWith:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)retryClick;
- (void)confignaveWithUrl:(id)arg1;
- (void)preLocationWithUrl:(id)arg1;
- (void)setupItemColor;
- (void)close;
- (void)settingAction;
- (void)back;
- (void)setupLeftButtonItem;
- (void)setupRightButtonItem;
- (id)getleftBarButtonItemWithTitle:(id)arg1;
- (void)handeleWorkOutLineApplication:(id)arg1;
- (void)loadWebViewWithRequest:(id)arg1;
- (void)handleComPleDataWithData:(id)arg1;
- (void)openModelOnline;
- (void)loadRealRequest;
- (id)getParmWithagentid:(id)arg1 corpid:(id)arg2;
- (void)setupWaterView;
- (void)setupWebView;
- (void)makeWebViewConstraints;
- (void)dealloc;
- (void)referWebView;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

