//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FWWpsConfig : NSObject
{
    _Bool _editModeIsRevision;
    NSString *_iAppOfficeCopyRight;
    NSString *_iAppOfficeWPSKey;
    NSString *_WPSOfficeKey;
    NSString *_iAppPDFKey;
    NSString *_YozoCdkey;
    NSString *_YozoVersion;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *YozoVersion; // @synthesize YozoVersion=_YozoVersion;
@property(retain, nonatomic) NSString *YozoCdkey; // @synthesize YozoCdkey=_YozoCdkey;
@property(retain, nonatomic) NSString *iAppPDFKey; // @synthesize iAppPDFKey=_iAppPDFKey;
@property(nonatomic) _Bool editModeIsRevision; // @synthesize editModeIsRevision=_editModeIsRevision;
@property(retain, nonatomic) NSString *WPSOfficeKey; // @synthesize WPSOfficeKey=_WPSOfficeKey;
@property(retain, nonatomic) NSString *iAppOfficeWPSKey; // @synthesize iAppOfficeWPSKey=_iAppOfficeWPSKey;
@property(retain, nonatomic) NSString *iAppOfficeCopyRight; // @synthesize iAppOfficeCopyRight=_iAppOfficeCopyRight;

@end

