//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface GMSStampStyle : NSObject
{
    UIImage *_stampImage;
    double _animationDuration;
}

+ (id)styleWithStampImage:(id)arg1;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(readonly, nonatomic) UIImage *stampImage; // @synthesize stampImage=_stampImage;
- (void).cxx_destruct;
- (id)initWithStampImage:(id)arg1;
- (id)init;

@end

