//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface JCommonPasteReportManager : NSObject
{
    NSArray *_pasteDatas;
    CDUnknownBlockType _reportCompletion;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType reportCompletion; // @synthesize reportCompletion=_reportCompletion;
@property(retain, nonatomic) NSArray *pasteDatas; // @synthesize pasteDatas=_pasteDatas;
- (id)pasteboardInfo;
- (void)report;

@end

