//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JCORETcpObject.h"

#import "JCORETcpProtocol-Protocol.h"

@class NSString;

@interface JPUSHNewRequest : JCORETcpObject <JCORETcpProtocol>
{
}

- (void)send;

// Remaining properties
@property(nonatomic) unsigned char algorithm;
@property(nonatomic) int autoRetryCount;
@property(copy, nonatomic) CDUnknownBlockType completionHandler;
@property(nonatomic) unsigned char controlFlag;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned char protocolType;
@property(nonatomic) unsigned short rid;
@property(nonatomic) unsigned long long seed;
@property(readonly) Class superclass;
@property(nonatomic) unsigned long long uid;
@property(nonatomic) unsigned char version;

@end

