//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JPUSHHelper : NSObject
{
}

+ (id)transformDateToStr:(id)arg1;
+ (id)transLocaleDate:(id)arg1;
+ (id)transformStrToDate:(id)arg1;
+ (id)getCurrentVCFrom:(id)arg1;
+ (id)getCurrentVCFrom;
+ (id)getCurrentWinow;
+ (id)dictionaryToString:(id)arg1;
+ (void)postNotification:(id)arg1 withUserInfo:(id)arg2;
+ (id)convertTokenDataToString:(id)arg1;
+ (_Bool)checkFormatOfMobileNumber:(id)arg1;
+ (id)JPUSHDisplayVersion;

@end

