//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KGAlertView.h"

@class NSLayoutConstraint, UIScrollView, UIView;

@interface KGAlertPopoverView : KGAlertView
{
    _Bool _fitSize;
    double _contentMinHeight;
    UIView *_contentView;
    NSLayoutConstraint *_textContentScrollViewConstraint;
    UIScrollView *_textContentScrollView;
    UIView *_textContentView;
    struct CGSize _maxSize;
    struct UIEdgeInsets _boundsEdgeInsets;
}

@property(retain, nonatomic) UIView *textContentView; // @synthesize textContentView=_textContentView;
@property(retain, nonatomic) UIScrollView *textContentScrollView; // @synthesize textContentScrollView=_textContentScrollView;
@property(retain, nonatomic) NSLayoutConstraint *textContentScrollViewConstraint; // @synthesize textContentScrollViewConstraint=_textContentScrollViewConstraint;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double contentMinHeight; // @synthesize contentMinHeight=_contentMinHeight;
@property(nonatomic) struct UIEdgeInsets boundsEdgeInsets; // @synthesize boundsEdgeInsets=_boundsEdgeInsets;
@property(nonatomic, getter=isFitSize) _Bool fitSize; // @synthesize fitSize=_fitSize;
@property(nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
- (void).cxx_destruct;
- (void)addSubviewOfTextContentScrollView;
- (void)initViews;
- (id)initWithContentView:(id)arg1;

@end

