//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KGBrushStampGenerator.h"

@class KGBrushProperty;

@interface KGBrushRectGenerator : KGBrushStampGenerator
{
}

- (void)configureBrush:(id)arg1;
- (void)renderStamp:(struct CGContext *)arg1 randomizer:(id)arg2;
@property(readonly, nonatomic) __weak KGBrushProperty *width;
- (void)buildProperties;
- (_Bool)canRandomize;

@end

