//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface KGBrushShader : NSObject
{
    unsigned int program_;
    NSDictionary *uniforms_;
}

+ (id)shaderWithVertexShader:(id)arg1 fragmentShader:(id)arg2 attributesNames:(id)arg3 uniformNames:(id)arg4;
@property(readonly, nonatomic) NSDictionary *uniforms; // @synthesize uniforms=uniforms_;
@property(readonly, nonatomic) unsigned int program; // @synthesize program=program_;
- (void).cxx_destruct;
- (unsigned int)locationForUniform:(id)arg1;
- (void)dealloc;
- (void)freeGLResources;
- (id)initWithVertexShader:(id)arg1 fragmentShader:(id)arg2 attributesNames:(id)arg3 uniformNames:(id)arg4;

@end

