//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KGBrushPropertyDelegate-Protocol.h"
#import "KGBrushStampGeneratorDelegate-Protocol.h"
#import "NSCopying-Protocol.h"

@class KGBrushProperty, KGBrushStampGenerator, NSMutableSet, NSString, UIImage;

@interface KGBrush : NSObject <KGBrushPropertyDelegate, KGBrushStampGeneratorDelegate, NSCopying>
{
    KGBrushStampGenerator *generator;
    UIImage *noise;
    KGBrushProperty *weight;
    KGBrushProperty *intensity;
    KGBrushProperty *angle;
    KGBrushProperty *spacing;
    KGBrushProperty *rotationalScatter;
    KGBrushProperty *positionalScatter;
    KGBrushProperty *angleDynamics;
    KGBrushProperty *weightDynamics;
    KGBrushProperty *intensityDynamics;
    UIImage *strokePreview;
    unsigned long long suppressNotifications;
    NSMutableSet *changedProperties;
    NSString *uuid_;
}

+ (id)brushWithGenerator:(id)arg1;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=uuid_;
@property(retain, nonatomic) NSMutableSet *changedProperties; // @synthesize changedProperties;
@property(nonatomic) unsigned long long suppressNotifications; // @synthesize suppressNotifications;
@property(retain, nonatomic) UIImage *strokePreview; // @synthesize strokePreview;
@property(retain, nonatomic) KGBrushProperty *intensityDynamics; // @synthesize intensityDynamics;
@property(retain, nonatomic) KGBrushProperty *weightDynamics; // @synthesize weightDynamics;
@property(retain, nonatomic) KGBrushProperty *angleDynamics; // @synthesize angleDynamics;
@property(retain, nonatomic) KGBrushProperty *positionalScatter; // @synthesize positionalScatter;
@property(retain, nonatomic) KGBrushProperty *rotationalScatter; // @synthesize rotationalScatter;
@property(retain, nonatomic) KGBrushProperty *spacing; // @synthesize spacing;
@property(retain, nonatomic) KGBrushProperty *angle; // @synthesize angle;
@property(retain, nonatomic) KGBrushProperty *intensity; // @synthesize intensity;
@property(retain, nonatomic) KGBrushProperty *weight; // @synthesize weight;
@property(retain, nonatomic) UIImage *noise; // @synthesize noise;
@property(retain, nonatomic) KGBrushStampGenerator *generator; // @synthesize generator;
- (void).cxx_destruct;
- (id)previewImageWithSize:(struct CGSize)arg1;
- (id)propertiesForGroupAtIndex:(unsigned long long)arg1;
- (id)allProperties;
- (unsigned long long)numberOfPropertyGroups;
@property(readonly, nonatomic) float radius;
- (void)generatorChanged:(id)arg1;
- (void)propertyChanged:(id)arg1;
- (id)initWithGenerator:(id)arg1;
- (void)buildProperties;
- (void)restoreDefaults;
- (void)suppressNotifications:(_Bool)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

