//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KGBrushPainting, KGBrushPaintingFragment, NSData, NSString;

@interface KGBrushLayer : NSObject
{
    _Bool visible_;
    _Bool locked_;
    _Bool alphaLocked_;
    float opacity_;
    NSData *loadedImageData_;
    KGBrushPaintingFragment *fragment_;
    unsigned int textureName_;
    int blendMode_;
    KGBrushPainting *painting_;
    NSString *uuid_;
    long long isSaved;
    struct CGAffineTransform transform;
}

+ (id)layer;
@property(nonatomic) struct CGAffineTransform transform; // @synthesize transform;
@property(nonatomic) long long isSaved; // @synthesize isSaved;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=uuid_;
@property(nonatomic) int blendMode; // @synthesize blendMode=blendMode_;
@property(nonatomic) float opacity; // @synthesize opacity=opacity_;
@property(nonatomic) _Bool alphaLocked; // @synthesize alphaLocked=alphaLocked_;
@property(nonatomic) _Bool locked; // @synthesize locked=locked_;
@property(nonatomic) _Bool visible; // @synthesize visible=visible_;
@property(nonatomic) __weak KGBrushPainting *painting; // @synthesize painting=painting_;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)freeze;
- (id)description;
@property(readonly, nonatomic) unsigned int textureName; // @synthesize textureName=textureName_;
- (void)applyShader:(id)arg1 undoBits:(_Bool)arg2;
- (void)clear;
- (void)commitStroke:(struct CGRect)arg1 color:(id)arg2 erase:(_Bool)arg3 undoable:(_Bool)arg4;
- (void)merge:(id)arg1;
- (void)modifyWithBlock:(CDUnknownBlockType)arg1 newTexture:(_Bool)arg2 undoBits:(_Bool)arg3 bounds:(struct CGRect)arg4;
- (void)modifyWithBlock:(CDUnknownBlockType)arg1 newTexture:(_Bool)arg2 undoBits:(_Bool)arg3;
- (void)blit:(float *)arg1 withEraseMask:(unsigned int)arg2;
- (void)blit:(float *)arg1 withMask:(unsigned int)arg2 color:(id)arg3;
- (void)blit:(float *)arg1 withTransform:(struct CGAffineTransform)arg2;
- (void)blit:(float *)arg1;
- (void)basicBlit:(float *)arg1;
- (void)configureBlendMode;
@property(readonly, nonatomic) _Bool editable;
@property(retain, nonatomic) NSData *imageData;
- (void)registerUndoInRect:(struct CGRect)arg1;
- (void)drawFragment:(id)arg1;
- (id)imageDataInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool isSuppressingNotifications;
- (void)dealloc;
- (void)freeGLResources;
- (id)initWithUUID:(id)arg1;
- (id)init;

@end

