//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter;
@protocol OS_dispatch_semaphore;

@interface KGPDFInfo : NSObject
{
    _Bool _debugMode;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    struct _sp_engine_token_s *_token;
    NSDateFormatter *_formatter;
}

+ (_Bool)RemoveTemporaryCacheDirectoryWithName:(id)arg1;
+ (id)GetTemporaryCacheDirectoryWithName:(id)arg1;
+ (void)showLogWithClassName:(id)arg1 message:(id)arg2;
+ (double)mainScale;
+ (void)synchronizedWithSemaphore:(unsigned long long)arg1 method:(CDUnknownBlockType)arg2;
+ (void)synchronized:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;
@property(nonatomic) struct _sp_engine_token_s *token; // @synthesize token=_token;
@property(nonatomic, getter=isDebugMode) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(retain) NSObject<OS_dispatch_semaphore> *semaphore; // @synthesize semaphore=_semaphore;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

