//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "KGPDFContentViewDelegate-Protocol.h"
#import "KGPDFModeView-Protocol.h"
#import "KGPDFModeViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIScrollView;
@protocol KGPDFModeViewDelegate;

@interface KGPDFModeSingleView : UIView <KGPDFContentViewDelegate, UIScrollViewDelegate, KGPDFModeView, KGPDFModeViewDelegate>
{
    id <KGPDFModeViewDelegate> _delegate;
    long long _currentPageIndex;
    struct KGPDFDocument *_document;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) struct KGPDFDocument *document; // @synthesize document=_document;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) __weak id <KGPDFModeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)contentView:(id)arg1 didMoveWithInfo:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)gotoPageFinished;
- (void)gotoPageWithIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)handleTapEvent:(id)arg1;
- (id)currentContentView;
- (void)addContentViewWithPageIndex:(unsigned long long)arg1;
- (void)addContentView;
- (void)loadViews;
- (struct CGPoint)touchPDFPointFromTouchPoint:(struct CGPoint)arg1 inversion:(_Bool)arg2 scaleSize:(struct CGSize *)arg3 distanceSize:(struct CGSize *)arg4;
- (void)removeFromSuperview;
- (unsigned long long)pageCount;
- (struct CGRect)pageBoundsWithIndex:(unsigned long long)arg1;
- (double)currentPageZoomScale;
- (struct CGPoint)currentPageImageOffset;
- (struct CGSize)currentPageImageSize;
- (struct CGRect)currentPageBounds;
- (void)insertBlankPageWithIndex:(unsigned long long)arg1;
- (void)movePageWithZoomScale:(double)arg1 offset:(struct CGPoint)arg2 loadTile:(_Bool)arg3;
- (void)updateView;
- (void)refreshPageViewWhenRotateDidChange;
- (void)reloadPageWithIndex:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 document:(struct KGPDFDocument *)arg2 pageIndex:(unsigned long long)arg3;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

