//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSLayoutConstraint, NSString, UIBarButtonItem, UINavigationBar, UINavigationItem, UIView;

@interface KGPopoverViewController : UIViewController
{
    _Bool _hideStatusBar;
    NSString *_leftItemTitle;
    NSString *_rightItemTitle;
    UIView *_contentView;
    CDUnknownBlockType _itemDidClickBlock;
    NSLayoutConstraint *_navigationHeightConstraint;
    UINavigationBar *_navigationBar;
    UINavigationItem *_navigationItem;
    UIBarButtonItem *_leftItem;
    UIBarButtonItem *_rightItem;
}

@property(retain, nonatomic) UIBarButtonItem *rightItem; // @synthesize rightItem=_rightItem;
@property(retain, nonatomic) UIBarButtonItem *leftItem; // @synthesize leftItem=_leftItem;
@property(retain, nonatomic) UINavigationItem *navigationItem; // @synthesize navigationItem=_navigationItem;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(retain, nonatomic) NSLayoutConstraint *navigationHeightConstraint; // @synthesize navigationHeightConstraint=_navigationHeightConstraint;
@property(copy, nonatomic) CDUnknownBlockType itemDidClickBlock; // @synthesize itemDidClickBlock=_itemDidClickBlock;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) NSString *rightItemTitle; // @synthesize rightItemTitle=_rightItemTitle;
@property(copy, nonatomic) NSString *leftItemTitle; // @synthesize leftItemTitle=_leftItemTitle;
@property(nonatomic, getter=isHideStatusBar) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
- (void).cxx_destruct;
- (void)handleItemEvent:(id)arg1;
- (double)navigationHeight;
- (void)initViews;
- (void)itemDidClickWithIndex:(CDUnknownBlockType)arg1;
- (id)initWithContentView:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

