//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, RCMessage, UIImage, UIView;

@interface KSPhotoItem : NSObject
{
    _Bool _finished;
    UIView *_sourceView;
    UIImage *_thumbImage;
    UIImage *_image;
    NSURL *_imageUrl;
}

+ (id)itemWithSourceView:(id)arg1 image:(id)arg2;
+ (id)itemWithSourceView:(id)arg1 imageUrl:(id)arg2;
+ (id)itemWithSourceView:(id)arg1 thumbImage:(id)arg2 imageUrl:(id)arg3;
- (void).cxx_destruct;
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(retain, nonatomic) NSURL *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(retain, nonatomic) UIView *sourceView; // @synthesize sourceView=_sourceView;
- (id)initWithSourceView:(id)arg1 image:(id)arg2;
- (id)initWithSourceView:(id)arg1 imageUrl:(id)arg2;
- (id)initWithSourceView:(id)arg1 thumbImage:(id)arg2 imageUrl:(id)arg3;
@property(retain, nonatomic) RCMessage *mesage;

@end

