//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KWApiAsyncSocket, NSData, NSDictionary, NSString;
@protocol KWOfficeApiDelegate;

@interface KWOfficeApi : NSObject
{
    KWApiAsyncSocket *_acceptSocket;
    KWApiAsyncSocket *_connectSocket;
    long long _port;
    id <KWOfficeApiDelegate> _delegate;
    NSDictionary *_rightDict;
    NSDictionary *_securityInfoDict;
    NSString *_filePath;
    NSString *_token;
    NSData *_fileData;
    NSString *_fileName;
    NSString *_sharePlayStatus;
    NSString *_serverHost;
    NSString *_accessCode;
}

+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
+ (void)setConfigAttribute;
+ (void)setConfigAttributeDic:(id)arg1;
+ (void)setBackgroundMode:(_Bool)arg1;
+ (void)goDownloadWPS;
+ (_Bool)isAppstoreWPSInstalled;
+ (_Bool)isEnterpriseWPSInstalled;
+ (void)changeToInternalTest;
+ (void)setWatermarkText:(id)arg1 colorWithRed:(double)arg2 green:(double)arg3 blue:(double)arg4 alpha:(double)arg5 type:(unsigned long long)arg6;
+ (void)setWatermarkText:(id)arg1 colorWithRed:(double)arg2 green:(double)arg3 blue:(double)arg4 alpha:(double)arg5;
+ (void)setDebugMode:(_Bool)arg1;
+ (void)setPort:(long long)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (void)registerApp:(id)arg1;
@property(retain, nonatomic) NSString *accessCode; // @synthesize accessCode=_accessCode;
@property(retain, nonatomic) NSString *serverHost; // @synthesize serverHost=_serverHost;
@property(retain, nonatomic) NSString *sharePlayStatus; // @synthesize sharePlayStatus=_sharePlayStatus;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSData *fileData; // @synthesize fileData=_fileData;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSDictionary *securityInfoDict; // @synthesize securityInfoDict=_securityInfoDict;
@property(retain, nonatomic) NSDictionary *rightDict; // @synthesize rightDict=_rightDict;
@property(nonatomic) __weak id <KWOfficeApiDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)resetKWOfficeApiServiceWithDelegate:(id)arg1;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socket:(id)arg1 didAcceptNewSocket:(id)arg2;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (_Bool)runUrlWpsAppWithURLSchemes:(id)arg1;
- (_Bool)setApplicationDidEnterBackground:(id)arg1;
- (void)setPort:(long long)arg1;
- (_Bool)closeKWOfficeApiService;
- (void)showLogText:(id)arg1;
- (_Bool)setServerHost:(id)arg1 accessCode:(id)arg2 error:(id *)arg3;
- (void)resetURLParameters;
- (_Bool)startWPSOfficeAPP:(id)arg1 delegate:(id)arg2 enterpriseOnly:(_Bool)arg3 error:(id *)arg4;
- (_Bool)startAPIService:(id *)arg1;
- (_Bool)sendFileData:(id)arg1 withFileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 error:(id *)arg6 enterpriseOnly:(_Bool)arg7;
- (_Bool)joinSharePlay:(id)arg1 serverHost:(id)arg2 callback:(id)arg3 delegate:(id)arg4 error:(id *)arg5;
- (_Bool)startSharePlay:(id)arg1 withFileName:(id)arg2 serverHost:(id)arg3 callback:(id)arg4 delegate:(id)arg5 error:(id *)arg6;
- (_Bool)startSharePlay:(id)arg1 securityInfo:(id)arg2 withFileName:(id)arg3 serverHost:(id)arg4 callback:(id)arg5 delegate:(id)arg6 error:(id *)arg7;
- (_Bool)sendFileData:(id)arg1 withFileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 error:(id *)arg6;
- (_Bool)sendFileData:(id)arg1 withFileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 securityInfo:(id)arg6 error:(id *)arg7;
- (_Bool)checkFileData:(id)arg1 fileName:(id)arg2 error:(id *)arg3;
- (void)setIsBackstage:(id)arg1;
- (_Bool)isBackgroundMode;
- (_Bool)initKWOfficeApiService;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

