//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LFGridView;

@protocol LFGridViewDelegate <NSObject>
- (void)lf_gridViewDidAspectRatio:(LFGridView *)arg1;
- (void)lf_gridViewDidEndResizing:(LFGridView *)arg1;
- (void)lf_gridViewDidResizing:(LFGridView *)arg1;
- (void)lf_gridViewDidBeginResizing:(LFGridView *)arg1;
@end

