//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CALayerDelegate-Protocol.h"

@class NSMutableArray, NSOperationQueue, NSString;

@interface LFLViewContext : NSObject <CALayerDelegate>
{
    int _rows;
    int _columns;
    NSMutableArray *_images;
    NSOperationQueue *_queue;
    struct CGSize _tileSize;
    struct CGRect _imageBounds;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(nonatomic) struct CGRect imageBounds; // @synthesize imageBounds=_imageBounds;
@property(nonatomic) struct CGSize tileSize; // @synthesize tileSize=_tileSize;
@property(nonatomic) int columns; // @synthesize columns=_columns;
@property(nonatomic) int rows; // @synthesize rows=_rows;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)configurationcontextWithImage:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

