//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFBaseEditingController.h"

#import "JRFilterBarDataSource-Protocol.h"
#import "JRFilterBarDelegate-Protocol.h"
#import "LFClipToolbarDelegate-Protocol.h"
#import "LFEditToolbarDataSource-Protocol.h"
#import "LFEditToolbarDelegate-Protocol.h"
#import "LFEditingViewDelegate-Protocol.h"
#import "LFPhotoEditDelegate-Protocol.h"
#import "LFStickerBarDelegate-Protocol.h"
#import "LFTextBarDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class JRFilterBar, LFClipToolbar, LFEditToolbar, LFEditingView, LFSafeAreaMaskView, LFStickerBar, NSArray, NSDictionary, NSString, UIImage, UITapGestureRecognizer, UIView;
@protocol LFPhotoEditingControllerDelegate;

@interface LFPhotoEditingController : LFBaseEditingController <LFEditToolbarDelegate, LFStickerBarDelegate, JRFilterBarDelegate, JRFilterBarDataSource, LFClipToolbarDelegate, LFEditToolbarDataSource, LFTextBarDelegate, LFPhotoEditDelegate, LFEditingViewDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate>
{
    LFEditingView *_EditingView;
    UIView *_edit_naviBar;
    LFEditToolbar *_edit_toolBar;
    LFClipToolbar *_edit_clipping_toolBar;
    LFSafeAreaMaskView *_edit_clipping_safeAreaMaskView;
    LFStickerBar *_edit_sticker_toolBar;
    JRFilterBar *_edit_filter_toolBar;
    UITapGestureRecognizer *singleTapRecognizer;
    _Bool _isHideNaviBar;
    UIImage *_editImage;
    unsigned long long _operationType;
    unsigned long long _defaultOperationType;
    NSDictionary *_operationAttrs;
    id <LFPhotoEditingControllerDelegate> _delegate;
    NSString *_stickerPath;
    unsigned long long _initSelectedOperationType;
    CDUnknownBlockType _delayCancelBlock;
    UIImage *_filterSmallImage;
    NSArray *_durations;
    NSDictionary *_editData;
    id _stickerBarCacheResource;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id stickerBarCacheResource; // @synthesize stickerBarCacheResource=_stickerBarCacheResource;
@property(retain, nonatomic) NSDictionary *editData; // @synthesize editData=_editData;
@property(retain, nonatomic) NSArray *durations; // @synthesize durations=_durations;
@property(retain, nonatomic) UIImage *filterSmallImage; // @synthesize filterSmallImage=_filterSmallImage;
@property(copy, nonatomic) CDUnknownBlockType delayCancelBlock; // @synthesize delayCancelBlock=_delayCancelBlock;
@property(nonatomic) unsigned long long initSelectedOperationType; // @synthesize initSelectedOperationType=_initSelectedOperationType;
@property(nonatomic) _Bool isHideNaviBar; // @synthesize isHideNaviBar=_isHideNaviBar;
@property(retain, nonatomic) NSString *stickerPath; // @synthesize stickerPath=_stickerPath;
@property(nonatomic) __weak id <LFPhotoEditingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *operationAttrs; // @synthesize operationAttrs=_operationAttrs;
@property(nonatomic) unsigned long long defaultOperationType; // @synthesize defaultOperationType=_defaultOperationType;
@property(nonatomic) unsigned long long operationType; // @synthesize operationType=_operationType;
@property(retain, nonatomic) UIImage *editImage; // @synthesize editImage=_editImage;
- (_Bool)operationBOOLForKey:(id)arg1;
- (id)operationArrayForKey:(id)arg1;
- (unsigned long long)operationSubTypeForKey:(id)arg1;
- (void)showTextBarController:(id)arg1;
- (void)changeFilterMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeStickerMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeClipMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeClipMenu:(_Bool)arg1;
- (void)changedBarStateWithAnimated:(_Bool)arg1;
- (void)changedBarState;
- (void)lf_EditingViewDidAppearClip:(id)arg1;
- (void)lf_EditingViewDidEndEditing:(id)arg1;
- (void)lf_EditingViewWillBeginEditing:(id)arg1;
- (void)lf_photoEditSplashEnded;
- (void)lf_photoEditSplashBegan;
- (void)lf_photoEditStickerDidSelectViewIsActive:(_Bool)arg1;
- (void)lf_photoEditDrawEnded;
- (void)lf_photoEditDrawBegan;
- (void)lf_textBarControllerDidReachMaximumLimit:(id)arg1;
- (void)lf_textBarControllerDidCancel:(id)arg1;
- (void)lf_textBarController:(id)arg1 didFinishText:(id)arg2;
- (void)lf_stickerBar:(id)arg1 didSelectImage:(id)arg2;
- (id)edit_sticker_toolBar;
- (id)jr_filterBarNameForEffectType:(long long)arg1;
- (id)jr_async_filterBarImageForEffectType:(long long)arg1;
- (void)jr_filterBar:(id)arg1 didSelectImage:(id)arg2 effectType:(long long)arg3;
- (id)edit_filter_toolBar;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)lf_clipToolbarDidAspectRatio:(id)arg1;
- (void)lf_clipToolbarDidRotate:(id)arg1;
- (void)lf_clipToolbarDidReset:(id)arg1;
- (void)lf_clipToolbarDidFinish:(id)arg1;
- (void)lf_clipToolbarDidCancel:(id)arg1;
- (_Bool)lf_clipToolbarCanAspectRatio:(id)arg1;
- (_Bool)lf_clipToolbarCanRotate:(id)arg1;
- (id)edit_clipping_toolBar;
- (void)lf_editToolbar:(id)arg1 drawBrushDidChange:(id)arg2;
- (void)lf_editToolbar:(id)arg1 drawColorDidChange:(id)arg2;
- (_Bool)lf_editToolbar:(id)arg1 canRevokeAtIndex:(unsigned long long)arg2;
- (void)lf_editToolbar:(id)arg1 subDidSelectAtIndex:(id)arg2;
- (void)lf_editToolbar:(id)arg1 subDidRevokeAtIndex:(unsigned long long)arg2;
- (void)lf_editToolbar:(id)arg1 mainDidSelectAtIndex:(unsigned long long)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)finishButtonClick;
- (void)cancelButtonClick;
- (void)singlePressedWithAnimated:(_Bool)arg1;
- (void)singlePressed;
- (void)configUserGuide;
- (void)configDefaultOperation;
- (void)configBottomToolBar;
- (void)configCustomNaviBar;
- (void)configScrollView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setPhotoEdit:(id)arg1;
- (void)setEditImage:(id)arg1 durations:(id)arg2;
- (id)initWithOrientation:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

