//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFBrush.h"

@class CALayer, NSMutableArray, NSString;

@interface LFSmearBrush : LFBrush
{
    NSString *_name;
    CALayer *_layer;
    NSMutableArray *_points;
}

+ (id)createSubLayerWithImage:(id)arg1 lineWidth:(double)arg2 point:(struct CGPoint)arg3 angle:(double)arg4 color:(id)arg5;
+ (id)createLayer;
+ (id)cacheImageWithName:(id)arg1 bundle:(id)arg2;
+ (id)drawLayerWithTrackDict:(id)arg1;
+ (_Bool)smearBrushCache;
+ (void)loadBrushImage:(id)arg1 canvasSize:(struct CGSize)arg2 useCache:(_Bool)arg3 complete:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
@property(nonatomic) __weak CALayer *layer; // @synthesize layer=_layer;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)allTracks;
- (id)createDrawLayerWithPoint:(struct CGPoint)arg1;
- (void)addPoint:(struct CGPoint)arg1;
- (id)initWithImageName:(id)arg1;
- (id)init;
- (id)colorOfPoint:(struct CGPoint)arg1;

@end

