//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class LFMovingView, NSDictionary;

@interface LFStickerView : UIView
{
    _Bool _hitTestSubView;
    double _minScale;
    double _maxScale;
    double _screenScale;
    CDUnknownBlockType _tapEnded;
    CDUnknownBlockType _moveCenter;
    LFMovingView *_selectMovingView;
}

+ (void)LFStickerViewDeactivated;
- (void).cxx_destruct;
@property(nonatomic, getter=isHitTestSubView) _Bool hitTestSubView; // @synthesize hitTestSubView=_hitTestSubView;
@property(nonatomic) __weak LFMovingView *selectMovingView; // @synthesize selectMovingView=_selectMovingView;
@property(copy, nonatomic) CDUnknownBlockType moveCenter; // @synthesize moveCenter=_moveCenter;
@property(copy, nonatomic) CDUnknownBlockType tapEnded; // @synthesize tapEnded=_tapEnded;
@property(nonatomic) double screenScale; // @synthesize screenScale=_screenScale;
@property(nonatomic) double maxScale; // @synthesize maxScale=_maxScale;
@property(nonatomic) double minScale; // @synthesize minScale=_minScale;
@property(retain, nonatomic) NSDictionary *data;
@property(readonly, nonatomic) unsigned long long count;
- (void)createStickerItem:(id)arg1;
- (id)createBaseMovingView:(id)arg1 active:(_Bool)arg2;
- (void)changeSelectStickerItem:(id)arg1;
- (id)getSelectStickerItem;
- (void)removeSelectStickerView;
- (void)activeSelectStickerView;
@property(readonly, nonatomic, getter=isEnable) _Bool enable;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

