//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "lf_resizeConrolDelegate-Protocol.h"

@class LFGridMaskLayer, LFResizeControl, LFResizeImageControl, LFVideoTrimmerGridLayer, NSString;
@protocol LFVideoTrimmerGridViewDelegate;

@interface LFVideoTrimmerGridView : UIView <lf_resizeConrolDelegate>
{
    double _controlMinWidth;
    double _controlMaxWidth;
    double _progress;
    id <LFVideoTrimmerGridViewDelegate> _delegate;
    LFResizeImageControl *_leftCornerView;
    LFResizeImageControl *_rightCornerView;
    LFResizeControl *_centerCornerView;
    LFVideoTrimmerGridLayer *_gridLayer;
    LFVideoTrimmerGridLayer *_bg_gridLayer;
    LFGridMaskLayer *_gridMaskLayer;
    UIView *_slider;
    struct CGRect _gridRect;
    struct CGRect _initialRect;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect initialRect; // @synthesize initialRect=_initialRect;
@property(nonatomic) __weak UIView *slider; // @synthesize slider=_slider;
@property(nonatomic) __weak LFGridMaskLayer *gridMaskLayer; // @synthesize gridMaskLayer=_gridMaskLayer;
@property(nonatomic) __weak LFVideoTrimmerGridLayer *bg_gridLayer; // @synthesize bg_gridLayer=_bg_gridLayer;
@property(nonatomic) __weak LFVideoTrimmerGridLayer *gridLayer; // @synthesize gridLayer=_gridLayer;
@property(nonatomic) __weak LFResizeControl *centerCornerView; // @synthesize centerCornerView=_centerCornerView;
@property(nonatomic) __weak LFResizeImageControl *rightCornerView; // @synthesize rightCornerView=_rightCornerView;
@property(nonatomic) __weak LFResizeImageControl *leftCornerView; // @synthesize leftCornerView=_leftCornerView;
@property(nonatomic) __weak id <LFVideoTrimmerGridViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) double controlMaxWidth; // @synthesize controlMaxWidth=_controlMaxWidth;
@property(nonatomic) double controlMinWidth; // @synthesize controlMinWidth=_controlMinWidth;
@property(nonatomic) struct CGRect gridRect; // @synthesize gridRect=_gridRect;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGRect)cropRectMakeWithResizeControlView:(id)arg1;
- (id)createCenterResizeControl;
- (id)createResizeControl;
- (void)setGridRect:(struct CGRect)arg1 animated:(_Bool)arg2;
- (void)lf_resizeConrolDidEndResizing:(id)arg1;
- (void)lf_resizeConrolDidResizing:(id)arg1;
- (void)lf_resizeConrolDidBeginResizing:(id)arg1;
- (void)setHiddenProgress:(_Bool)arg1;
@property(nonatomic, getter=isEnabledRightCorner) _Bool enabledRightCorner;
@property(nonatomic, getter=isEnabledLeftCorner) _Bool enabledLeftCorner;
- (void)layoutSubviews;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

