//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAsset, AVMutableAudioMix, AVMutableComposition, AVPlayer, AVPlayerItem, NSArray, NSString, NSURL;
@protocol LFVideoPlayerDelegate;

@interface LFVideoPlayer : NSObject
{
    NSURL *mURL;
    float mRestoreAfterScrubbingRate;
    _Bool seekToZeroBeforePlay;
    id mTimeObserver;
    _Bool isSeeking;
    _Bool _muteOriginalSound;
    float _rate;
    id <LFVideoPlayerDelegate> _delegate;
    NSArray *_audioUrls;
    double _totalDuration;
    double _duration;
    AVPlayerItem *_mPlayerItem;
    AVPlayer *_player;
    NSString *_audioTimePitchAlgorithm;
    AVMutableComposition *_composition;
    AVMutableAudioMix *_audioMix;
    struct CGSize _size;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVMutableAudioMix *audioMix; // @synthesize audioMix=_audioMix;
@property(copy, nonatomic) AVMutableComposition *composition; // @synthesize composition=_composition;
@property(copy, nonatomic) NSString *audioTimePitchAlgorithm; // @synthesize audioTimePitchAlgorithm=_audioTimePitchAlgorithm;
@property(retain) AVPlayer *player; // @synthesize player=_player;
@property(retain) AVPlayerItem *mPlayerItem; // @synthesize mPlayerItem=_mPlayerItem;
@property(nonatomic) float rate; // @synthesize rate=_rate;
@property(nonatomic) _Bool muteOriginalSound; // @synthesize muteOriginalSound=_muteOriginalSound;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSArray *audioUrls; // @synthesize audioUrls=_audioUrls;
@property(nonatomic) __weak id <LFVideoPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)prepareToPlayAsset:(id)arg1 withKeys:(id)arg2;
- (void)assetFailedToPrepareForPlayback:(id)arg1;
- (void)removePlayerTimeObserver;
- (CDStruct_1b6d18a9)playerItemDuration;
- (void)playerItemDidReachEnd:(id)arg1;
- (_Bool)isPlaying;
- (_Bool)isScrubbing;
- (void)endScrubbing;
- (void)scrub:(id)arg1;
- (void)beginScrubbing;
- (void)syncScrubber;
- (void)initScrubberTimer;
- (void)seekToTime:(double)arg1;
- (void)resetDisplay;
- (void)mute:(_Bool)arg1;
- (void)pause;
- (void)play;
- (id)createAVMutableComposition:(id)arg1;
@property(copy, nonatomic) AVAsset *asset;
@property(copy, nonatomic) NSURL *URL;
- (void)dealloc;
- (id)init;

@end

