//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVPlayer, LFVideoPlayer, NSError, UISlider;

@protocol LFVideoPlayerDelegate <NSObject>
- (void)LFVideoPlayerReadyToPlay:(LFVideoPlayer *)arg1 duration:(double)arg2;
- (void)LFVideoPlayerLayerDisplay:(LFVideoPlayer *)arg1 avplayer:(AVPlayer *)arg2;

@optional
- (void)LFVideoPlayerFailedToPrepare:(LFVideoPlayer *)arg1 error:(NSError *)arg2;
- (double)LFVideoPlayerSyncScrubProgressWidth:(LFVideoPlayer *)arg1;
- (void)LFVideoPlayerSyncScrub:(LFVideoPlayer *)arg1 duration:(double)arg2;
- (UISlider *)LFVideoPlayerSyncScrub:(LFVideoPlayer *)arg1;
- (void)LFVideoPlayerPlayDidReachEnd:(LFVideoPlayer *)arg1;
@end

