//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "LFEditingProtocol-Protocol.h"

@class LFDataFilterImageView, LFDrawView, LFStickerView, NSDictionary, NSString, UIImage;
@protocol LFPhotoEditDelegate;

@interface LFZoomingView : UIView <LFEditingProtocol>
{
    UIImage *_image;
    CDUnknownBlockType _moveCenter;
    LFDataFilterImageView *_imageView;
    LFDrawView *_drawView;
    LFStickerView *_stickerView;
    LFDrawView *_splashView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak LFDrawView *splashView; // @synthesize splashView=_splashView;
@property(nonatomic) __weak LFStickerView *stickerView; // @synthesize stickerView=_stickerView;
@property(nonatomic) __weak LFDrawView *drawView; // @synthesize drawView=_drawView;
@property(nonatomic) __weak LFDataFilterImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType moveCenter; // @synthesize moveCenter=_moveCenter;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSDictionary *photoEditData;
- (id)editOtherImagesInRect:(struct CGRect)arg1 rotate:(double)arg2;
- (void)setImage:(id)arg1 durations:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool drawCanUndo;
@property(nonatomic) _Bool drawEnable;
@property(nonatomic) __weak id <LFPhotoEditDelegate> editDelegate;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isDrawing;
@property(readonly, nonatomic) _Bool isSplashing;
@property(nonatomic) double screenScale;
@property(readonly, nonatomic) _Bool splashCanUndo;
@property(nonatomic) _Bool splashEnable;
@property(nonatomic) unsigned long long splashStateType;
@property(readonly, nonatomic) _Bool stickerEnable;
@property(nonatomic) double stickerMaxScale;
@property(nonatomic) double stickerMinScale;
@property(readonly) Class superclass;

@end

