//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GLKit/GLKViewController.h>

#import "DYPaletteToolViewDelegate-Protocol.h"
#import "NewDYLiteViewDelegate-Protocol.h"

@class DYDrawView, DYPaletteToolView, NSMutableArray, NSMutableDictionary, NSString, NSTimer, NewDYLiteView, UIButton, UIColor, UIImage;
@protocol NewDYPaletteViewDelegate;

@interface NewDYPaletteViewController : GLKViewController <NewDYLiteViewDelegate, DYPaletteToolViewDelegate>
{
    double ios7Height;
    DYPaletteToolView *topView;
    DYPaletteToolView *bottomView;
    DYPaletteToolView *colorView;
    DYPaletteToolView *widthView;
    long long lastEditState;
    long long lastEditColor;
    NewDYLiteView *paletteView;
    NewDYLiteView *paletteView2;
    NewDYLiteView *paletteView3;
    _Bool isRubber;
    DYDrawView *liteBgView;
    NewDYLiteView *liteView;
    NSTimer *liteTimer;
    _Bool isShowSetView;
    _Bool isShowColorView;
    _Bool isShowWidthView;
    long long liteColor;
    long long liteWidth;
    NSString *uploadKey;
    _Bool isClearPalette;
    UIImage *handImage;
    long long maxRow;
    UIButton *_leftButton;
    UIButton *_rightButton;
    long long _currentpage;
    NSMutableDictionary *_locationDic;
    long long _whiteLitePage;
    struct CGRect _paleteFrame;
    _Bool _isShowPaletteView;
    id <NewDYPaletteViewDelegate> _dyp_delegate;
    NSMutableDictionary *_setDic;
    NSMutableArray *_wordImgArray;
    NSMutableArray *_wordImgArray2;
    NSMutableArray *_wordImgArray3;
    NSMutableDictionary *_paletteDic;
    double _scale;
    UIColor *_topColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *topColor; // @synthesize topColor=_topColor;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(retain, nonatomic) NSMutableDictionary *paletteDic; // @synthesize paletteDic=_paletteDic;
@property(retain, nonatomic) NSMutableArray *wordImgArray3; // @synthesize wordImgArray3=_wordImgArray3;
@property(retain, nonatomic) NSMutableArray *wordImgArray2; // @synthesize wordImgArray2=_wordImgArray2;
@property(retain, nonatomic) NSMutableArray *wordImgArray; // @synthesize wordImgArray=_wordImgArray;
@property(retain, nonatomic) NSMutableDictionary *setDic; // @synthesize setDic=_setDic;
@property(nonatomic) _Bool isShowPaletteView; // @synthesize isShowPaletteView=_isShowPaletteView;
@property(nonatomic) id <NewDYPaletteViewDelegate> dyp_delegate; // @synthesize dyp_delegate=_dyp_delegate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (id)getSubImage:(struct CGRect)arg1 image:(id)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)processData;
- (void)clearData;
- (void)widthBtnClick:(id)arg1;
- (void)colorBtnClick:(id)arg1;
- (void)clearLiteView;
- (void)buttonClick:(id)arg1;
- (void)hideSetView;
- (void)getPath:(id)arg1;
- (void)turnToLite;
- (void)turnToPalette;
- (void)showColorOrSizeView;
- (void)chagePage:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

