//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (KGCategoryAdditions)
+ (id)chineseAmountWithMoney:(id)arg1;
- (id)drawWithTextAttributes:(id)arg1 inRect:(struct CGRect)arg2;
- (struct CGSize)sizeForFont:(id)arg1;
- (struct CGSize)sizeForFont:(id)arg1 minFontSize:(double)arg2 actualFontSize:(double *)arg3 forWidth:(double)arg4 lineBreakMode:(long long)arg5;
@end

