//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSReaderViewController.h"

@class NSString, UIButton, UIView;
@protocol WellSignDelegate;

@interface PDFeditViewController : WSReaderViewController
{
    _Bool _saved;
    _Bool _canEdit;
    _Bool _closeEdit;
    UIView *_pdfView;
    UIView *_historyView;
    UIView *_disPlayView;
    UIView *_toolView;
    UIView *_maskView;
    id <WellSignDelegate> _delegate;
    UIButton *_colorBtn;
    UIButton *_eraseBtn;
    NSString *_name;
    NSString *_useid;
    UIView *_naviView;
    UIView *_bottomView;
    UIButton *_selectedBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *naviView; // @synthesize naviView=_naviView;
@property(retain, nonatomic) NSString *useid; // @synthesize useid=_useid;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool closeEdit; // @synthesize closeEdit=_closeEdit;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(nonatomic) _Bool saved; // @synthesize saved=_saved;
@property(retain, nonatomic) UIButton *eraseBtn; // @synthesize eraseBtn=_eraseBtn;
@property(retain, nonatomic) UIButton *colorBtn; // @synthesize colorBtn=_colorBtn;
@property(nonatomic) __weak id <WellSignDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIView *toolView; // @synthesize toolView=_toolView;
@property(retain, nonatomic) UIView *disPlayView; // @synthesize disPlayView=_disPlayView;
@property(retain, nonatomic) UIView *historyView; // @synthesize historyView=_historyView;
@property(retain, nonatomic) UIView *pdfView; // @synthesize pdfView=_pdfView;
- (void)dealloc;
- (void)resetPDFState;
- (void)btnclick:(id)arg1;
- (void)setupUI;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

