//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, UICollectionView, UICollectionViewFlowLayout, UILabel, UISwipeGestureRecognizer;
@protocol PdfDisplayHistoryDelegate;

@interface PdfHistoryDisplayView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _isCustom;
    NSArray *_modelArray;
    UICollectionView *_collectionView;
    id <PdfDisplayHistoryDelegate> _historyDisplayDelegate;
    UICollectionViewFlowLayout *_layout;
    unsigned long long _direction;
    UISwipeGestureRecognizer *_swipe;
    UILabel *_emptyLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *emptyLabel; // @synthesize emptyLabel=_emptyLabel;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipe; // @synthesize swipe=_swipe;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(retain, nonatomic) UICollectionViewFlowLayout *layout; // @synthesize layout=_layout;
@property(nonatomic) _Bool isCustom; // @synthesize isCustom=_isCustom;
@property(nonatomic) __weak id <PdfDisplayHistoryDelegate> historyDisplayDelegate; // @synthesize historyDisplayDelegate=_historyDisplayDelegate;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *modelArray; // @synthesize modelArray=_modelArray;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)swipeHandle;
- (void)initUI;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

