//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSString, QYSBluetoothSealDataSource, UICollectionView;

@interface QYSBluetoothSealPhotoListView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    UICollectionView *_collectionView;
    QYSBluetoothSealDataSource *_dataSource;
    CDUnknownBlockType _reuploadImageModel;
    CDUnknownBlockType _previewImageModel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType previewImageModel; // @synthesize previewImageModel=_previewImageModel;
@property(copy, nonatomic) CDUnknownBlockType reuploadImageModel; // @synthesize reuploadImageModel=_reuploadImageModel;
@property(nonatomic) __weak QYSBluetoothSealDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)initSubviews;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

