//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QYSBluetoothSealFileManager : NSObject
{
}

+ (id)photoPathsInLibraryWithUserId:(id)arg1;
+ (id)markPhotoAsRetriedWithPath:(id)arg1;
+ (_Bool)removePhotoWithPath:(id)arg1;
+ (id)savePhoto:(id)arg1 authId:(id)arg2 userId:(id)arg3;
+ (id)folderPathInLibraryWithUserId:(id)arg1;
+ (id)sdkFolderInLibrary;
+ (id)userFolderInLibraryWithUserId:(id)arg1;
+ (id)rootFolderInLibrary;

@end

