//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWContactSelectViewController.h"

#import "UISearchBarDelegate-Protocol.h"

@class NSMutableArray, NSObject, NSString, UISearchBar;
@protocol OS_dispatch_queue;

@interface RCAtSomeBodyViewController : FWContactSelectViewController <UISearchBarDelegate>
{
    NSObject<OS_dispatch_queue> *_serialQueue;
    _Bool _canAtAll;
    CDUnknownBlockType _callBackPerson;
    NSMutableArray *_originDataSource;
    NSMutableArray *_selArry;
    UISearchBar *_mySearchBar;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UISearchBar *mySearchBar; // @synthesize mySearchBar=_mySearchBar;
@property(retain, nonatomic) NSMutableArray *selArry; // @synthesize selArry=_selArry;
@property(retain, nonatomic) NSMutableArray *originDataSource; // @synthesize originDataSource=_originDataSource;
@property(nonatomic) _Bool canAtAll; // @synthesize canAtAll=_canAtAll;
@property(copy, nonatomic) CDUnknownBlockType callBackPerson; // @synthesize callBackPerson=_callBackPerson;
- (void)processingData:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)endSlect;
- (void)backAction:(id)arg1;
- (void)atAllPerson;
- (void)doneSelPerson;
- (void)viewDidLayoutSubviews;
- (void)setupTableView;
- (void)setupNavgation;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

