//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FWIMKit/YYLabel.h>

@interface RFittableFontLabel : YYLabel
{
    _Bool _isUpdatingFromIB;
    _Bool _autoAdjustFontSize;
    double _maxFontSize;
    double _minFontSize;
}

@property(nonatomic) double minFontSize; // @synthesize minFontSize=_minFontSize;
@property(nonatomic) double maxFontSize; // @synthesize maxFontSize=_maxFontSize;
@property(nonatomic) _Bool autoAdjustFontSize; // @synthesize autoAdjustFontSize=_autoAdjustFontSize;
@property(nonatomic) _Bool isUpdatingFromIB; // @synthesize isUpdatingFromIB=_isUpdatingFromIB;
- (id)currentAttributedStringAttributes;
- (unsigned long long)multiLineSizeState:(struct CGRect)arg1 size:(struct CGSize)arg2;
- (unsigned long long)singleLineSizeState:(struct CGRect)arg1 size:(struct CGSize)arg2;
- (double)binarySearch:(id)arg1 minSize:(double)arg2 maxSize:(double)arg3 size:(struct CGSize)arg4 constraintSize:(struct CGSize)arg5;
- (double)fontSizeThatFits:(id)arg1 maxFontSize:(double)arg2 minFontScale:(double)arg3 rectSize:(struct CGSize)arg4;
- (void)fontSizeToFit:(double)arg1 minFontScale:(double)arg2 rectSize:(struct CGSize)arg3;
- (void)adjustFontSize;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;
- (void)setFrame:(struct CGRect)arg1;
- (void)setText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

