//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UITapGestureRecognizer;
@protocol RFollowTouchViewProtocol;

@interface RFollowTouchView : UIView
{
    long long _position;
    UIView *_touchView;
    id <RFollowTouchViewProtocol> _eventDelegate;
    UIImageView *_imageV;
    UITapGestureRecognizer *_activateTapGesture;
    struct CGSize _imageCenterToPosition;
}

+ (id)viewWithDelegate:(id)arg1 touchView:(id)arg2 position:(long long)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *activateTapGesture; // @synthesize activateTapGesture=_activateTapGesture;
@property(nonatomic) struct CGSize imageCenterToPosition; // @synthesize imageCenterToPosition=_imageCenterToPosition;
@property(retain, nonatomic) UIImageView *imageV; // @synthesize imageV=_imageV;
@property(nonatomic) __weak id <RFollowTouchViewProtocol> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(nonatomic) __weak UIView *touchView; // @synthesize touchView=_touchView;
@property(nonatomic) long long position; // @synthesize position=_position;
- (void)layoutImageView;
- (void)layoutSubviews;
- (void)activateTapGestureAction;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)judgePostion:(double)arg1:(double)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setImage:(id)arg1 imageCenterToPosition:(struct CGSize)arg2;
- (id)initWithEventDelegate:(id)arg1 touchView:(id)arg2 position:(long long)arg3;

@end

