//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface RLinearFilter : NSObject
{
    int _weightCount;
    int _maxLoopNum;
    int _currentLoopNum;
    double _qToleranteDistance;
    NSArray *_weight;
}

+ (id)getWeight;
+ (id)linearFilterWithPDFSize:(struct CGSize)arg1;
- (void).cxx_destruct;
@property(nonatomic) int currentLoopNum; // @synthesize currentLoopNum=_currentLoopNum;
@property(nonatomic) int maxLoopNum; // @synthesize maxLoopNum=_maxLoopNum;
@property(retain, nonatomic) NSArray *weight; // @synthesize weight=_weight;
@property(nonatomic) double qToleranteDistance; // @synthesize qToleranteDistance=_qToleranteDistance;
@property(nonatomic) int weightCount; // @synthesize weightCount=_weightCount;
- (int)simplifyFindMidPointFrom:(unsigned long long)arg1 to:(unsigned long long)arg2 array:(id)arg3;
- (id)simplify:(id)arg1 fatherView:(id)arg2;
- (double)distanceBetweenCapturedPoint:(struct CGPoint)arg1 previousPoint:(struct CGPoint)arg2;
- (double)distanceBetweenCapturedPoint:(struct CGPoint)arg1 previousPoint:(struct CGPoint)arg2 control:(struct CGPoint)arg3 scale:(double)arg4;
- (struct CGPoint)insertPointWithBegin:(struct CGPoint)arg1 end:(struct CGPoint)arg2 proportion:(double)arg3;
- (void)tagAtPoint:(id)arg1 fatherView:(id)arg2 type:(int)arg3 text:(id)arg4;
- (id)increaseConsistency:(id)arg1 at:(unsigned long long)arg2 scale:(double)arg3 isEnd:(_Bool)arg4 fatherView:(id)arg5;
- (void)applyGauss:(id)arg1;
- (void)gaussSmooth:(id)arg1 from:(unsigned long long)arg2;
- (id)init;

@end

