//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface RSealTempletAddCollectionCell : UICollectionViewCell
{
    _Bool _addActionEnable;
    UIImageView *_addImageView;
    UILabel *_addLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *addLabel; // @synthesize addLabel=_addLabel;
@property(retain, nonatomic) UIImageView *addImageView; // @synthesize addImageView=_addImageView;
@property(nonatomic) _Bool addActionEnable; // @synthesize addActionEnable=_addActionEnable;
- (void)addTitle:(id)arg1;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

