//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RSignDataModel : NSObject
{
    double _editTime;
    NSString *_ownerName;
    long long _ownerUid;
    NSString *_desc;
    struct CGRect _signFrameInPDF;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) long long ownerUid; // @synthesize ownerUid=_ownerUid;
@property(retain, nonatomic) NSString *ownerName; // @synthesize ownerName=_ownerName;
@property(nonatomic) double editTime; // @synthesize editTime=_editTime;
@property(nonatomic) struct CGRect signFrameInPDF; // @synthesize signFrameInPDF=_signFrameInPDF;
- (long long)getOwnerUid;
- (id)getOwnerName;
- (id)getDesc;

@end

