//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RFollowTouchViewProtocol-Protocol.h"

@class NSArray, NSString, RFittableFontLabel, RFollowRotateView, RFollowTouchView, RSignDashBorderView, UIImageView, WSHandWriteInsertView;
@protocol RFollowRotateViewProtocol;

@interface RSignAdjustSizeView : UIView <RFollowTouchViewProtocol>
{
    _Bool _isTimeShow;
    _Bool _isInsertType;
    id <RFollowRotateViewProtocol> _eventDelegate;
    RFittableFontLabel *_resizeLabel;
    UIImageView *_signImageView;
    RFollowRotateView *_rightTopRotateV;
    RFollowTouchView *_rightBottomScaleV;
    RFollowTouchView *_centerDragV;
    WSHandWriteInsertView *_insertView;
    UIImageView *_timeImageView;
    RSignDashBorderView *_dashBorderImageView;
    UIView *_rotateView;
    RFollowTouchView *_leftTopScaleV;
    RFollowTouchView *_leftBottomScaleV;
    RFollowTouchView *_rightBottomRotateV;
    NSArray *_lineStringArray;
}

+ (id)viewWithDelegate:(id)arg1;
+ (id)viewWithDelegate:(id)arg1 rotateView:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *lineStringArray; // @synthesize lineStringArray=_lineStringArray;
@property(retain, nonatomic) RFollowTouchView *rightBottomRotateV; // @synthesize rightBottomRotateV=_rightBottomRotateV;
@property(retain, nonatomic) RFollowTouchView *leftBottomScaleV; // @synthesize leftBottomScaleV=_leftBottomScaleV;
@property(retain, nonatomic) RFollowTouchView *leftTopScaleV; // @synthesize leftTopScaleV=_leftTopScaleV;
@property(nonatomic) __weak UIView *rotateView; // @synthesize rotateView=_rotateView;
@property(retain, nonatomic) RSignDashBorderView *dashBorderImageView; // @synthesize dashBorderImageView=_dashBorderImageView;
@property(retain, nonatomic) UIImageView *timeImageView; // @synthesize timeImageView=_timeImageView;
@property(retain, nonatomic) WSHandWriteInsertView *insertView; // @synthesize insertView=_insertView;
@property(nonatomic) _Bool isInsertType; // @synthesize isInsertType=_isInsertType;
@property(retain, nonatomic) RFollowTouchView *centerDragV; // @synthesize centerDragV=_centerDragV;
@property(retain, nonatomic) RFollowTouchView *rightBottomScaleV; // @synthesize rightBottomScaleV=_rightBottomScaleV;
@property(retain, nonatomic) RFollowRotateView *rightTopRotateV; // @synthesize rightTopRotateV=_rightTopRotateV;
@property(nonatomic) _Bool isTimeShow; // @synthesize isTimeShow=_isTimeShow;
@property(retain, nonatomic) UIImageView *signImageView; // @synthesize signImageView=_signImageView;
@property(retain, nonatomic) RFittableFontLabel *resizeLabel; // @synthesize resizeLabel=_resizeLabel;
@property(nonatomic) __weak id <RFollowRotateViewProtocol> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
- (void)resizeView:(id)arg1;
- (void)setHandWriteArr:(id)arg1 itemWH:(double)arg2;
- (void)setImage:(id)arg1;
- (id)getTextPointDictInAdjustSizeView;
- (id)timeImage;
- (struct CGRect)timeFrameInAdjustSizeView;
- (struct CGPoint)templetCenterInSizeViewScale;
- (struct CGRect)frameWithTempletFrame:(struct CGRect)arg1;
- (struct CGRect)getTempletFrameWithSizeFrame:(struct CGRect)arg1;
- (id)textColor;
- (id)textName;
- (id)textFont;
- (struct CGRect)getTempletFrameInAdjustSizeView;
- (void)showRotateButton;
- (void)hiddenRotateButton;
- (void)showDashBorderImage;
- (void)hiddenDashBorderImage;
- (void)layoutSubviews;
- (void)layoutSubviewsManual;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

