//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class RSignTempletImageView, RWriteTempletModel, UIButton;
@protocol RWriteTempletCellProtocol;

@interface RWriteTempletCell : UITableViewCell
{
    _Bool _isShowSign;
    int _type;
    RWriteTempletModel *_data;
    id <RWriteTempletCellProtocol> _eventDelegate;
    RSignTempletImageView *_signImageView;
    UIButton *_deleteB;
}

+ (id)cellWithTableView:(id)arg1 indexPath:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *deleteB; // @synthesize deleteB=_deleteB;
@property(retain, nonatomic) RSignTempletImageView *signImageView; // @synthesize signImageView=_signImageView;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) _Bool isShowSign; // @synthesize isShowSign=_isShowSign;
@property(nonatomic) __weak id <RWriteTempletCellProtocol> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(retain, nonatomic) RWriteTempletModel *data; // @synthesize data=_data;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)deleteSign;
- (void)turnOffGesture;
- (void)showSync;
- (void)showAddSign;
- (void)showSignWithData:(id)arg1 eventDelegate:(id)arg2;
- (void)initUI;

@end

