//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SPDropItemProtocol-Protocol.h"

@class NSMutableDictionary, NSString, UIImageView, UILabel, UIView;

@interface SPDropItem : NSObject <SPDropItemProtocol>
{
    _Bool _selected;
    UIView *_displayView;
    CDUnknownBlockType tapHandler;
    CDUnknownBlockType doubleTapHandler;
    CDUnknownBlockType longPressHandler;
    NSString *_title;
    NSMutableDictionary *_titleColorDict;
    NSMutableDictionary *_imageDict;
    UIImageView *_imageView;
    UILabel *_textLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSMutableDictionary *imageDict; // @synthesize imageDict=_imageDict;
@property(retain, nonatomic) NSMutableDictionary *titleColorDict; // @synthesize titleColorDict=_titleColorDict;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) CDUnknownBlockType longPressHandler; // @synthesize longPressHandler;
@property(copy, nonatomic) CDUnknownBlockType doubleTapHandler; // @synthesize doubleTapHandler;
@property(copy, nonatomic) CDUnknownBlockType tapHandler; // @synthesize tapHandler;
@property(readonly, nonatomic) UIView *displayView;
@property(nonatomic, getter=isSelected) _Bool selected;
- (id)imageForState:(unsigned long long)arg1;
- (id)colorForState:(unsigned long long)arg1;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

