//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class NSString, UIColor, UILabel;

@interface SPTextView : UITextView
{
    NSString *_placeholder;
    UILabel *_placeholderLabel;
    UIColor *_placeholderColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
- (struct CGSize)intrinsicContentSize;
- (id)delegate;
- (struct CGRect)placeholderExpectedFrame;
- (struct UIEdgeInsets)placeholderInsets;
- (void)layoutSubviews;
- (void)setTextAlignment:(long long)arg1;
- (void)setFont:(id)arg1;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)refreshPlaceholder;
- (void)awakeFromNib;
- (id)init;
- (void)dealloc;
- (void)initialize;

@end

