//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (FWChat)
+ (id)colorBlackForAddMenuHL;
+ (id)colorBlackForAddMenu;
+ (id)colorBlackAlphaScannerBG;
+ (id)colorBlackBGAlpha;
+ (id)colorBlackBG;
+ (id)colorBlackForNavBar;
+ (id)colorBlueMoment;
+ (id)colorGreenDefault;
+ (id)colorGrayForMoment;
+ (id)colorGrayForChatBar;
+ (id)colorGrayLine;
+ (id)colorGrayCharcoalBG;
+ (id)colorGrayBG;
+ (id)colorTextBlue;
+ (id)colorTextGray1;
+ (id)colorTextGray;
+ (id)colorTextBlack;
+ (id)colorCadetGray;
+ (id)colorBattleshipGray;
+ (id)colorTealBlue;
+ (id)colorChatMsgBlue;
+ (id)colorLine;
+ (id)colorTable;
+ (id)colorWhite;
+ (id)colorBlack;
@end

