//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (Color)
+ (id)resizableImage:(id)arg1;
+ (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (id)imageWithCornerRadius:(double)arg1;
- (unsigned int)RGBAofColor:(id)arg1;
- (id)translatePixelColorByTargetNearBlackColorHex:(unsigned int)arg1 nearWhiteColorHex:(unsigned int)arg2 transColorHex:(unsigned int)arg3 inRect:(struct CGRect)arg4;
- (id)translatePixelColorByTargetNearBlackColorHex:(unsigned int)arg1 nearWhiteColorHex:(unsigned int)arg2 transColorHex:(unsigned int)arg3;
- (id)translatePixelColorByTargetNearBlackColor:(id)arg1 nearWhiteColor:(id)arg2 transColor:(id)arg3 inRect:(struct CGRect)arg4;
- (id)translatePixelColorByTargetNearBlackColor:(id)arg1 nearWhiteColor:(id)arg2 transColor:(id)arg3;
- (id)translatePixelColorByTargetNearBlackColorRGBA:(unsigned int)arg1 nearWhiteColorRGBA:(unsigned int)arg2 transColorRGBA:(unsigned int)arg3 inRect:(struct CGRect)arg4;
- (id)imageByApplyingAlpha:(double)arg1;
@end

