//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (LFPresentation)
+ (void)LFPresentation_swizzledSelector:(SEL)arg1 swizzledSelector:(SEL)arg2;
+ (void)load;
- (void)lf_presentation_track_addGestureRecognizer:(id)arg1;
@end

