//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (LFMECommon)
- (void)LFME_setCornerRadiusWithoutMasks:(float)arg1;
- (void)LFME_setCornerRadius:(float)arg1;
- (id)LFME_colorOfPoint:(struct CGPoint)arg1;
- (id)LFME_captureImageAtFrame:(struct CGRect)arg1;
- (id)LFME_captureImage;
@end

