//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSString, WSDrawManager, WSPDFPage, YYMemoryCache;

@interface WSCacheOperation : NSOperation
{
    int _width;
    int _height;
    int _pdfX;
    int _pdfY;
    int _pdfWidth;
    int _pdfHeight;
    WSDrawManager *_drawManager;
    WSPDFPage *_page;
    YYMemoryCache *_cache;
    NSString *_key;
}

- (void).cxx_destruct;
@property(nonatomic) int pdfHeight; // @synthesize pdfHeight=_pdfHeight;
@property(nonatomic) int pdfWidth; // @synthesize pdfWidth=_pdfWidth;
@property(nonatomic) int pdfY; // @synthesize pdfY=_pdfY;
@property(nonatomic) int pdfX; // @synthesize pdfX=_pdfX;
@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) __weak YYMemoryCache *cache; // @synthesize cache=_cache;
@property(nonatomic) __weak WSPDFPage *page; // @synthesize page=_page;
@property(nonatomic) __weak WSDrawManager *drawManager; // @synthesize drawManager=_drawManager;
- (void)main;

@end

