//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UILabel;
@protocol WSNavigationBarDelegate;

@interface WSNavigationBar : UIView
{
    UIButton *_saveButton;
    CDUnknownBlockType _backOrTurnPageBlock;
    CDUnknownBlockType _turnNextPageBlock;
    id <WSNavigationBarDelegate> _delegate;
    NSString *_title;
    UIView *_container;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UILabel *_navTitleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *navTitleLabel; // @synthesize navTitleLabel=_navTitleLabel;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) UIView *container; // @synthesize container=_container;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak id <WSNavigationBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType turnNextPageBlock; // @synthesize turnNextPageBlock=_turnNextPageBlock;
@property(copy, nonatomic) CDUnknownBlockType backOrTurnPageBlock; // @synthesize backOrTurnPageBlock=_backOrTurnPageBlock;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
- (void)returnButtonMethod;
- (void)saveButtonMethod;
- (void)turnPageToNextPage;
- (void)goBackOrTurnPageToPreviousPage;
- (void)changeTurnPageState;
- (void)resetNavBarState;
- (void)prepareForLayout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

