//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WSDrawManager, WSVDrawContext;

@interface WSVDrawPdfView : UIView
{
    WSVDrawContext *_drawContext;
    WSDrawManager *_drawManager;
    long long _pageNumber;
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(nonatomic) long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(retain, nonatomic) WSDrawManager *drawManager; // @synthesize drawManager=_drawManager;
@property(retain, nonatomic) WSVDrawContext *drawContext; // @synthesize drawContext=_drawContext;
- (void)clearContents;
- (void)dealloc;
- (void)stopRender;
- (_Bool)isDisplayedInScreen:(struct CGRect)arg1;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

