//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WSVerticalReaderManagerFactory : NSObject
{
}

+ (void)destory;
+ (void)destory:(id)arg1;
+ (id)getReuseDrawManager:(id)arg1;
+ (id)getKeyPath:(id)arg1;
+ (id)getKeyPointer:(id)arg1;
+ (id)readerManagerDict;
+ (id)readerManager:(id)arg1;

@end

