//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, UIImage, ZYQAsset, ZYQAssetPickerController;

@protocol ZYQAssetPickerControllerDelegate <NSObject>
- (void)assetPickerControllerDidFinishPickingVideo;
- (void)assetPickerController:(ZYQAssetPickerController *)arg1 didFinishPickingAssets:(NSArray *)arg2;

@optional
- (void)assetPickerControllerDidMinimum:(ZYQAssetPickerController *)arg1;
- (void)assetPickerControllerDidMaximum:(ZYQAssetPickerController *)arg1;
- (void)assetPickerController:(ZYQAssetPickerController *)arg1 didDeselectAsset:(ZYQAsset *)arg2;
- (void)assetPickerController:(ZYQAssetPickerController *)arg1 didSelectAsset:(ZYQAsset *)arg2;
- (void)assetPickerControllerDidCancel:(ZYQAssetPickerController *)arg1;
- (void)assetPickerControllerDidEdit:(UIImage *)arg1;
@end

