//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSError, NSString;

@interface AMapDNSResolver : NSObject
{
    _Bool _done;
    _Bool _shouldCancel;
    NSString *_hostname;
    NSArray *_addressStrs;
    NSError *_error;
    CDUnknownBlockType _block;
    struct __CFHost *_host;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldCancel; // @synthesize shouldCancel=_shouldCancel;
@property _Bool done; // @synthesize done=_done;
@property(retain, nonatomic) struct __CFHost *host; // @synthesize host=_host;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSArray *addressStrs; // @synthesize addressStrs=_addressStrs;
@property(copy, nonatomic) NSString *hostname; // @synthesize hostname=_hostname;
- (void)hostResolutionDoneWithAddresses:(id)arg1;
- (void)stopHostResolution;
- (void)asyncLookupComplete:(CDUnknownBlockType)arg1;
- (id)initWithHost:(id)arg1;
- (void)dealloc;

@end

