//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMapCloudConfig.h"

@class NSNumber;

@interface AMapReGeocodeCacheConfig : AMapCloudConfig
{
    NSNumber *_timeoffset;
    NSNumber *_num;
    NSNumber *_regeoReuseDistance;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *regeoReuseDistance; // @synthesize regeoReuseDistance=_regeoReuseDistance;
@property(readonly, nonatomic) NSNumber *num; // @synthesize num=_num;
@property(readonly, nonatomic) NSNumber *timeoffset; // @synthesize timeoffset=_timeoffset;
- (id)initWithCloudConfig:(id)arg1;

@end

