//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AMapNetworkFailModel, NSMutableArray, NSMutableDictionary, NSUserDefaults;
@protocol OS_dispatch_queue;

@interface AMapNetWorkPerformanceManager : NSObject
{
    NSMutableArray *_successModelQueue;
    NSMutableArray *_failedModelQueue;
    NSMutableDictionary *_uploadingQueue;
    NSObject<OS_dispatch_queue> *_gcdQueue;
    AMapNetworkFailModel *_lastFailModel;
    NSMutableDictionary *_staticDomainOccureErrorDic;
    NSUserDefaults *_netWorkUserDefault;
}

+ (id)defaultManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSUserDefaults *netWorkUserDefault; // @synthesize netWorkUserDefault=_netWorkUserDefault;
@property(retain, nonatomic) NSMutableDictionary *staticDomainOccureErrorDic; // @synthesize staticDomainOccureErrorDic=_staticDomainOccureErrorDic;
@property(retain, nonatomic) AMapNetworkFailModel *lastFailModel; // @synthesize lastFailModel=_lastFailModel;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *gcdQueue; // @synthesize gcdQueue=_gcdQueue;
@property(retain, nonatomic) NSMutableDictionary *uploadingQueue; // @synthesize uploadingQueue=_uploadingQueue;
@property(retain, nonatomic) NSMutableArray *failedModelQueue; // @synthesize failedModelQueue=_failedModelQueue;
@property(retain, nonatomic) NSMutableArray *successModelQueue; // @synthesize successModelQueue=_successModelQueue;
- (void)updateFailQueue:(id)arg1;
- (void)updateSuccessQueue:(id)arg1;
- (void)requestCompleteWithError:(id)arg1 failModel:(id)arg2 sucModel:(id)arg3;
- (_Bool)canUseStaticDomain:(id)arg1;
- (_Bool)isSameDay:(id)arg1 date2:(id)arg2;
- (void)updateStaticDomainOccureError:(id)arg1;
- (id)getFailModel;
- (id)getPerformanceModel;
- (void)addPerformanceModel:(id)arg1;
- (id)init;
- (id)initWithSinglton;

@end

