//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;
@protocol DYPaletteToolViewDelegate;

@interface DYPaletteToolView : UIView
{
    long long _toolMark;
    id <DYPaletteToolViewDelegate> delegate;
    UILabel *_titleLable;
    UIButton *_firstBtn;
    UIButton *_secondBtn;
    UIButton *_fourthBtn;
    UIButton *_fifthBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *fifthBtn; // @synthesize fifthBtn=_fifthBtn;
@property(retain, nonatomic) UIButton *fourthBtn; // @synthesize fourthBtn=_fourthBtn;
@property(retain, nonatomic) UIButton *secondBtn; // @synthesize secondBtn=_secondBtn;
@property(retain, nonatomic) UIButton *firstBtn; // @synthesize firstBtn=_firstBtn;
@property(retain, nonatomic) UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(nonatomic) __weak id <DYPaletteToolViewDelegate> delegate; // @synthesize delegate;
- (void)setshowBottomViewFrame;
- (void)setTopViewFrame;
- (void)layoutSubviews;
- (void)showUploadViewWithOutClear:(_Bool)arg1;
- (void)showSizeView;
- (void)showWidthView;
- (void)showColorView;
- (void)showPdfBottomView;
- (void)showBottomView;
- (id)scaleImage:(id)arg1 toScale:(float)arg2;
- (void)showTopView;
- (void)initView:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withMark:(long long)arg2 delegate:(id)arg3;

@end

