//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSDictionary;
@protocol DYSubmitDelegate;

@interface DYSubmitView : UIView
{
    id <DYSubmitDelegate> delegate;
    NSArray *operationArray;
    NSDictionary *operationDic;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *operationDic; // @synthesize operationDic;
@property(retain, nonatomic) NSArray *operationArray; // @synthesize operationArray;
@property(nonatomic) __weak id <DYSubmitDelegate> delegate; // @synthesize delegate;
- (void)showOperationItem;
- (id)initWithFrame:(struct CGRect)arg1;

@end

