//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ESDevice-Protocol.h"

@class CBPeripheral, NSString;

@interface ESBleDevice : NSObject <ESDevice>
{
    _Bool _isSystemPairTriggered;
    CBPeripheral *peripheral;
    NSString *name;
    NSString *mediaID;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isSystemPairTriggered; // @synthesize isSystemPairTriggered=_isSystemPairTriggered;
@property(retain, nonatomic) NSString *mediaID; // @synthesize mediaID;
@property(retain, nonatomic) CBPeripheral *peripheral; // @synthesize peripheral;
- (void)readyForSend:(CDUnknownBlockType)arg1;
- (void)free;
- (_Bool)disconnect;
- (long long)connect;
- (_Bool)connect:(double)arg1;
- (_Bool)isConnected;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name;
- (_Bool)isIsSystemPairTriggered;
- (id)initWithSn:(id)arg1;
- (id)initWithPeripheral:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

