//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol ESDevice;

@interface ESSecurePipe : NSObject
{
    id <ESDevice> _device;
}

+ (id)sendData:(id)arg1 encrypted:(_Bool)arg2;
+ (void)buildForDevice:(id)arg1;
+ (id)currentDevice;
+ (void)setDevice:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) id <ESDevice> device; // @synthesize device=_device;

@end

