//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CaptureDataOutputProtocol-Protocol.h"

@class CircleView, MyBottomView, NSString, RemindView, UIImage, UIImageView, UILabel, VideoCaptureDevice;

@interface FaceBaseViewController : UIViewController <CaptureDataOutputProtocol>
{
    _Bool _hasFinished;
    UIImageView *_displayImageView;
    UIImage *_coverImage;
    UIImageView *_coverImageView;
    MyBottomView *_bottomView;
    CircleView *_circleView;
    VideoCaptureDevice *_videoCapture;
    UILabel *_remindLabel;
    RemindView *_remindView;
    UILabel *_remindDetailLabel;
    UIImageView *_successImage;
    struct CGRect _previewRect;
    struct CGRect _detectRect;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *successImage; // @synthesize successImage=_successImage;
@property(retain, nonatomic) UILabel *remindDetailLabel; // @synthesize remindDetailLabel=_remindDetailLabel;
@property(retain, nonatomic) RemindView *remindView; // @synthesize remindView=_remindView;
@property(retain, nonatomic) UILabel *remindLabel; // @synthesize remindLabel=_remindLabel;
@property(retain, nonatomic) VideoCaptureDevice *videoCapture; // @synthesize videoCapture=_videoCapture;
@property(retain, nonatomic) CircleView *circleView; // @synthesize circleView=_circleView;
@property(nonatomic) struct CGRect detectRect; // @synthesize detectRect=_detectRect;
@property(nonatomic) struct CGRect previewRect; // @synthesize previewRect=_previewRect;
@property(retain, nonatomic) MyBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) UIImage *coverImage; // @synthesize coverImage=_coverImage;
@property(nonatomic) _Bool hasFinished; // @synthesize hasFinished=_hasFinished;
@property(retain, nonatomic) UIImageView *displayImageView; // @synthesize displayImageView=_displayImageView;
- (void)captureError;
- (void)captureOutputSampleBuffer:(id)arg1;
- (void)onAppBecomeActive;
- (void)onAppWillResignAction;
- (void)closeAction;
- (void)faceProcesss:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)singleActionSuccess:(_Bool)arg1;
- (void)warningStatus:(unsigned long long)arg1 warning:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

