//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FWAppThemeNavBtn, NSString;

@interface FWAddMenuItem : NSObject
{
    long long _type;
    NSString *_title;
    NSString *_iconPath;
    NSString *_className;
    FWAppThemeNavBtn *_themeNavBtn;
}

+ (id)createWithType:(long long)arg1 title:(id)arg2 iconPath:(id)arg3 className:(id)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) FWAppThemeNavBtn *themeNavBtn; // @synthesize themeNavBtn=_themeNavBtn;
@property(retain, nonatomic) NSString *className; // @synthesize className=_className;
@property(retain, nonatomic) NSString *iconPath; // @synthesize iconPath=_iconPath;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

