//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSNumber, NSString;

@interface FWAppThemeDetail : MTLModel <MTLJSONSerializing>
{
    NSString *_theme_id;
    NSString *_theme_name;
    NSString *_select;
    NSNumber *_isdefault;
    NSString *_status;
    NSString *_client_type;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *client_type; // @synthesize client_type=_client_type;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSNumber *isdefault; // @synthesize isdefault=_isdefault;
@property(copy, nonatomic) NSString *select; // @synthesize select=_select;
@property(copy, nonatomic) NSString *theme_name; // @synthesize theme_name=_theme_name;
@property(copy, nonatomic) NSString *theme_id; // @synthesize theme_id=_theme_id;

@end

