//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface FWAppTheme : MTLModel <MTLJSONSerializing>
{
    NSString *_nav_bgcolor;
    NSString *_nav_textcolor_default;
    NSString *_nav_textcolor_selected;
    NSNumber *_nav_showtext;
    NSArray *_navlist;
    NSString *_theme_id;
    NSString *_theme_name;
    NSString *_other_tag;
}

+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *other_tag; // @synthesize other_tag=_other_tag;
@property(copy, nonatomic) NSString *theme_name; // @synthesize theme_name=_theme_name;
@property(copy, nonatomic) NSString *theme_id; // @synthesize theme_id=_theme_id;
@property(retain, nonatomic) NSArray *navlist; // @synthesize navlist=_navlist;
@property(copy, nonatomic) NSNumber *nav_showtext; // @synthesize nav_showtext=_nav_showtext;
@property(copy, nonatomic) NSString *nav_textcolor_selected; // @synthesize nav_textcolor_selected=_nav_textcolor_selected;
@property(copy, nonatomic) NSString *nav_textcolor_default; // @synthesize nav_textcolor_default=_nav_textcolor_default;
@property(copy, nonatomic) NSString *nav_bgcolor; // @synthesize nav_bgcolor=_nav_bgcolor;

@end

