//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSArray, NSString;

@interface FWCallConversation : MTLModel <MTLJSONSerializing>
{
    NSString *_chatId;
    long long _chatType;
    NSString *_chatTargetId;
    long long _chatMemberCount;
    NSArray *_chatMemberIdList;
    NSString *_chatMemberIds;
    NSString *_lastCallSenderId;
    long long _lastCallType;
    long long _lastCallTime;
}

+ (id)JSONKeyPathsByPropertyKey;
+ (const struct WCTProperty *)lastCallTime;
+ (const struct WCTProperty *)lastCallType;
+ (const struct WCTProperty *)lastCallSenderId;
+ (const struct WCTProperty *)chatMemberIds;
+ (const struct WCTProperty *)chatMemberIdList;
+ (const struct WCTProperty *)chatMemberCount;
+ (const struct WCTProperty *)chatTargetId;
+ (const struct WCTProperty *)chatType;
+ (const struct WCTProperty *)chatId;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
- (void).cxx_destruct;
@property(nonatomic) long long lastCallTime; // @synthesize lastCallTime=_lastCallTime;
@property(nonatomic) long long lastCallType; // @synthesize lastCallType=_lastCallType;
@property(retain, nonatomic) NSString *lastCallSenderId; // @synthesize lastCallSenderId=_lastCallSenderId;
@property(retain, nonatomic) NSString *chatMemberIds; // @synthesize chatMemberIds=_chatMemberIds;
@property(retain, nonatomic) NSArray *chatMemberIdList; // @synthesize chatMemberIdList=_chatMemberIdList;
@property(nonatomic) long long chatMemberCount; // @synthesize chatMemberCount=_chatMemberCount;
@property(retain, nonatomic) NSString *chatTargetId; // @synthesize chatTargetId=_chatTargetId;
@property(nonatomic) long long chatType; // @synthesize chatType=_chatType;
@property(retain, nonatomic) NSString *chatId; // @synthesize chatId=_chatId;

@end

