//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FWMoreMenuItem, NSString;

@interface FWChatMenuitem : NSObject
{
    _Bool _isMore;
    NSString *_iamgeStr;
    NSString *_itemText;
    SEL _action;
    id _target;
    FWMoreMenuItem *_moreIem;
    NSString *_msgId;
}

+ (id)menuitemWithImage:(id)arg1 text:(id)arg2;
+ (id)menuitemWithImage:(id)arg1 text:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *msgId; // @synthesize msgId=_msgId;
@property(retain, nonatomic) FWMoreMenuItem *moreIem; // @synthesize moreIem=_moreIem;
@property(nonatomic) _Bool isMore; // @synthesize isMore=_isMore;
@property(retain, nonatomic) id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *itemText; // @synthesize itemText=_itemText;
@property(copy, nonatomic) NSString *iamgeStr; // @synthesize iamgeStr=_iamgeStr;

@end

