//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSIndexPath, NSString, UIButton, UITableView;

@interface FWCompanyView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _didChoseCompany;
    UIButton *_arrowBtn;
    NSArray *_datasource;
    UITableView *_tableView;
    UIView *_backView;
    NSIndexPath *_indexPath;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak UIButton *arrowBtn; // @synthesize arrowBtn=_arrowBtn;
@property(copy, nonatomic) CDUnknownBlockType didChoseCompany; // @synthesize didChoseCompany=_didChoseCompany;
- (void)layoutSubviews;
- (void)close;
- (void)closeCompany;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)showInRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

