//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class NSString, UIViewController;

@interface FWCustomPresentAnimation : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _dismiss;
    UIViewController *_toVC;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIViewController *toVC; // @synthesize toVC=_toVC;
@property(nonatomic, getter=isDismissed) _Bool dismiss; // @synthesize dismiss=_dismiss;
- (void)animationEnded:(_Bool)arg1;
- (void)RunDismissAnimation:(id)arg1 fromVC:(id)arg2 toVC:(id)arg3 fromView:(id)arg4 toView:(id)arg5;
- (void)RunPresentAnimation:(id)arg1 fromVC:(id)arg2 toVC:(id)arg3 fromView:(id)arg4 toView:(id)arg5;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

