//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PGDatePickerDelegate-Protocol.h"

@class NSDate, NSString, PGDatePickManager, PGDatePicker;

@interface FWDatePickerView : UIView <PGDatePickerDelegate>
{
    _Bool _autoSelected;
    NSDate *_minimumDate;
    NSDate *_maximumDate;
    CDUnknownBlockType _datePickerSelResult;
    NSString *_weekStr;
    PGDatePickManager *_datePickManager;
    PGDatePicker *_datePicker;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PGDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain, nonatomic) PGDatePickManager *datePickManager; // @synthesize datePickManager=_datePickManager;
@property(copy, nonatomic) NSString *weekStr; // @synthesize weekStr=_weekStr;
@property(copy, nonatomic) CDUnknownBlockType datePickerSelResult; // @synthesize datePickerSelResult=_datePickerSelResult;
@property(retain, nonatomic) NSDate *maximumDate; // @synthesize maximumDate=_maximumDate;
@property(retain, nonatomic) NSDate *minimumDate; // @synthesize minimumDate=_minimumDate;
@property(nonatomic) _Bool autoSelected; // @synthesize autoSelected=_autoSelected;
- (void)setDate:(id)arg1 animated:(_Bool)arg2;
- (void)datePicker:(id)arg1 didSelectDate:(id)arg2;
- (id)viewControllerWithView:(id)arg1;
- (void)showDateViewWithMode:(long long)arg1 inView:(id)arg2;
- (void)showDateAndTimeInView:(id)arg1;
- (void)showHourMinuteAndSecondInView:(id)arg1;
- (void)showHourAndMinuteInView:(id)arg1;
- (void)showDateHourMinuteSecondInView:(id)arg1;
- (void)showDateHourMinuteInView:(id)arg1;
- (void)showAllDateInView:(id)arg1;
- (void)showAllDateYearAndMouthInView:(id)arg1;
- (void)showDateYearInView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

