//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FWEncryptConfig : MTLModel <MTLJSONSerializing>
{
    NSString *_sm2_publickey;
    NSString *_rsa_publickey;
    NSString *_data_encrypt;
    NSString *_key_encrypt;
    long long _encryptStatus;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(nonatomic) long long encryptStatus; // @synthesize encryptStatus=_encryptStatus;
@property(copy, nonatomic) NSString *key_encrypt; // @synthesize key_encrypt=_key_encrypt;
@property(copy, nonatomic) NSString *data_encrypt; // @synthesize data_encrypt=_data_encrypt;
@property(copy, nonatomic) NSString *rsa_publickey; // @synthesize rsa_publickey=_rsa_publickey;
@property(copy, nonatomic) NSString *sm2_publickey; // @synthesize sm2_publickey=_sm2_publickey;
- (id)valueForUndefinedKey:(id)arg1;
- (id)init;

@end

