//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSError, NSLayoutConstraint, NSURL, UIButton, UIImageView, UILabel;
@protocol FWerrorDelegate;

@interface FWerrorView : UIView
{
    UIImageView *_imageView;
    UILabel *_label;
    UIButton *_button;
    id <FWerrorDelegate> _delegate;
    UIButton *_detailButton;
    NSError *_error;
    NSURL *_url;
    NSLayoutConstraint *_detailBtnConstrint;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *detailBtnConstrint; // @synthesize detailBtnConstrint=_detailBtnConstrint;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) __weak UIButton *detailButton; // @synthesize detailButton=_detailButton;
@property(nonatomic) __weak id <FWerrorDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (void)detailClick:(id)arg1;
- (void)tryAgain:(id)arg1;

@end

