//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSURL, UIImageView;

@interface FWExpressionViewController : UIViewController
{
    NSURL *_resourceUrl;
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSURL *resourceUrl; // @synthesize resourceUrl=_resourceUrl;
- (void)viewDidLoad;

@end

