//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FWLoginConfigInfo : MTLModel <MTLJSONSerializing>
{
    int _ios_force_update;
    int _ios_force_update_enterprise;
    int _ios_check_update_develop;
    int _ios_no_screenshot;
    int _app_url_preload;
    int _msg_no_copy;
    int _noti_to_detail;
    int _app_preview_more;
    int _app_webview_more;
    int _forbid_download_preview;
    int _cid;
    int _app_call_btn_mode;
    int _app_call_dial_disable;
    int _video_count_limit;
    int _msg_thumbnail_mode;
    int _msg_audio_mode;
    int _ios_locaton_examine;
    int _iOS_loginCancal_safeKeyboard;
    int _isRandomKeyBoard;
    int _cacal_SafeKeyBoard_SelectBg;
    int _client_PrivateChat_HiddenName;
    int _iOS_Check_HTTPEnable;
    int _ios_root_check;
    int _enable_autogiration;
    int _msg_group_atall;
    int _msg_auto_search;
    int _address_auto_search;
    int _ios_block_external_share;
    int _iOS_Open_ScanResultGBK;
    int _ios_rich_text_msg_open_safari;
    int _authenticatorCertType;
    int _msg_list_group;
    int _shieldSavePic;
    int _ios_notsetup_umeng;
    int _msg_dont_disturb;
    int _create_wx_group;
    int _chooseimage_watermark_latitude;
    int _open_private_conversation_permission;
    int _ios_SSLcertificates;
    int _ios_face_close_biopsy;
    int _network_switch_detection;
    int _ios_background_keep_alive;
    int _personCard_openFollow;
    int _wakeup_update_tasklist_time;
    NSString *_server_urls;
    NSString *_ios_googleMap_key;
    NSString *_ios_baiduMap_key;
    NSString *_face_sdk_type;
    NSString *_face_pos_yaw;
    NSString *_face_random;
    NSString *_face_actions;
    NSString *_iOScustomUserAgent;
    NSString *_iOS_SingAgain_OrganiID;
    NSString *_set_cookie_domain;
    NSString *_msg_file_allow_exts;
    NSString *_ios_third_schemes;
    NSString *_ios_cookie_fix_paths;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(nonatomic) int wakeup_update_tasklist_time; // @synthesize wakeup_update_tasklist_time=_wakeup_update_tasklist_time;
@property(nonatomic) int personCard_openFollow; // @synthesize personCard_openFollow=_personCard_openFollow;
@property(nonatomic) int ios_background_keep_alive; // @synthesize ios_background_keep_alive=_ios_background_keep_alive;
@property(nonatomic) int network_switch_detection; // @synthesize network_switch_detection=_network_switch_detection;
@property(nonatomic) int ios_face_close_biopsy; // @synthesize ios_face_close_biopsy=_ios_face_close_biopsy;
@property(nonatomic) int ios_SSLcertificates; // @synthesize ios_SSLcertificates=_ios_SSLcertificates;
@property(nonatomic) int open_private_conversation_permission; // @synthesize open_private_conversation_permission=_open_private_conversation_permission;
@property(nonatomic) int chooseimage_watermark_latitude; // @synthesize chooseimage_watermark_latitude=_chooseimage_watermark_latitude;
@property(nonatomic) int create_wx_group; // @synthesize create_wx_group=_create_wx_group;
@property(nonatomic) int msg_dont_disturb; // @synthesize msg_dont_disturb=_msg_dont_disturb;
@property(nonatomic) int ios_notsetup_umeng; // @synthesize ios_notsetup_umeng=_ios_notsetup_umeng;
@property(copy, nonatomic) NSString *ios_cookie_fix_paths; // @synthesize ios_cookie_fix_paths=_ios_cookie_fix_paths;
@property(copy, nonatomic) NSString *ios_third_schemes; // @synthesize ios_third_schemes=_ios_third_schemes;
@property(nonatomic) int shieldSavePic; // @synthesize shieldSavePic=_shieldSavePic;
@property(nonatomic) int msg_list_group; // @synthesize msg_list_group=_msg_list_group;
@property(nonatomic) int authenticatorCertType; // @synthesize authenticatorCertType=_authenticatorCertType;
@property(copy, nonatomic) NSString *msg_file_allow_exts; // @synthesize msg_file_allow_exts=_msg_file_allow_exts;
@property(nonatomic) int ios_rich_text_msg_open_safari; // @synthesize ios_rich_text_msg_open_safari=_ios_rich_text_msg_open_safari;
@property(nonatomic) int iOS_Open_ScanResultGBK; // @synthesize iOS_Open_ScanResultGBK=_iOS_Open_ScanResultGBK;
@property(nonatomic) int ios_block_external_share; // @synthesize ios_block_external_share=_ios_block_external_share;
@property(nonatomic) int address_auto_search; // @synthesize address_auto_search=_address_auto_search;
@property(nonatomic) int msg_auto_search; // @synthesize msg_auto_search=_msg_auto_search;
@property(nonatomic) int msg_group_atall; // @synthesize msg_group_atall=_msg_group_atall;
@property(nonatomic) int enable_autogiration; // @synthesize enable_autogiration=_enable_autogiration;
@property(copy, nonatomic) NSString *set_cookie_domain; // @synthesize set_cookie_domain=_set_cookie_domain;
@property(nonatomic) int ios_root_check; // @synthesize ios_root_check=_ios_root_check;
@property(nonatomic) int iOS_Check_HTTPEnable; // @synthesize iOS_Check_HTTPEnable=_iOS_Check_HTTPEnable;
@property(copy, nonatomic) NSString *iOS_SingAgain_OrganiID; // @synthesize iOS_SingAgain_OrganiID=_iOS_SingAgain_OrganiID;
@property(nonatomic) int client_PrivateChat_HiddenName; // @synthesize client_PrivateChat_HiddenName=_client_PrivateChat_HiddenName;
@property(nonatomic) int cacal_SafeKeyBoard_SelectBg; // @synthesize cacal_SafeKeyBoard_SelectBg=_cacal_SafeKeyBoard_SelectBg;
@property(nonatomic) int isRandomKeyBoard; // @synthesize isRandomKeyBoard=_isRandomKeyBoard;
@property(nonatomic) int iOS_loginCancal_safeKeyboard; // @synthesize iOS_loginCancal_safeKeyboard=_iOS_loginCancal_safeKeyboard;
@property(copy, nonatomic) NSString *iOScustomUserAgent; // @synthesize iOScustomUserAgent=_iOScustomUserAgent;
@property(copy, nonatomic) NSString *face_actions; // @synthesize face_actions=_face_actions;
@property(copy, nonatomic) NSString *face_random; // @synthesize face_random=_face_random;
@property(copy, nonatomic) NSString *face_pos_yaw; // @synthesize face_pos_yaw=_face_pos_yaw;
@property(copy, nonatomic) NSString *face_sdk_type; // @synthesize face_sdk_type=_face_sdk_type;
@property(copy, nonatomic) NSString *ios_baiduMap_key; // @synthesize ios_baiduMap_key=_ios_baiduMap_key;
@property(copy, nonatomic) NSString *ios_googleMap_key; // @synthesize ios_googleMap_key=_ios_googleMap_key;
@property(copy, nonatomic) NSString *server_urls; // @synthesize server_urls=_server_urls;
@property(nonatomic) int ios_locaton_examine; // @synthesize ios_locaton_examine=_ios_locaton_examine;
@property(nonatomic) int msg_audio_mode; // @synthesize msg_audio_mode=_msg_audio_mode;
@property(nonatomic) int msg_thumbnail_mode; // @synthesize msg_thumbnail_mode=_msg_thumbnail_mode;
@property(nonatomic) int video_count_limit; // @synthesize video_count_limit=_video_count_limit;
@property(nonatomic) int app_call_dial_disable; // @synthesize app_call_dial_disable=_app_call_dial_disable;
@property(nonatomic) int app_call_btn_mode; // @synthesize app_call_btn_mode=_app_call_btn_mode;
@property(nonatomic) int cid; // @synthesize cid=_cid;
@property(nonatomic) int forbid_download_preview; // @synthesize forbid_download_preview=_forbid_download_preview;
@property(nonatomic) int app_webview_more; // @synthesize app_webview_more=_app_webview_more;
@property(nonatomic) int app_preview_more; // @synthesize app_preview_more=_app_preview_more;
@property(nonatomic) int noti_to_detail; // @synthesize noti_to_detail=_noti_to_detail;
@property(nonatomic) int msg_no_copy; // @synthesize msg_no_copy=_msg_no_copy;
@property(nonatomic) int app_url_preload; // @synthesize app_url_preload=_app_url_preload;
@property(nonatomic) int ios_no_screenshot; // @synthesize ios_no_screenshot=_ios_no_screenshot;
@property(nonatomic) int ios_check_update_develop; // @synthesize ios_check_update_develop=_ios_check_update_develop;
@property(nonatomic) int ios_force_update_enterprise; // @synthesize ios_force_update_enterprise=_ios_force_update_enterprise;
@property(nonatomic) int ios_force_update; // @synthesize ios_force_update=_ios_force_update;
- (id)init;

@end

