//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FWWebViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class FBKVOController, NSString, UIButton, UIColor, UIImageView, UILabel, UIScrollView, UITextField, UIView;

@interface FWLoginViewController : FWWebViewController <UITextFieldDelegate, UIGestureRecognizerDelegate>
{
    FBKVOController *_KVOController;
    _Bool _clearPwd;
    _Bool _isShowBgimage;
    UIButton *_forgetBtn;
    UIButton *_registerBtn;
    NSString *_userloginkey;
    NSString *_phoneloginkey;
    UIButton *_eyeBtn;
    UITextField *_phoneField;
    UITextField *_passwordField;
    UITextField *_imageCodeField;
    UIButton *_loginBtn;
    UIButton *_moreBtn;
    UIImageView *_imageCodeView;
    UIView *_logoView;
    UIImageView *_logoBgView;
    UIView *_inputView;
    UIView *_codeView;
    UIView *_defaultlogoView;
    UIImageView *_bgView;
    UILabel *_copyright;
    UIScrollView *_contentView;
    UIButton *_changeLanBtn;
    UIView *_remberView;
    UIView *_loginView;
    UIButton *_remBtn;
    UIView *_agreeView;
    UIButton *_agreeBtn;
    UIButton *_checkAgreeBtn;
    UIView *_pwdView;
    UIColor *_loginBtnEnableColor;
    UIColor *_loginBtnAbleColor;
    UIColor *_loginBtnTitleColor;
    UIImageView *_logo;
    UILabel *_label;
    UIView *_accountView;
    UIView *_lineForPhone;
    UITextField *_phone1Field;
    UIView *_lineForPassword;
    UIView *_smallCodeView;
    UIView *_lineForAuth;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *lineForAuth; // @synthesize lineForAuth=_lineForAuth;
@property(retain, nonatomic) UIView *smallCodeView; // @synthesize smallCodeView=_smallCodeView;
@property(retain, nonatomic) UIView *lineForPassword; // @synthesize lineForPassword=_lineForPassword;
@property(retain, nonatomic) UITextField *phone1Field; // @synthesize phone1Field=_phone1Field;
@property(retain, nonatomic) UIView *lineForPhone; // @synthesize lineForPhone=_lineForPhone;
@property(retain, nonatomic) UIView *accountView; // @synthesize accountView=_accountView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *logo; // @synthesize logo=_logo;
@property(nonatomic) _Bool isShowBgimage; // @synthesize isShowBgimage=_isShowBgimage;
@property(retain, nonatomic) UIColor *loginBtnTitleColor; // @synthesize loginBtnTitleColor=_loginBtnTitleColor;
@property(retain, nonatomic) UIColor *loginBtnAbleColor; // @synthesize loginBtnAbleColor=_loginBtnAbleColor;
@property(retain, nonatomic) UIColor *loginBtnEnableColor; // @synthesize loginBtnEnableColor=_loginBtnEnableColor;
@property(nonatomic) __weak UIView *pwdView; // @synthesize pwdView=_pwdView;
@property(nonatomic) __weak UIButton *checkAgreeBtn; // @synthesize checkAgreeBtn=_checkAgreeBtn;
@property(nonatomic) __weak UIButton *agreeBtn; // @synthesize agreeBtn=_agreeBtn;
@property(nonatomic) __weak UIView *agreeView; // @synthesize agreeView=_agreeView;
@property(nonatomic) __weak UIButton *remBtn; // @synthesize remBtn=_remBtn;
@property(nonatomic) __weak UIView *loginView; // @synthesize loginView=_loginView;
@property(nonatomic) __weak UIView *remberView; // @synthesize remberView=_remberView;
@property(nonatomic) __weak UIButton *changeLanBtn; // @synthesize changeLanBtn=_changeLanBtn;
@property(nonatomic) __weak UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UILabel *copyright; // @synthesize copyright=_copyright;
@property(nonatomic) __weak UIImageView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UIView *defaultlogoView; // @synthesize defaultlogoView=_defaultlogoView;
@property(nonatomic) __weak UIView *codeView; // @synthesize codeView=_codeView;
@property(nonatomic) __weak UIView *inputView; // @synthesize inputView=_inputView;
@property(nonatomic) __weak UIImageView *logoBgView; // @synthesize logoBgView=_logoBgView;
@property(nonatomic) __weak UIView *logoView; // @synthesize logoView=_logoView;
@property(nonatomic) __weak UIImageView *imageCodeView; // @synthesize imageCodeView=_imageCodeView;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(retain, nonatomic) UITextField *imageCodeField; // @synthesize imageCodeField=_imageCodeField;
@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) UITextField *phoneField; // @synthesize phoneField=_phoneField;
@property(nonatomic) __weak UIButton *eyeBtn; // @synthesize eyeBtn=_eyeBtn;
@property(retain, nonatomic) NSString *phoneloginkey; // @synthesize phoneloginkey=_phoneloginkey;
@property(retain, nonatomic) NSString *userloginkey; // @synthesize userloginkey=_userloginkey;
@property(retain, nonatomic) UIButton *registerBtn; // @synthesize registerBtn=_registerBtn;
@property(retain, nonatomic) UIButton *forgetBtn; // @synthesize forgetBtn=_forgetBtn;
@property(nonatomic) _Bool clearPwd; // @synthesize clearPwd=_clearPwd;
- (void)handleErrorWith:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)reachabilityChanged:(id)arg1;
- (void)addReachabilityChangedNotification;
- (void)crossScreenFitLoginView;
- (void)viewDidLayoutSubviews;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)dealloc;
- (void)keyboardHidden;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handleTapGesture:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (id)getUserCheckKey;
- (id)getCheckAgreeMentKey;
- (void)setupTextFiledWithtextFiled:(id)arg1 iconName:(id)arg2;
- (id)newTextField:(id)arg1;
- (void)setupBottomView;
- (void)setupRegistAndForgetFrame;
- (void)setupRegistandForgetView;
- (void)setupServiceAgreement;
- (void)setupLoginView;
- (void)setupRemberView;
- (void)refershRemberView;
- (id)getRemberPwdKey;
- (void)setupPasswordFiled;
- (void)setupInputView;
- (void)setupLogoView;
- (void)setupBgView;
- (void)agreeBtnClick:(id)arg1;
- (void)checkBtnClick:(id)arg1;
- (void)changeLanClick:(id)arg1;
- (void)changeCapucha:(id)arg1;
- (void)forgetAction:(id)arg1;
- (void)registerAction:(id)arg1;
- (void)eyebtnClick:(id)arg1;
- (void)remPwdBtnDidClick:(id)arg1;
- (void)moreAction:(id)arg1;
- (void)loginAction:(id)arg1;
- (void)textFieldTextChange:(id)arg1;
- (void)refershLoginUIWithDic:(id)arg1;
- (id)findImageViewWith:(id)arg1;
- (void)setupLoginData;
- (void)setupTargetTextFiled;
- (void)changeStatusStyle;
- (void)switchServer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setupObserverRefershUIKVO;
- (void)setupUI;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

