//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FWMenuItem : NSObject
{
    _Bool _showRightRedPoint;
    int _itemType;
    NSString *_iconPath;
    NSString *_title;
    NSString *_subTitle;
    NSString *_rightIconURL;
    NSString *_itemId;
}

+ (id)createMenuWithIconPath:(id)arg1 title:(id)arg2 itemType:(int)arg3 itemId:(id)arg4;
+ (id)createMenuWithIconPath:(id)arg1 title:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) _Bool showRightRedPoint; // @synthesize showRightRedPoint=_showRightRedPoint;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(nonatomic) int itemType; // @synthesize itemType=_itemType;
@property(retain, nonatomic) NSString *rightIconURL; // @synthesize rightIconURL=_rightIconURL;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *iconPath; // @synthesize iconPath=_iconPath;

@end

