//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FWContactSelectViewControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class FWMessageModel, FWPlacehoderTextView, NSMutableArray, NSString, UIButton, UILabel, UIScrollView, UIView;

@interface FWNewTaskDingController : UIViewController <UIScrollViewDelegate, UITextViewDelegate, FWContactSelectViewControllerDelegate>
{
    _Bool _canEdit;
    int _msg_type;
    int _send_type;
    CDUnknownBlockType _updateDing;
    NSMutableArray *_groupMembers;
    FWMessageModel *_messageModel;
    NSString *_text;
    long long _focusTaskChoosenStyle;
    UIButton *_submitbtn;
    UIScrollView *_scrollView;
    FWPlacehoderTextView *_textView;
    UIView *_reciveView;
    UIView *_sendStyleView;
    UIView *_sendTimeView;
    UIView *_timeChoseView;
    UIView *_peopleView;
    UILabel *_countlabel;
    UILabel *_timechoseLabel;
    NSMutableArray *_meberViews;
    NSMutableArray *_personMebers;
    NSString *_send_time;
    NSString *_messageId;
    NSMutableArray *_types;
    UIButton *_button;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSMutableArray *types; // @synthesize types=_types;
@property(copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(copy, nonatomic) NSString *send_time; // @synthesize send_time=_send_time;
@property(nonatomic) int send_type; // @synthesize send_type=_send_type;
@property(nonatomic) int msg_type; // @synthesize msg_type=_msg_type;
@property(retain, nonatomic) NSMutableArray *personMebers; // @synthesize personMebers=_personMebers;
@property(retain, nonatomic) NSMutableArray *meberViews; // @synthesize meberViews=_meberViews;
@property(nonatomic) __weak UILabel *timechoseLabel; // @synthesize timechoseLabel=_timechoseLabel;
@property(nonatomic) __weak UILabel *countlabel; // @synthesize countlabel=_countlabel;
@property(nonatomic) __weak UIView *peopleView; // @synthesize peopleView=_peopleView;
@property(nonatomic) __weak UIView *timeChoseView; // @synthesize timeChoseView=_timeChoseView;
@property(nonatomic) __weak UIView *sendTimeView; // @synthesize sendTimeView=_sendTimeView;
@property(nonatomic) __weak UIView *sendStyleView; // @synthesize sendStyleView=_sendStyleView;
@property(nonatomic) __weak UIView *reciveView; // @synthesize reciveView=_reciveView;
@property(nonatomic) __weak FWPlacehoderTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIButton *submitbtn; // @synthesize submitbtn=_submitbtn;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(nonatomic) long long focusTaskChoosenStyle; // @synthesize focusTaskChoosenStyle=_focusTaskChoosenStyle;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) FWMessageModel *messageModel; // @synthesize messageModel=_messageModel;
@property(retain, nonatomic) NSMutableArray *groupMembers; // @synthesize groupMembers=_groupMembers;
@property(copy, nonatomic) CDUnknownBlockType updateDing; // @synthesize updateDing=_updateDing;
- (void)viewDidLayoutSubviews;
- (void)showImagePeopleWithMebers:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onMultiSelectGroupReturn:(id)arg1 mode:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)timeChose;
- (void)popTimeChoseViw:(id)arg1;
- (void)setupMsgTypeWithSegmIndex:(long long)arg1;
- (void)selectItem:(id)arg1;
- (void)showChosedDetailVc;
- (void)choseRecivePerson;
- (void)getnewDingAndUpdateCpmversationlist;
- (void)submitTaskFouces;
- (id)getNameLabelWithName:(id)arg1;
- (id)getbgView;
- (void)setupContentView;
- (void)setupNavgation;
- (void)showUnreadPersonViewFromMessageWithArry:(id)arg1;
- (void)setupData;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

