//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface FWRegisterViewController : UIViewController <UITextFieldDelegate>
{
    _Bool _isForgetPwd;
    _Bool _showImageCode;
    _Bool _push;
    UILabel *_titleLabel;
    UIButton *_nextBtn;
    UITextField *_phoneFiled;
    UIView *_placeView;
    UIImageView *_verImageView;
    UITextField *_verCodeField;
    UIView *_imageBgView;
    UILabel *_phonePrefixLabel;
    UIButton *_getMsgBtn;
    UITextField *_msgField;
    double _imageBgViewH;
    NSLayoutConstraint *_varImageBgViewH;
    NSString *_registerkey;
    NSLayoutConstraint *_pwdViewH;
    UITextField *_pwdFiled;
    UIView *_pwdView;
    long long _barStyle;
}

- (void).cxx_destruct;
@property(nonatomic) long long barStyle; // @synthesize barStyle=_barStyle;
@property(nonatomic, getter=isPush) _Bool push; // @synthesize push=_push;
@property(nonatomic) __weak UIView *pwdView; // @synthesize pwdView=_pwdView;
@property(nonatomic) __weak UITextField *pwdFiled; // @synthesize pwdFiled=_pwdFiled;
@property(nonatomic) __weak NSLayoutConstraint *pwdViewH; // @synthesize pwdViewH=_pwdViewH;
@property(retain, nonatomic) NSString *registerkey; // @synthesize registerkey=_registerkey;
@property(nonatomic) __weak NSLayoutConstraint *varImageBgViewH; // @synthesize varImageBgViewH=_varImageBgViewH;
@property(nonatomic) double imageBgViewH; // @synthesize imageBgViewH=_imageBgViewH;
@property(nonatomic) _Bool showImageCode; // @synthesize showImageCode=_showImageCode;
@property(nonatomic) __weak UITextField *msgField; // @synthesize msgField=_msgField;
@property(nonatomic) __weak UIButton *getMsgBtn; // @synthesize getMsgBtn=_getMsgBtn;
@property(nonatomic) __weak UILabel *phonePrefixLabel; // @synthesize phonePrefixLabel=_phonePrefixLabel;
@property(nonatomic) __weak UIView *imageBgView; // @synthesize imageBgView=_imageBgView;
@property(nonatomic) __weak UITextField *verCodeField; // @synthesize verCodeField=_verCodeField;
@property(nonatomic) __weak UIImageView *verImageView; // @synthesize verImageView=_verImageView;
@property(nonatomic) __weak UIView *placeView; // @synthesize placeView=_placeView;
@property(nonatomic) __weak UITextField *phoneFiled; // @synthesize phoneFiled=_phoneFiled;
@property(nonatomic) __weak UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool isForgetPwd; // @synthesize isForgetPwd=_isForgetPwd;
- (void)setupGetAgain:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)backClick:(id)arg1;
- (void)pushToMain;
- (void)eyebtnClick:(id)arg1;
- (void)registNewUser;
- (void)modifyPwd;
- (void)nextBtnClick:(id)arg1;
- (void)changeImageCode;
- (void)getMsgCode:(id)arg1;
- (void)changePlace;
- (void)textfiledidChange:(id)arg1;
- (void)setupChacePlaceView;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)dealloc;
- (void)setupPhoneFiled;
- (void)setupImageVarCode;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

