//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSDictionary, NSString;

@interface FWSearchDetailinfo : MTLModel <MTLJSONSerializing>
{
    long long _agentid;
    NSString *_url;
    NSString *_searchDescription;
    NSString *_name;
    NSDictionary *_logo;
    NSString *_searchId;
    NSString *_tenant_corpid;
}

+ (id)JSONKeyPathsByPropertyKey;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *tenant_corpid; // @synthesize tenant_corpid=_tenant_corpid;
@property(copy, nonatomic) NSString *searchId; // @synthesize searchId=_searchId;
@property(retain, nonatomic) NSDictionary *logo; // @synthesize logo=_logo;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *searchDescription; // @synthesize searchDescription=_searchDescription;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long agentid; // @synthesize agentid=_agentid;

@end

