//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AMapLocationManagerDelegate-Protocol.h"
#import "CLLocationManagerDelegate-Protocol.h"

@class AMapLocationManager, AMapLocationReGeocode, CLLocation, CLLocationManager, FWTaskInfo, NSDate, NSString;
@protocol OS_dispatch_source;

@interface FWTaskManager : NSObject <AMapLocationManagerDelegate, CLLocationManagerDelegate>
{
    _Bool _isLogin;
    _Bool _isBackground;
    NSDate *_startTaskDate;
    FWTaskInfo *_taskInfo;
    CLLocation *_location;
    AMapLocationReGeocode *_regeocode;
    CLLocationManager *_cllocationManager;
    NSObject<OS_dispatch_source> *_timer;
    AMapLocationManager *_locationManager;
}

+ (id)manager;
- (void).cxx_destruct;
@property(retain, nonatomic) AMapLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) CLLocationManager *cllocationManager; // @synthesize cllocationManager=_cllocationManager;
@property(nonatomic) _Bool isBackground; // @synthesize isBackground=_isBackground;
@property(retain, nonatomic) AMapLocationReGeocode *regeocode; // @synthesize regeocode=_regeocode;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
@property(retain, nonatomic) FWTaskInfo *taskInfo; // @synthesize taskInfo=_taskInfo;
@property(retain, nonatomic) NSDate *startTaskDate; // @synthesize startTaskDate=_startTaskDate;
- (void)dealloc;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)getVersionWithKey:(id)arg1;
- (void)updateTaskData;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)handleActionWith:(int)arg1 actionSetting:(id)arg2 joinMeetingDict:(id)arg3;
- (void)reportData:(id)arg1;
- (void)postLocationData:(id)arg1 otherParam:(id)arg2 task:(id)arg3 reportType:(int)arg4;
- (void)readStepCount:(CDUnknownBlockType)arg1;
- (id)clientInfo;
- (void)invokeTask:(id)arg1 withOtherParam:(id)arg2 reportType:(int)arg3;
- (void)invokeTasksWithOpenLink;
- (void)invokeTasksWithSendMsg;
- (void)stopTasks;
- (void)startTasks:(id)arg1 isLogin:(_Bool)arg2 isBecomeActive:(_Bool)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

