//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FWConversationModel, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIButton, UIScrollView, UIView;

@interface FWTaskFocusDetailController : UIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isLoading;
    FWConversationModel *_conversation;
    NSArray *_titles;
    UIButton *_selBtn;
    UIView *_indicatorView;
    UIScrollView *_scrollView;
    NSMutableArray *_titleBtns;
    NSMutableArray *_tableViews;
    NSMutableArray *_nodataViews;
    UIButton *_backButton;
    NSMutableDictionary *_cacheDict;
    NSMutableDictionary *_cacheTimeDict;
    UIView *_topBgView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *topBgView; // @synthesize topBgView=_topBgView;
@property(retain, nonatomic) NSMutableDictionary *cacheTimeDict; // @synthesize cacheTimeDict=_cacheTimeDict;
@property(retain, nonatomic) NSMutableDictionary *cacheDict; // @synthesize cacheDict=_cacheDict;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) NSMutableArray *nodataViews; // @synthesize nodataViews=_nodataViews;
@property(retain, nonatomic) NSMutableArray *tableViews; // @synthesize tableViews=_tableViews;
@property(retain, nonatomic) NSMutableArray *titleBtns; // @synthesize titleBtns=_titleBtns;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) __weak UIButton *selBtn; // @synthesize selBtn=_selBtn;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) FWConversationModel *conversation; // @synthesize conversation=_conversation;
- (void)onConnectionStatusChangedNotification:(id)arg1;
- (void)didReceiveMessageNotification:(id)arg1;
- (id)getCellIdWithModel:(id)arg1;
- (id)getArrayWithTag:(long long)arg1;
- (void)reloadRowsAtIndexPathsWithModel:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)handelTabelViewWithTheme:(id)arg1 arry:(id)arg2;
- (void)laodNewDataWithTheme:(id)arg1 type:(id)arg2;
- (void)laodNewData;
- (void)loadMoreData:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2 WithCellId:(id)arg3 tableView:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupContentView;
- (id)setupNodataViewWithTag:(long long)arg1;
- (id)setupTabelViewWithTag:(long long)arg1;
- (void)topheadBtnClick:(id)arg1;
- (void)setupTopHeadView;
- (void)addTaskFocus;
- (void)back;
- (void)stupNavgation;
- (void)rcFoucsTaskTablere_ReloadData:(id)arg1;
- (void)clearUnread;
- (void)setupNotification;
- (void)autoLayoutTabelViewWithTag:(long long)arg1;
- (void)autoLayoutNodataViewWithTag:(long long)arg1;
- (void)taskFocusDetailVCLandScapeFit;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

