//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FWTabBar;

@protocol FWTabBarDelegate <NSObject>
- (_Bool)tabBar:(FWTabBar *)arg1 shouldSelectViewControllerInindex:(long long)arg2;
- (void)tabBar:(FWTabBar *)arg1 scrollToDistance:(double)arg2 status:(long long)arg3;

@optional
- (void)tabBar:(FWTabBar *)arg1 didClickButtonFromIndex:(long long)arg2 toIndex:(long long)arg3;
@end

