//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "FWUserInfoLoaderObserver-Protocol.h"

@class NSString, RCConversation, UIImageView, UILabel;

@interface FWTransportCell : UITableViewCell <FWUserInfoLoaderObserver>
{
    UIImageView *_headerView;
    UILabel *_titlLabel;
    UIImageView *_groupTypeImageView;
    RCConversation *_conversation;
    UIImageView *_secretImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *secretImageView; // @synthesize secretImageView=_secretImageView;
@property(retain, nonatomic) RCConversation *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) UIImageView *groupTypeImageView; // @synthesize groupTypeImageView=_groupTypeImageView;
@property(retain, nonatomic) UILabel *titlLabel; // @synthesize titlLabel=_titlLabel;
@property(retain, nonatomic) UIImageView *headerView; // @synthesize headerView=_headerView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)groupUserInfoFailToLoad:(id)arg1;
- (void)groupUserInfoDidLoad:(id)arg1;
- (void)userInfoFailToLoad:(id)arg1;
- (void)userInfoDidLoad:(id)arg1;
- (void)refreshSubViews:(id)arg1;
- (void)clearPreCellInfo;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

