//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class FWPersonModel, NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface FWUserCardController : UIViewController
{
    FWPersonModel *_personModel;
    UILabel *_qrcodeLabel;
    UILabel *_userName;
    UILabel *_descLabel;
    UIImageView *_userIconView;
    UIImageView *_codeImageView;
    UIView *_backView;
    NSLayoutConstraint *_erCodeImageH;
    NSLayoutConstraint *_ercodeImageW;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *ercodeImageW; // @synthesize ercodeImageW=_ercodeImageW;
@property(nonatomic) __weak NSLayoutConstraint *erCodeImageH; // @synthesize erCodeImageH=_erCodeImageH;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UIImageView *codeImageView; // @synthesize codeImageView=_codeImageView;
@property(nonatomic) __weak UIImageView *userIconView; // @synthesize userIconView=_userIconView;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UILabel *userName; // @synthesize userName=_userName;
@property(nonatomic) __weak UILabel *qrcodeLabel; // @synthesize qrcodeLabel=_qrcodeLabel;
@property(retain, nonatomic) FWPersonModel *personModel; // @synthesize personModel=_personModel;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidLayoutSubviews;
- (id)generateQRCode:(id)arg1 width:(double)arg2 height:(double)arg3;
- (void)setup;
- (void)setupDataWithDic:(id)arg1;
- (void)setuperCode;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

@end

