//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GMUtils : NSObject
{
}

+ (id)hexToData:(id)arg1;
+ (id)hexToString:(id)arg1;
+ (id)dataToHex:(id)arg1;
+ (id)stringToHex:(id)arg1;

@end

