//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError, NSString;

@protocol iAppOfficeDelegate <NSObject>
- (void)officeDidCloseWithError:(NSError *)arg1;
- (void)officeDidAbort;
- (void)officeDidFinished;
- (void)officeDidReceivedData:(NSDictionary *)arg1;

@optional
- (void)officeJoinSharePlayDidFailWithErrorMessage:(NSString *)arg1;
- (void)officeJoinSharePlayDidSuccess;
- (void)officeStartSharePlayDidFailWithErrorMessage:(NSString *)arg1;
- (void)officeStartSharePlayDidSuccessWithAccessCode:(NSString *)arg1 serverHost:(NSString *)arg2;
@end

