//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, iAppPDFView;

@protocol iAppPDFViewDelegate <NSObject>

@optional
- (void)iAppPDFView:(iAppPDFView *)arg1 didCancelInputPasswordWithButtonType:(long long)arg2;
- (_Bool)iAppPDFView:(iAppPDFView *)arg1 didClickedAnnotationWithInfo:(NSDictionary *)arg2;
- (void)iAppPDFView:(iAppPDFView *)arg1 didSelectedText:(NSString *)arg2 withStartPoint:(struct CGPoint)arg3 endPoint:(struct CGPoint)arg4;
- (_Bool)iAppPDFView:(iAppPDFView *)arg1 shouldSelectingTextAndThisPlaceHasAnnote:(_Bool)arg2;
- (double)iAppPDFView:(iAppPDFView *)arg1 fieldDidBeginEditingWithInfo:(NSDictionary *)arg2;
- (void)iAppPDFView:(iAppPDFView *)arg1 pageDidMoveWithInfo:(NSDictionary *)arg2;
- (void)iAppPDFView:(iAppPDFView *)arg1 annotationDidFinish:(_Bool)arg2 annotationType:(long long)arg3;
- (void)iAppPDFView:(iAppPDFView *)arg1 pageIndexDidChange:(unsigned long long)arg2;
@end

