//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KWOfficeApiDelegate-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString;
@protocol iAppOfficeDelegate;

@interface iAppOffice : NSObject <KWOfficeApiDelegate>
{
    _Bool _isAuthorized;
    _Bool _debugMode;
    unsigned long long _surplusDays;
    NSMutableDictionary *_PGFFileInfo;
    NSDictionary *_fileSecurityInfo;
    id <iAppOfficeDelegate> _delegate;
}

+ (id)messageInfoWithMessage:(id)arg1 componentsSeparated:(id)arg2 infoSeparated:(id)arg3;
+ (id)convertHexStrToData:(id)arg1;
+ (id)fileDataFromPGFFileInfo:(id)arg1;
+ (id)fileInfoWithPGFFileData:(id)arg1;
+ (_Bool)setApplicationDidEnterBackground:(id)arg1;
+ (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
+ (void)downloadWPS;
+ (_Bool)isAppStoreWPSInstalled;
+ (void)setWatermarkText:(id)arg1 colorWithRed:(double)arg2 green:(double)arg3 blue:(double)arg4 alpha:(double)arg5 type:(unsigned long long)arg6;
+ (void)setBackgroundMode:(_Bool)arg1;
+ (void)setPort:(long long)arg1;
+ (unsigned long long)checkCopyRightExpireDate;
+ (void)registerApp:(id)arg1 wpsKey:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)sharedInstance;
@property(nonatomic) __weak id <iAppOfficeDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSDictionary *fileSecurityInfo; // @synthesize fileSecurityInfo=_fileSecurityInfo;
@property(retain, nonatomic) NSMutableDictionary *PGFFileInfo; // @synthesize PGFFileInfo=_PGFFileInfo;
@property(nonatomic) unsigned long long surplusDays; // @synthesize surplusDays=_surplusDays;
@property(nonatomic, getter=isDebugMode) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) _Bool isAuthorized; // @synthesize isAuthorized=_isAuthorized;
- (void).cxx_destruct;
- (void)KWOfficeApiJoinSharePlayDidFailWithErrorMessage:(id)arg1;
- (void)KWOfficeApiJoinSharePlayDidSuccess;
- (void)KWOfficeApiStartSharePlayDidFailWithErrorMessage:(id)arg1;
- (void)KWOfficeApiStartSharePlayDidSuccessWithAccessCode:(id)arg1 serverHost:(id)arg2;
- (void)KWOfficeApiDidCloseWithError:(id)arg1;
- (void)KWOfficeApiDidAbort;
- (void)KWOfficeApiDidFinished;
- (void)KWOfficeApiDidReceiveData:(id)arg1;
- (void)showLog:(id)arg1;
- (id)AES256DecryptData:(id)arg1 withKey:(id)arg2;
- (id)AES256EncryptData:(id)arg1 withKey:(id)arg2;
- (_Bool)sendFileWithContentData:(id)arg1 fileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 securityInfo:(id)arg6 error:(id *)arg7;
- (_Bool)joinSharePlay:(id)arg1 serverHost:(id)arg2 callback:(id)arg3 delegate:(id)arg4 error:(id *)arg5;
- (_Bool)startSharePlay:(id)arg1 fileName:(id)arg2 serverHost:(id)arg3 callback:(id)arg4 securityInfo:(id)arg5 delegate:(id)arg6 error:(id *)arg7;
- (_Bool)startSharePlay:(id)arg1 withFileName:(id)arg2 serverHost:(id)arg3 callback:(id)arg4 delegate:(id)arg5 error:(id *)arg6;
- (void)sendFileData:(id)arg1 fileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 securityInfo:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)sendFileData:(id)arg1 fileName:(id)arg2 callback:(id)arg3 delegate:(id)arg4 policy:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (id)authorizedInfo;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

