//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDLFaceDetectionManager : NSObject
{
    _Bool _enableSound;
}

+ (id)sharedInstance;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(nonatomic) _Bool enableSound; // @synthesize enableSound=_enableSound;
- (void)reset;
- (void)startInitial;
- (void)detectMultiFacesImage:(id)arg1 withMaxFaceCount:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (void)detectStratrgyWithNormalImage:(id)arg1 previewRect:(struct CGRect)arg2 detectRect:(struct CGRect)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)detectStratrgyWithQualityControlImage:(id)arg1 previewRect:(struct CGRect)arg2 detectRect:(struct CGRect)arg3 completionHandler:(CDUnknownBlockType)arg4;

@end

