//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, NSURL, UIButton, UICollectionView, UIColor, UIFont, UIImage, UIViewController;

@interface IFMShareView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _showMiddleLine;
    _Bool _showBorderLine;
    _Bool _showCornerRadius;
    _Bool _showsHorizontalScrollIndicator;
    _Bool _showCancleButton;
    _Bool _oneLine;
    UIView *_headerView;
    UIView *_footerView;
    UIButton *_cancleButton;
    UIColor *_containViewColor;
    UIFont *_itemTitleFont;
    UIColor *_itemTitleColor;
    UIColor *_middleLineColor;
    double _itemImageTopSpace;
    double _iconAndTitleSpace;
    double _itemSpace;
    double _middleTopSpace;
    double _middleBottomSpace;
    double _middleLineEdgeSpace;
    NSArray *_shareItems;
    NSArray *_functionItems;
    UIView *_containView;
    UIView *_bodyView;
    UIView *_middleLine;
    UICollectionView *_shareCollectionView;
    UICollectionView *_functionCollectionView;
    unsigned long long _itemCountEveryRow;
    UIViewController *_presentVC;
    NSString *_shareText;
    UIImage *_shareImage;
    NSURL *_shareUrl;
    struct CGSize _itemSize;
    struct CGSize _itemImageSize;
    struct UIEdgeInsets _bodyViewEdgeInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) UIImage *shareImage; // @synthesize shareImage=_shareImage;
@property(retain, nonatomic) NSString *shareText; // @synthesize shareText=_shareText;
@property(nonatomic) __weak UIViewController *presentVC; // @synthesize presentVC=_presentVC;
@property(nonatomic) unsigned long long itemCountEveryRow; // @synthesize itemCountEveryRow=_itemCountEveryRow;
@property(nonatomic) _Bool oneLine; // @synthesize oneLine=_oneLine;
@property(nonatomic) __weak UICollectionView *functionCollectionView; // @synthesize functionCollectionView=_functionCollectionView;
@property(nonatomic) __weak UICollectionView *shareCollectionView; // @synthesize shareCollectionView=_shareCollectionView;
@property(retain, nonatomic) UIView *middleLine; // @synthesize middleLine=_middleLine;
@property(retain, nonatomic) UIView *bodyView; // @synthesize bodyView=_bodyView;
@property(retain, nonatomic) UIView *containView; // @synthesize containView=_containView;
@property(retain, nonatomic) NSArray *functionItems; // @synthesize functionItems=_functionItems;
@property(retain, nonatomic) NSArray *shareItems; // @synthesize shareItems=_shareItems;
@property(nonatomic) _Bool showCancleButton; // @synthesize showCancleButton=_showCancleButton;
@property(nonatomic) _Bool showsHorizontalScrollIndicator; // @synthesize showsHorizontalScrollIndicator=_showsHorizontalScrollIndicator;
@property(nonatomic) double middleLineEdgeSpace; // @synthesize middleLineEdgeSpace=_middleLineEdgeSpace;
@property(nonatomic) double middleBottomSpace; // @synthesize middleBottomSpace=_middleBottomSpace;
@property(nonatomic) double middleTopSpace; // @synthesize middleTopSpace=_middleTopSpace;
@property(nonatomic) double itemSpace; // @synthesize itemSpace=_itemSpace;
@property(nonatomic) double iconAndTitleSpace; // @synthesize iconAndTitleSpace=_iconAndTitleSpace;
@property(nonatomic) double itemImageTopSpace; // @synthesize itemImageTopSpace=_itemImageTopSpace;
@property(nonatomic) struct UIEdgeInsets bodyViewEdgeInsets; // @synthesize bodyViewEdgeInsets=_bodyViewEdgeInsets;
@property(nonatomic) _Bool showCornerRadius; // @synthesize showCornerRadius=_showCornerRadius;
@property(nonatomic) _Bool showBorderLine; // @synthesize showBorderLine=_showBorderLine;
@property(nonatomic) struct CGSize itemImageSize; // @synthesize itemImageSize=_itemImageSize;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) _Bool showMiddleLine; // @synthesize showMiddleLine=_showMiddleLine;
@property(retain, nonatomic) UIColor *middleLineColor; // @synthesize middleLineColor=_middleLineColor;
@property(retain, nonatomic) UIColor *itemTitleColor; // @synthesize itemTitleColor=_itemTitleColor;
@property(retain, nonatomic) UIFont *itemTitleFont; // @synthesize itemTitleFont=_itemTitleFont;
@property(retain, nonatomic) UIColor *containViewColor; // @synthesize containViewColor=_containViewColor;
@property(retain, nonatomic) UIButton *cancleButton; // @synthesize cancleButton=_cancleButton;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (void)showInView:(id)arg1;
- (void)tappedCancel;
- (void)maskViewClick:(id)arg1;
- (void)cancleButtonAction:(id)arg1;
- (void)layoutSubviews;
- (void)addURL:(id)arg1;
- (void)addImage:(id)arg1;
- (void)addText:(id)arg1;
- (void)dismiss:(_Bool)arg1;
- (void)showFromControlle:(id)arg1;
- (id)initWithItems:(id)arg1 countEveryRow:(long long)arg2;
- (id)initWithShareItems:(id)arg1 functionItems:(id)arg2 itemSize:(struct CGSize)arg3;
- (id)initWithItems:(id)arg1 itemSize:(struct CGSize)arg2 DisplayLine:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

