//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMYWebView, NSError, NSString, NSURLRequest, WKWebView;

@protocol IMYWebViewDelegate <NSObject>

@optional
- (void)webViewWebContentProcessDidTerminate:(WKWebView *)arg1;
- (void)webViewgoBackChanged:(IMYWebView *)arg1 canback:(_Bool)arg2;
- (void)webViewTitledidChanged:(IMYWebView *)arg1 title:(NSString *)arg2;
- (_Bool)webView:(IMYWebView *)arg1 shouldStartLoadWithRequest:(NSURLRequest *)arg2 navigationType:(long long)arg3;
- (void)webView:(IMYWebView *)arg1 didFailLoadWithError:(NSError *)arg2;
- (void)webViewDidFinishLoad:(IMYWebView *)arg1;
- (void)webViewDidStartLoad:(IMYWebView *)arg1;
@end

