//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JCOREMacAddressManager : NSObject
{
}

+ (unsigned int)IPv4Pton:(id)arg1;
+ (id)IPv4Ntop:(unsigned int)arg1;
+ (id)currentIPAddressOf:(id)arg1;
+ (void)getDeviceMacFromMDNS:(CDUnknownBlockType)arg1;

@end

