//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class JPushMessageConfig, NSString, NSURL, UIProgressView, WKWebView;
@protocol JPushInMessageWebViewControllerDelegate;

@interface JPushInMessageWebViewController : UIViewController <WKNavigationDelegate, WKUIDelegate>
{
    NSURL *_url;
    id <JPushInMessageWebViewControllerDelegate> _delegate;
    JPushMessageConfig *_config;
    WKWebView *_webView;
    UIProgressView *_progressView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) JPushMessageConfig *config; // @synthesize config=_config;
@property(nonatomic) __weak id <JPushInMessageWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)close;
- (void)initNavItem;
- (void)initView;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

