//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JPUSHMessage.h"

#import "JCORETcpReceiptProtocol-Protocol.h"

@class NSString;

@interface JPUSHMessageReceipt : JPUSHMessage <JCORETcpReceiptProtocol>
{
    unsigned short statusCode;
}

@property(nonatomic) unsigned short statusCode; // @synthesize statusCode;
- (id)initWith:(id)arg1;

// Remaining properties
@property(nonatomic) unsigned char algorithm;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned char protocolType;
@property(nonatomic) unsigned short rid;
@property(readonly) Class superclass;
@property(nonatomic) unsigned long long uid;
@property(nonatomic) unsigned char version;

@end

