//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class JPushMessageConfig, JPushWeakScriptMessageDelegate, NSLayoutConstraint, NSString, WKWebView;
@protocol JPushMessageViewDelegate;

@interface JPushMessageView : UIView <WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler, UIGestureRecognizerDelegate>
{
    _Bool _isShow;
    _Bool _isCallback;
    _Bool _isNetwork;
    JPushMessageConfig *_config;
    id <JPushMessageViewDelegate> _delegate;
    NSLayoutConstraint *_leftConstraint;
    NSLayoutConstraint *_rightConstraint;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_heightConstraint;
    NSLayoutConstraint *_bottomConstraint;
    WKWebView *_webView;
    JPushWeakScriptMessageDelegate *_messageDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isNetwork; // @synthesize isNetwork=_isNetwork;
@property(nonatomic) _Bool isCallback; // @synthesize isCallback=_isCallback;
@property(retain, nonatomic) JPushWeakScriptMessageDelegate *messageDelegate; // @synthesize messageDelegate=_messageDelegate;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(retain, nonatomic) NSLayoutConstraint *rightConstraint; // @synthesize rightConstraint=_rightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *leftConstraint; // @synthesize leftConstraint=_leftConstraint;
@property(nonatomic) __weak id <JPushMessageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) JPushMessageConfig *config; // @synthesize config=_config;
- (id)fileURLForBuggyWKWebView8WithFileURL:(id)arg1;
- (id)dicToData:(id)arg1;
- (id)dicToString:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)reportData:(id)arg1;
- (void)onLoadCallback:(id)arg1;
- (void)getTplData:(id)arg1;
- (void)inAppClick:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)removeScriptMessageHandler;
- (void)addScriptMessageHandler;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleTap:(id)arg1;
- (void)fadeMeout;
- (void)initGesture;
- (void)setView;
- (id)initWithFrame:(struct CGRect)arg1 WithConfig:(id)arg2 delegate:(id)arg3;
- (id)initWithConfig:(id)arg1 delegate:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

