//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor, UIImage;
@protocol OS_dispatch_queue;

@interface JRConfigTool : NSObject
{
    UIColor *_selectTitleColor;
    UIColor *_normalTitleColor;
    double _itemMargin;
    NSObject<OS_dispatch_queue> *_concurrentQueue;
    UIImage *_normalImage;
    UIImage *_failureImage;
    struct CGSize _itemSize;
}

+ (void)free;
+ (id)shareInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *failureImage; // @synthesize failureImage=_failureImage;
@property(retain, nonatomic) UIImage *normalImage; // @synthesize normalImage=_normalImage;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *concurrentQueue; // @synthesize concurrentQueue=_concurrentQueue;
@property(nonatomic) double itemMargin; // @synthesize itemMargin=_itemMargin;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(retain, nonatomic) UIColor *normalTitleColor; // @synthesize normalTitleColor=_normalTitleColor;
@property(retain, nonatomic) UIColor *selectTitleColor; // @synthesize selectTitleColor=_selectTitleColor;
- (void)_normalInit;
- (id)init;

@end

