//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRBaseCollectionViewCell.h"

@class UILabel;

@interface JRTitleCollectionViewCell : JRBaseCollectionViewCell
{
    UILabel *_label;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
- (void)_createCustomView;
- (void)showAnimationOfProgress:(double)arg1 select:(_Bool)arg2;
- (void)setCellData:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

