//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KGAlertView.h"

@class UIActivityIndicatorView, UIView;

@interface KGAlertProgressView : KGAlertView
{
    _Bool _initCustomView;
    long long _mode;
    UIView *_contentView;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (id)textModeView;
- (id)indicatorModeView;
- (void)showProgressViewWithMode:(long long)arg1;
- (void)initViews;
- (void)initDatas;
- (void)dismissAfterDelay:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithMode:(long long)arg1;
- (void)setActivateTouchBackground:(_Bool)arg1;

@end

