//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CAEAGLLayer, EAGLContext;
@protocol KGBrushGLRegionDelegate;

@interface KGBrushGLRegion : NSObject
{
    unsigned int renderbuffer;
    unsigned int framebuffer;
    unsigned int stencilBuffer;
    int width;
    int height;
    CAEAGLLayer *layer;
    id <KGBrushGLRegionDelegate> delegate;
    EAGLContext *context;
}

+ (id)regionWithContext:(id)arg1 andLayer:(id)arg2;
@property(nonatomic) __weak EAGLContext *context; // @synthesize context;
@property(nonatomic) __weak id <KGBrushGLRegionDelegate> delegate; // @synthesize delegate;
@property(nonatomic) int height; // @synthesize height;
@property(nonatomic) int width; // @synthesize width;
@property(nonatomic) unsigned int stencilBuffer; // @synthesize stencilBuffer;
@property(nonatomic) unsigned int framebuffer; // @synthesize framebuffer;
@property(nonatomic) unsigned int renderbuffer; // @synthesize renderbuffer;
@property(retain, nonatomic) CAEAGLLayer *layer; // @synthesize layer;
- (void).cxx_destruct;
- (void)present;
- (_Bool)resize;
- (void)freeGLResources;
- (void)dealloc;
- (id)initWithContext:(id)arg1 andLayer:(id)arg2;

@end

