//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class KGBrush, KGBrushColor, NSMutableArray;

@interface KGBrushPath : NSObject <NSCopying>
{
    NSMutableArray *nodes_;
    _Bool closed_;
    struct CGPath *pathRef_;
    struct CGRect bounds_;
    _Bool boundsDirty_;
    double remainder_;
    NSMutableArray *points_;
    NSMutableArray *sizes_;
    NSMutableArray *angles_;
    NSMutableArray *alphas_;
    _Bool limitBrushSize;
    int action;
    KGBrush *brush_;
    KGBrushColor *color_;
    double scale_;
    struct CGRect _strokeBounds;
}

+ (id)pathWithStart:(struct CGPoint)arg1 end:(struct CGPoint)arg2;
+ (id)pathWithOvalInRect:(struct CGRect)arg1;
+ (id)pathWithRect:(struct CGRect)arg1;
@property(nonatomic) struct CGRect strokeBounds; // @synthesize strokeBounds=_strokeBounds;
@property(nonatomic) double scale; // @synthesize scale=scale_;
@property(nonatomic) int action; // @synthesize action;
@property(nonatomic) double remainder; // @synthesize remainder=remainder_;
@property(nonatomic) _Bool limitBrushSize; // @synthesize limitBrushSize;
@property(retain, nonatomic) KGBrushColor *color; // @synthesize color=color_;
@property(retain, nonatomic) KGBrush *brush; // @synthesize brush=brush_;
@property(retain, nonatomic) NSMutableArray *nodes; // @synthesize nodes=nodes_;
@property(nonatomic) _Bool closed; // @synthesize closed=closed_;
- (void).cxx_destruct;
- (struct CGRect)paint:(id)arg1;
- (void)paintFromPoint:(id)arg1 toPoint:(id)arg2 randomizer:(id)arg3;
- (void)paintStamp:(id)arg1;
- (id)newRandomizer;
- (struct CGRect)drawData;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)flatten;
- (id)flattenedPoints;
- (void)addAnchors;
- (void)transform:(struct CGAffineTransform)arg1;
- (id)nodesInRect:(struct CGRect)arg1;
- (struct CGRect)controlBounds;
- (struct CGRect)bounds;
- (void)computeBounds;
- (void)invalidatePath;
- (id)lastNode;
- (id)firstNode;
- (void)addNode:(id)arg1;
- (void)setClosedQuiet:(_Bool)arg1;
- (id)initWithStart:(struct CGPoint)arg1 end:(struct CGPoint)arg2;
- (id)initWithOvalInRect:(struct CGRect)arg1;
- (id)initWithRect:(struct CGRect)arg1;
- (struct CGPath *)pathRef;
- (id)reversedNodes;
- (id)decodeLegacyNodesB:(id)arg1;
- (id)decodeLegacyNodesA:(id)arg1 v1:(_Bool)arg2;
- (void)dealloc;
- (id)initWithNode:(id)arg1;
- (id)init;

@end

