//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CAAnimationDelegate-Protocol.h"
#import "LFPhotoEditingControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class LFPhotoEditingController, NSMutableArray, NSMutableSet, NSString, RCConversation, UIButton, UIImage, UIImageView, UILabel, UIPageControl, UIScrollView;
@protocol KSImageManager, KSPhotoBrowserDelegate;

@interface KSPhotoBrowser : UIViewController <UIScrollViewDelegate, UIViewControllerTransitioningDelegate, CAAnimationDelegate, LFPhotoEditingControllerDelegate>
{
    struct CGPoint _startLocation;
    NSString *_scannedResult;
    _Bool _bounces;
    _Bool _showAllPhoto;
    _Bool _repostDisable;
    _Bool _presented;
    _Bool _beginAnimation;
    _Bool _isRotating;
    _Bool _canSave;
    unsigned long long _dismissalStyle;
    unsigned long long _backgroundStyle;
    unsigned long long _pageindicatorStyle;
    unsigned long long _loadingStyle;
    id <KSPhotoBrowserDelegate> _delegate;
    NSMutableArray *_imageDataArray;
    RCConversation *_conversation;
    CDUnknownBlockType _photoCallBack;
    UIScrollView *_scrollView;
    NSMutableArray *_photoItems;
    NSMutableSet *_reusableItemViews;
    NSMutableArray *_visibleItemViews;
    unsigned long long _currentPage;
    UIImageView *_backgroundView;
    UIPageControl *_pageControl;
    UILabel *_pageLabel;
    id <KSImageManager> _imageManager;
    UIViewController *_currentVC;
    UIButton *_allPhotoBtn;
    UIImage *_editedImage;
    LFPhotoEditingController *_lfPhotoEditVC;
}

+ (void)setImageManagerClass:(Class)arg1;
+ (id)browserWithPhotoItems:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) LFPhotoEditingController *lfPhotoEditVC; // @synthesize lfPhotoEditVC=_lfPhotoEditVC;
@property(retain, nonatomic) UIImage *editedImage; // @synthesize editedImage=_editedImage;
@property(nonatomic) _Bool canSave; // @synthesize canSave=_canSave;
@property(nonatomic) _Bool isRotating; // @synthesize isRotating=_isRotating;
@property(nonatomic) _Bool beginAnimation; // @synthesize beginAnimation=_beginAnimation;
@property(retain, nonatomic) UIButton *allPhotoBtn; // @synthesize allPhotoBtn=_allPhotoBtn;
@property(nonatomic) __weak UIViewController *currentVC; // @synthesize currentVC=_currentVC;
@property(retain, nonatomic) id <KSImageManager> imageManager; // @synthesize imageManager=_imageManager;
@property(nonatomic) _Bool presented; // @synthesize presented=_presented;
@property(retain, nonatomic) UILabel *pageLabel; // @synthesize pageLabel=_pageLabel;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSMutableArray *visibleItemViews; // @synthesize visibleItemViews=_visibleItemViews;
@property(retain, nonatomic) NSMutableSet *reusableItemViews; // @synthesize reusableItemViews=_reusableItemViews;
@property(retain, nonatomic) NSMutableArray *photoItems; // @synthesize photoItems=_photoItems;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool repostDisable; // @synthesize repostDisable=_repostDisable;
@property(copy, nonatomic) CDUnknownBlockType photoCallBack; // @synthesize photoCallBack=_photoCallBack;
@property(retain, nonatomic) RCConversation *conversation; // @synthesize conversation=_conversation;
@property(nonatomic) _Bool showAllPhoto; // @synthesize showAllPhoto=_showAllPhoto;
@property(retain, nonatomic) NSMutableArray *imageDataArray; // @synthesize imageDataArray=_imageDataArray;
@property(nonatomic) __weak id <KSPhotoBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool bounces; // @synthesize bounces=_bounces;
@property(nonatomic) unsigned long long loadingStyle; // @synthesize loadingStyle=_loadingStyle;
@property(nonatomic) unsigned long long pageindicatorStyle; // @synthesize pageindicatorStyle=_pageindicatorStyle;
@property(nonatomic) unsigned long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
@property(nonatomic) unsigned long long dismissalStyle; // @synthesize dismissalStyle=_dismissalStyle;
- (void)lf_PhotoEditingController:(id)arg1 didFinishPhotoEdit:(id)arg2;
- (void)lf_PhotoEditingControllerDidCancel:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)showSlideCompletionAnimationFromPoint:(struct CGPoint)arg1;
- (void)showDismissalAnimation;
- (void)showRotationCompletionAnimationFromPoint:(struct CGPoint)arg1;
- (void)showCancellationAnimation;
- (void)didPan:(id)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)savImageToPhotos:(id)arg1;
- (void)editImage:(id)arg1;
- (void)photoViewTranspond:(id)arg1;
- (void)QRReaderDidFinishRead:(id)arg1;
- (void)photoViewExtractQRcode:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didLongPress:(id)arg1;
- (void)didDoubleTap:(id)arg1;
- (void)didSingleTap:(id)arg1;
- (void)addGestureRecognizer;
- (void)handlePanBegin;
- (void)configPageLabelWithPage:(unsigned long long)arg1;
- (void)configPhotoView:(id)arg1 withItem:(id)arg2;
- (void)blurBackgroundWithImage:(id)arg1 animated:(_Bool)arg2;
- (id)screenshot;
- (void)performSlideWithPan:(id)arg1;
- (void)performScaleWithPan:(id)arg1;
- (void)performRotationWithPan:(id)arg1;
- (void)dismissAnimated:(_Bool)arg1;
- (void)configItemViews;
- (void)updateReusableItemViews;
- (id)dequeueReusableItemView;
- (id)photoViewForPage:(unsigned long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)setStatusBarHidden:(_Bool)arg1;
- (void)showFromViewController:(id)arg1;
- (void)allPhotoBtnClick:(id)arg1;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPhotoItems:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

