//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "KSImageManager-Protocol.h"

@class NSString;

@interface KSYYImageManager : NSObject <KSImageManager>
{
}

- (id)imageFromMemoryForURL:(id)arg1;
- (void)cancelImageRequestForImageView:(id)arg1;
- (void)setImageForImageView:(id)arg1 withURL:(id)arg2 placeholder:(id)arg3 progress:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

