//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LFResizeControl;

@protocol lf_resizeConrolDelegate <NSObject>
- (void)lf_resizeConrolDidEndResizing:(LFResizeControl *)arg1;
- (void)lf_resizeConrolDidResizing:(LFResizeControl *)arg1;
- (void)lf_resizeConrolDidBeginResizing:(LFResizeControl *)arg1;
@end

