//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAsset, AVAssetReader, AVAssetReaderOutput, AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, AVAudioMix, AVVideoComposition, NSArray, NSDictionary, NSError, NSString, NSURL;
@protocol LFAssetExportSessionDelegate, OS_dispatch_group, OS_dispatch_queue;

@interface LFAssetExportSession : NSObject
{
    NSObject<OS_dispatch_queue> *_audioQueue;
    NSObject<OS_dispatch_queue> *_videoQueue;
    NSObject<OS_dispatch_group> *_dispatchGroup;
    NSError *_error;
    double _totalDuration;
    CDStruct_1b6d18a9 lastSamplePresentationTime;
    _Bool _shouldOptimizeForNetworkUse;
    _Bool _cancelled;
    _Bool _needsLeaveAudio;
    _Bool _needsLeaveVideo;
    float _progress;
    int _videoOrientation;
    id <LFAssetExportSessionDelegate> _delegate;
    unsigned long long _preset;
    AVAsset *_asset;
    AVVideoComposition *_videoComposition;
    AVAudioMix *_audioMix;
    NSString *_outputFileType;
    NSURL *_outputURL;
    NSDictionary *_videoOutputSettings;
    NSDictionary *_videoSettings;
    NSDictionary *_audioSettings;
    NSArray *_metadata;
    AVAssetReader *_reader;
    AVAssetReaderOutput *_videoOutput;
    AVAssetReaderOutput *_audioOutput;
    AVAssetWriter *_writer;
    AVAssetWriterInput *_videoInput;
    AVAssetWriterInputPixelBufferAdaptor *_videoPixelBufferAdaptor;
    AVAssetWriterInput *_audioInput;
    CDUnknownBlockType _completionHandler;
    struct CGSize _inputBufferSize;
    CDStruct_e83c9415 _timeRange;
}

+ (id)exportSessionWithAsset:(id)arg1 preset:(unsigned long long)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) _Bool needsLeaveVideo; // @synthesize needsLeaveVideo=_needsLeaveVideo;
@property(nonatomic) _Bool needsLeaveAudio; // @synthesize needsLeaveAudio=_needsLeaveAudio;
@property(nonatomic) int videoOrientation; // @synthesize videoOrientation=_videoOrientation;
@property(nonatomic) struct CGSize inputBufferSize; // @synthesize inputBufferSize=_inputBufferSize;
@property(retain, nonatomic) AVAssetWriterInput *audioInput; // @synthesize audioInput=_audioInput;
@property(retain, nonatomic) AVAssetWriterInputPixelBufferAdaptor *videoPixelBufferAdaptor; // @synthesize videoPixelBufferAdaptor=_videoPixelBufferAdaptor;
@property(retain, nonatomic) AVAssetWriterInput *videoInput; // @synthesize videoInput=_videoInput;
@property(retain, nonatomic) AVAssetWriter *writer; // @synthesize writer=_writer;
@property(retain, nonatomic) AVAssetReaderOutput *audioOutput; // @synthesize audioOutput=_audioOutput;
@property(retain, nonatomic) AVAssetReaderOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain, nonatomic) AVAssetReader *reader; // @synthesize reader=_reader;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(readonly) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(copy, nonatomic) NSArray *metadata; // @synthesize metadata=_metadata;
@property(nonatomic) _Bool shouldOptimizeForNetworkUse; // @synthesize shouldOptimizeForNetworkUse=_shouldOptimizeForNetworkUse;
@property(nonatomic) CDStruct_e83c9415 timeRange; // @synthesize timeRange=_timeRange;
@property(copy, nonatomic) NSDictionary *audioSettings; // @synthesize audioSettings=_audioSettings;
@property(copy, nonatomic) NSDictionary *videoSettings; // @synthesize videoSettings=_videoSettings;
@property(copy, nonatomic) NSDictionary *videoOutputSettings; // @synthesize videoOutputSettings=_videoOutputSettings;
@property(copy, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(copy, nonatomic) NSString *outputFileType; // @synthesize outputFileType=_outputFileType;
@property(copy, nonatomic) AVAudioMix *audioMix; // @synthesize audioMix=_audioMix;
@property(copy, nonatomic) AVVideoComposition *videoComposition; // @synthesize videoComposition=_videoComposition;
@property(readonly, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(nonatomic) unsigned long long preset; // @synthesize preset=_preset;
@property(nonatomic) __weak id <LFAssetExportSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)reset;
- (void)_setProgress:(float)arg1;
- (void)cancelExport;
@property(readonly, nonatomic) long long status;
@property(readonly, nonatomic) NSError *error;
- (void)complete;
- (id)fixedCompositionWithAsset:(id)arg1;
- (id)buildDefaultVideoComposition;
- (void)_didAppendToInput:(id)arg1 atTime:(CDStruct_1b6d18a9)arg2;
- (void)_markInputComplete:(id)arg1 error:(id)arg2;
- (void)beginReadWriteOnVideo;
- (void)beginReadWriteOnAudio;
- (void)_setupVideoUsingTracks:(id)arg1;
- (void)_setupAudioUsingTracks:(id)arg1;
- (void)exportAsynchronouslyWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) float estimatedExportSize;
- (id)initWithAsset:(id)arg1 preset:(unsigned long long)arg2;
- (id)init;

@end

