//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LFClippingView;

@protocol LFClippingViewDelegate <NSObject>
- (void)lf_clippingViewDidEndDecelerating:(LFClippingView *)arg1;
- (void)lf_clippingViewWillBeginDragging:(LFClippingView *)arg1;
- (void)lf_clippingViewDidEndZooming:(LFClippingView *)arg1;
- (void)lf_clippingViewDidZoom:(LFClippingView *)arg1;
- (void (^)(struct CGRect))lf_clippingViewWillBeginZooming:(LFClippingView *)arg1;
@end

