//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFScrollView.h"

#import "LFEditingProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class LFZoomingView, NSDictionary, NSString, UIImage;
@protocol LFClippingViewDelegate, LFPhotoEditDelegate;

@interface LFClippingView : LFScrollView <UIScrollViewDelegate, LFEditingProtocol>
{
    _Bool _isReseting;
    _Bool _isRotating;
    _Bool _useGesture;
    UIImage *_image;
    id <LFClippingViewDelegate> _clippingDelegate;
    double _first_minimumZoomScale;
    LFZoomingView *_zoomingView;
    long long _angle;
    double _defaultMaximumZoomScale;
    double _old_zoomScale;
    double _old_minimumZoomScale;
    double _old_maximumZoomScale;
    struct CGPoint _offsetSuperCenter;
    struct CGSize _old_contentSize;
    struct CGPoint _old_contentOffset;
    struct CGRect _editRect;
    struct CGRect _cropRect;
    struct CGRect _normalRect;
    struct CGRect _saveRect;
    struct CGRect _old_frame;
    struct CGAffineTransform _old_transform;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGAffineTransform old_transform; // @synthesize old_transform=_old_transform;
@property(nonatomic) double old_maximumZoomScale; // @synthesize old_maximumZoomScale=_old_maximumZoomScale;
@property(nonatomic) double old_minimumZoomScale; // @synthesize old_minimumZoomScale=_old_minimumZoomScale;
@property(nonatomic) struct CGPoint old_contentOffset; // @synthesize old_contentOffset=_old_contentOffset;
@property(nonatomic) struct CGSize old_contentSize; // @synthesize old_contentSize=_old_contentSize;
@property(nonatomic) double old_zoomScale; // @synthesize old_zoomScale=_old_zoomScale;
@property(nonatomic) struct CGRect old_frame; // @synthesize old_frame=_old_frame;
@property(nonatomic) double defaultMaximumZoomScale; // @synthesize defaultMaximumZoomScale=_defaultMaximumZoomScale;
@property(nonatomic) long long angle; // @synthesize angle=_angle;
@property(nonatomic) struct CGRect saveRect; // @synthesize saveRect=_saveRect;
@property(nonatomic) struct CGRect normalRect; // @synthesize normalRect=_normalRect;
@property(nonatomic) __weak LFZoomingView *zoomingView; // @synthesize zoomingView=_zoomingView;
@property(nonatomic) _Bool useGesture; // @synthesize useGesture=_useGesture;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
@property(nonatomic) struct CGRect editRect; // @synthesize editRect=_editRect;
@property(readonly, nonatomic) _Bool isRotating; // @synthesize isRotating=_isRotating;
@property(readonly, nonatomic) _Bool isReseting; // @synthesize isReseting=_isReseting;
@property(nonatomic) struct CGPoint offsetSuperCenter; // @synthesize offsetSuperCenter=_offsetSuperCenter;
@property(nonatomic) double first_minimumZoomScale; // @synthesize first_minimumZoomScale=_first_minimumZoomScale;
@property(nonatomic) __weak id <LFClippingViewDelegate> clippingDelegate; // @synthesize clippingDelegate=_clippingDelegate;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSDictionary *photoEditData;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)touchesShouldCancelInContentView:(id)arg1;
- (_Bool)touchesShouldBegin:(id)arg1 withEvent:(id)arg2 inContentView:(id)arg3;
- (void)resetMinimumZoomScale;
- (void)transformRotate:(long long)arg1;
- (_Bool)verifyRect:(struct CGRect)arg1;
- (void)refreshImageZoomViewCenter;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)rotateClockwise:(_Bool)arg1;
- (void)zoomInToRect:(struct CGRect)arg1;
- (void)zoomOutToRect:(struct CGRect)arg1 completion:(CDUnknownBlockType)arg2;
- (void)zoomOutToRect:(struct CGRect)arg1;
- (struct CGRect)cappedCropRectInImageRectWithCropRect:(struct CGRect)arg1;
- (_Bool)canResetWithRect:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool canReset;
- (void)resetToRect:(struct CGRect)arg1;
- (void)reset;
- (void)cancel;
- (id)editOtherImagesInRect:(struct CGRect)arg1 rotate:(double)arg2;
- (void)setImage:(id)arg1 durations:(id)arg2;
- (void)dealloc;
- (void)customInit;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool drawCanUndo;
@property(nonatomic) _Bool drawEnable;
@property(nonatomic) __weak id <LFPhotoEditDelegate> editDelegate;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isDrawing;
@property(readonly, nonatomic) _Bool isSplashing;
@property(nonatomic) double screenScale;
@property(readonly, nonatomic) _Bool splashCanUndo;
@property(nonatomic) _Bool splashEnable;
@property(nonatomic) unsigned long long splashStateType;
@property(readonly, nonatomic) _Bool stickerEnable;
@property(nonatomic) double stickerMaxScale;
@property(nonatomic) double stickerMinScale;
@property(readonly) Class superclass;

@end

