//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFBrush.h"

@class CAShapeLayer, UIBezierPath, UIColor;

@interface LFPaintBrush : LFBrush
{
    UIColor *_lineColor;
    UIBezierPath *_path;
    CAShapeLayer *_layer;
}

+ (id)drawLayerWithTrackDict:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak CAShapeLayer *layer; // @synthesize layer=_layer;
@property(retain, nonatomic) UIBezierPath *path; // @synthesize path=_path;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
- (id)allTracks;
- (id)createDrawLayerWithPoint:(struct CGPoint)arg1;
- (void)addPoint:(struct CGPoint)arg1;
- (id)init;

@end

