//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LFText, LFTextBar;

@protocol LFTextBarDelegate <NSObject>
- (void)lf_textBarControllerDidReachMaximumLimit:(LFTextBar *)arg1;
- (void)lf_textBarControllerDidCancel:(LFTextBar *)arg1;
- (void)lf_textBarController:(LFTextBar *)arg1 didFinishText:(LFText *)arg2;
@end

