//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LFBaseEditingController.h"

#import "JRFilterBarDataSource-Protocol.h"
#import "JRFilterBarDelegate-Protocol.h"
#import "LFAudioTrackBarDelegate-Protocol.h"
#import "LFEditToolbarDelegate-Protocol.h"
#import "LFPhotoEditDelegate-Protocol.h"
#import "LFStickerBarDelegate-Protocol.h"
#import "LFTextBarDelegate-Protocol.h"
#import "LFVideoClipToolbarDelegate-Protocol.h"
#import "LFVideoEditingPlayerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class AVAsset, JRFilterBar, LFEditToolbar, LFStickerBar, LFVideoClipToolbar, LFVideoEditingView, NSArray, NSDictionary, NSString, UIImage, UITapGestureRecognizer, UIView;
@protocol LFVideoEditingControllerDelegate;

@interface LFVideoEditingController : LFBaseEditingController <LFEditToolbarDelegate, LFStickerBarDelegate, LFTextBarDelegate, JRFilterBarDelegate, JRFilterBarDataSource, LFAudioTrackBarDelegate, LFVideoClipToolbarDelegate, LFPhotoEditDelegate, UIGestureRecognizerDelegate, LFVideoEditingPlayerDelegate>
{
    LFVideoEditingView *_EditingView;
    UIView *_edit_naviBar;
    LFEditToolbar *_edit_toolBar;
    LFStickerBar *_edit_sticker_toolBar;
    JRFilterBar *_edit_filter_toolBar;
    LFVideoClipToolbar *_edit_clipping_toolBar;
    UITapGestureRecognizer *singleTapRecognizer;
    _Bool _isHideNaviBar;
    UIImage *_placeholderImage;
    AVAsset *_asset;
    unsigned long long _operationType;
    unsigned long long _defaultOperationType;
    NSDictionary *_operationAttrs;
    id <LFVideoEditingControllerDelegate> _delegate;
    double _minClippingDuration;
    NSArray *_defaultAudioUrls;
    NSString *_stickerPath;
    unsigned long long _initSelectedOperationType;
    CDUnknownBlockType _delayCancelBlock;
    UIImage *_filterSmallImage;
    NSDictionary *_editData;
    id _stickerBarCacheResource;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id stickerBarCacheResource; // @synthesize stickerBarCacheResource=_stickerBarCacheResource;
@property(retain, nonatomic) NSDictionary *editData; // @synthesize editData=_editData;
@property(retain, nonatomic) UIImage *filterSmallImage; // @synthesize filterSmallImage=_filterSmallImage;
@property(copy, nonatomic) CDUnknownBlockType delayCancelBlock; // @synthesize delayCancelBlock=_delayCancelBlock;
@property(nonatomic) unsigned long long initSelectedOperationType; // @synthesize initSelectedOperationType=_initSelectedOperationType;
@property(nonatomic) _Bool isHideNaviBar; // @synthesize isHideNaviBar=_isHideNaviBar;
@property(retain, nonatomic) NSString *stickerPath; // @synthesize stickerPath=_stickerPath;
@property(retain, nonatomic) NSArray *defaultAudioUrls; // @synthesize defaultAudioUrls=_defaultAudioUrls;
@property(nonatomic) double minClippingDuration; // @synthesize minClippingDuration=_minClippingDuration;
@property(nonatomic) __weak id <LFVideoEditingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *operationAttrs; // @synthesize operationAttrs=_operationAttrs;
@property(nonatomic) unsigned long long defaultOperationType; // @synthesize defaultOperationType=_defaultOperationType;
@property(nonatomic) unsigned long long operationType; // @synthesize operationType=_operationType;
@property(readonly, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(readonly, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
- (id)operationArrayURLForKey:(id)arg1;
- (id)operationArrayForKey:(id)arg1;
- (double)operationDoubleForKey:(id)arg1;
- (_Bool)operationBOOLForKey:(id)arg1;
- (unsigned long long)operationSubTypeForKey:(id)arg1;
- (id)jr_filterBarNameForEffectType:(long long)arg1;
- (id)jr_async_filterBarImageForEffectType:(long long)arg1;
- (void)jr_filterBar:(id)arg1 didSelectImage:(id)arg2 effectType:(long long)arg3;
- (id)edit_filter_toolBar;
- (id)edit_clipping_toolBar;
- (id)edit_sticker_toolBar;
- (void)changeFilterMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)showAudioTrackBar;
- (void)showTextBarController:(id)arg1;
- (void)changeStickerMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeClipMenu:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeClipMenu:(_Bool)arg1;
- (void)changedBarStateWithAnimated:(_Bool)arg1;
- (void)changedBarState;
- (void)lf_videoEditingViewFailedToPrepare:(id)arg1 error:(id)arg2;
- (void)lf_photoEditSplashEnded;
- (void)lf_photoEditSplashBegan;
- (void)lf_photoEditStickerDidSelectViewIsActive:(_Bool)arg1;
- (void)lf_photoEditDrawEnded;
- (void)lf_photoEditDrawBegan;
- (void)lf_videoClipToolbarDidFinish:(id)arg1;
- (void)lf_videoClipToolbarDidCancel:(id)arg1;
- (void)lf_audioTrackBarDidCancel:(id)arg1;
- (void)lf_audioTrackBar:(id)arg1 didFinishAudioUrls:(id)arg2;
- (void)lf_textBarControllerDidReachMaximumLimit:(id)arg1;
- (void)lf_textBarControllerDidCancel:(id)arg1;
- (void)lf_textBarController:(id)arg1 didFinishText:(id)arg2;
- (void)lf_stickerBar:(id)arg1 didSelectImage:(id)arg2;
- (void)lf_editToolbar:(id)arg1 rateDidChange:(float)arg2;
- (void)lf_editToolbar:(id)arg1 drawBrushDidChange:(id)arg2;
- (void)lf_editToolbar:(id)arg1 drawColorDidChange:(id)arg2;
- (_Bool)lf_editToolbar:(id)arg1 canRevokeAtIndex:(unsigned long long)arg2;
- (void)lf_editToolbar:(id)arg1 subDidSelectAtIndex:(id)arg2;
- (void)lf_editToolbar:(id)arg1 subDidRevokeAtIndex:(unsigned long long)arg2;
- (void)lf_editToolbar:(id)arg1 mainDidSelectAtIndex:(unsigned long long)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)finishButtonClick;
- (void)cancelButtonClick;
- (void)singlePressedWithAnimated:(_Bool)arg1;
- (void)singlePressed;
- (void)configUserGuide;
- (void)configDefaultOperation;
- (void)configBottomToolBar;
- (void)configCustomNaviBar;
- (void)configEditingView;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setVideoEdit:(id)arg1;
- (void)setVideoAsset:(id)arg1 placeholderImage:(id)arg2;
- (void)setVideoURL:(id)arg1 placeholderImage:(id)arg2;
- (id)initWithOrientation:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

