//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LFVideoClippingView, NSError;

@protocol LFVideoClippingViewDelegate <NSObject>
- (double)lf_videoClippingViewProgressWidth:(LFVideoClippingView *)arg1;
- (void)lf_videoClippingView:(LFVideoClippingView *)arg1 duration:(double)arg2;
- (void)lf_videoClippingViewFailedToPrepare:(LFVideoClippingView *)arg1 error:(NSError *)arg2;
- (void)lf_videoClippingViewReadyToPlay:(LFVideoClippingView *)arg1;

@optional
- (void)lf_videoClippingViewPlayToEndTime:(LFVideoClippingView *)arg1;
- (void)lf_videoClippingViewPause:(LFVideoClippingView *)arg1;
- (void)lf_videoClippingViewPlay:(LFVideoClippingView *)arg1;
@end

