//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class LJBirthday, NSArray, NSData, NSDate, NSString, UIImage;

@interface LJPerson : NSObject <NSCoding>
{
    _Bool _selected;
    unsigned long long _priority;
    unsigned long long _contactType;
    NSString *_fullName;
    NSString *_fullNamePinyin;
    NSString *_fullNameSimplePinyin;
    NSString *_familyName;
    NSString *_givenName;
    NSString *_namePrefix;
    NSString *_nameSuffix;
    NSString *_nickname;
    NSString *_middleName;
    NSString *_organizationName;
    NSString *_departmentName;
    NSString *_jobTitle;
    NSString *_note;
    NSString *_phoneticGivenName;
    NSString *_phoneticMiddleName;
    NSString *_phoneticFamilyName;
    NSData *_imageData;
    UIImage *_image;
    NSData *_thumbnailImageData;
    UIImage *_thumbnailImage;
    NSDate *_creationDate;
    NSDate *_modificationDate;
    NSArray *_phones;
    NSArray *_emails;
    NSArray *_addresses;
    LJBirthday *_birthday;
    NSArray *_messages;
    NSArray *_socials;
    NSArray *_relations;
    NSArray *_urls;
    struct _NSRange _hilightNameLocation;
    struct _NSRange _hilightNumberLocation;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *urls; // @synthesize urls=_urls;
@property(copy, nonatomic) NSArray *relations; // @synthesize relations=_relations;
@property(copy, nonatomic) NSArray *socials; // @synthesize socials=_socials;
@property(copy, nonatomic) NSArray *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) LJBirthday *birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSArray *addresses; // @synthesize addresses=_addresses;
@property(copy, nonatomic) NSArray *emails; // @synthesize emails=_emails;
@property(copy, nonatomic) NSArray *phones; // @synthesize phones=_phones;
@property(retain, nonatomic) NSDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(copy, nonatomic) NSData *thumbnailImageData; // @synthesize thumbnailImageData=_thumbnailImageData;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(copy, nonatomic) NSString *phoneticFamilyName; // @synthesize phoneticFamilyName=_phoneticFamilyName;
@property(copy, nonatomic) NSString *phoneticMiddleName; // @synthesize phoneticMiddleName=_phoneticMiddleName;
@property(copy, nonatomic) NSString *phoneticGivenName; // @synthesize phoneticGivenName=_phoneticGivenName;
@property(copy, nonatomic) NSString *note; // @synthesize note=_note;
@property(copy, nonatomic) NSString *jobTitle; // @synthesize jobTitle=_jobTitle;
@property(copy, nonatomic) NSString *departmentName; // @synthesize departmentName=_departmentName;
@property(copy, nonatomic) NSString *organizationName; // @synthesize organizationName=_organizationName;
@property(copy, nonatomic) NSString *middleName; // @synthesize middleName=_middleName;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *nameSuffix; // @synthesize nameSuffix=_nameSuffix;
@property(copy, nonatomic) NSString *namePrefix; // @synthesize namePrefix=_namePrefix;
@property(copy, nonatomic) NSString *givenName; // @synthesize givenName=_givenName;
@property(copy, nonatomic) NSString *familyName; // @synthesize familyName=_familyName;
@property(copy, nonatomic) NSString *fullNameSimplePinyin; // @synthesize fullNameSimplePinyin=_fullNameSimplePinyin;
@property(copy, nonatomic) NSString *fullNamePinyin; // @synthesize fullNamePinyin=_fullNamePinyin;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(nonatomic) unsigned long long contactType; // @synthesize contactType=_contactType;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(nonatomic) struct _NSRange hilightNumberLocation; // @synthesize hilightNumberLocation=_hilightNumberLocation;
@property(nonatomic) struct _NSRange hilightNameLocation; // @synthesize hilightNameLocation=_hilightNameLocation;
- (id)propertyKeys;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRecord:(void *)arg1;
- (id)initWithCNContact:(id)arg1;

@end

