//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MQPJSBridgeURLHandler-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"

@class APayH5WapViewToolbar, MQPWKJSBridge, MQPWebProgress, MQPWebService, MQPWebView, NSMutableURLRequest, NSString;

@interface MQPWebVC : UIViewController <WKNavigationDelegate, MQPJSBridgeURLHandler, UIScrollViewDelegate>
{
    _Bool _isScrolling;
    _Bool _isEnding;
    MQPWebProgress *_progress;
    NSMutableURLRequest *_urlReqest;
    APayH5WapViewToolbar *_toolbar;
    MQPWebService *_service;
    MQPWebView *_webView;
    MQPWKJSBridge *_jsBridge;
}

@property(retain, nonatomic) MQPWKJSBridge *jsBridge; // @synthesize jsBridge=_jsBridge;
@property(retain, nonatomic) MQPWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak MQPWebService *service; // @synthesize service=_service;
- (void).cxx_destruct;
- (double)safeAreaHeight;
- (id)imageViewWithImageName:(id)arg1;
- (id)labelWithFrame:(struct CGRect)arg1 isbold:(_Bool)arg2 size:(double)arg3 text:(id)arg4;
- (void)setupNaviBar4VC:(id)arg1 left:(id)arg2 title:(id)arg3 right:(id)arg4;
- (id)leftItem:(_Bool)arg1 text:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)rotateAccordingToStatusBarOrientationAndSupportedOrientations;
- (void)statusBarFrameOrOrientationChanged:(id)arg1;
- (void)pushWnd:(id)arg1;
- (void)hideToolbar;
- (void)showToolbar;
- (void)showRefreshButton:(_Bool)arg1;
- (void)showBackButton:(_Bool)arg1;
- (void)onExitWithResult:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)refresh;
- (void)back;
- (void)onWebErr:(id)arg1 log:(id)arg2;
- (void)onAction:(id)arg1;
- (id)subStrInStr:(id)arg1 between:(id)arg2 and:(id)arg3;
- (id)dictionaryFromString:(id)arg1;
- (void)onCallNativeFunc:(id)arg1;
- (void)loadJSBridge:(CDUnknownBlockType)arg1;
- (_Bool)onJSBridgeURLHandler:(id)arg1;
- (id)resultDicWithQuery:(id)arg1;
- (void)onH5PayWithError:(id)arg1;
- (_Bool)onH5PayHandler:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)parseTitleFromDocument;
- (void)notifyPagefinish;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)doClickNaviRightAction:(id)arg1;
- (void)doClickNaviLeftAction:(id)arg1;
- (void)h5BackV1;
- (void)h5BackV2;
- (void)setupWebView;
- (_Bool)openWithUrl:(id)arg1 method:(id)arg2 title:(id)arg3 h5mode:(long long)arg4;
- (void)setupSDKUserAgent;
- (void)dealloc;
- (id)initWithWebService:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

