//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CropViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class CropView, NSString, PhotoContentView, PhotoScrollView, UIButton, UIImage, UISlider;

@interface PhotoTweakView : UIView <UIScrollViewDelegate, CropViewDelegate>
{
    _Bool _manualZoomed;
    double _angle;
    CropView *_cropView;
    PhotoContentView *_photoContentView;
    UISlider *_slider;
    UIButton *_resetBtn;
    PhotoScrollView *_scrollView;
    UIImage *_image;
    UIView *_topMask;
    UIView *_leftMask;
    UIView *_bottomMask;
    UIView *_rightMask;
    double _centerY;
    double _maxRotationAngle;
    struct CGPoint _photoContentOffset;
    struct CGSize _originalSize;
    struct CGSize _maximumCanvasSize;
    struct CGPoint _originalPoint;
}

- (void).cxx_destruct;
@property(nonatomic) double maxRotationAngle; // @synthesize maxRotationAngle=_maxRotationAngle;
@property(nonatomic) struct CGPoint originalPoint; // @synthesize originalPoint=_originalPoint;
@property(nonatomic) double centerY; // @synthesize centerY=_centerY;
@property(nonatomic) struct CGSize maximumCanvasSize; // @synthesize maximumCanvasSize=_maximumCanvasSize;
@property(retain, nonatomic) UIView *rightMask; // @synthesize rightMask=_rightMask;
@property(retain, nonatomic) UIView *bottomMask; // @synthesize bottomMask=_bottomMask;
@property(retain, nonatomic) UIView *leftMask; // @synthesize leftMask=_leftMask;
@property(retain, nonatomic) UIView *topMask; // @synthesize topMask=_topMask;
@property(nonatomic) _Bool manualZoomed; // @synthesize manualZoomed=_manualZoomed;
@property(nonatomic) struct CGSize originalSize; // @synthesize originalSize=_originalSize;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) PhotoScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIButton *resetBtn; // @synthesize resetBtn=_resetBtn;
@property(retain, nonatomic) UISlider *slider; // @synthesize slider=_slider;
@property(readonly, nonatomic) PhotoContentView *photoContentView; // @synthesize photoContentView=_photoContentView;
@property(retain, nonatomic) CropView *cropView; // @synthesize cropView=_cropView;
@property(readonly, nonatomic) struct CGPoint photoContentOffset; // @synthesize photoContentOffset=_photoContentOffset;
@property(nonatomic) double angle; // @synthesize angle=_angle;
- (struct CGPoint)photoTranslation;
- (void)resetBtnTapped:(id)arg1;
- (void)sliderTouchEnded:(id)arg1;
- (void)sliderValueChanged:(id)arg1;
- (void)checkScrollViewContentOffset;
- (void)updateMasks:(_Bool)arg1;
- (void)cropEnded:(id)arg1;
- (void)cropMoved:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (id)viewForZoomingInScrollView:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2 maxRotationAngle:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

