//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GLKit/GLKView.h>

@class EAGLContext, GLKBaseEffect, NSMutableArray, UIColor, UIImage;

@interface PPSSignatureView : GLKView
{
    NSMutableArray *pointsArray;
    NSMutableArray *pathsArray;
    NSMutableArray *colorsArray;
    NSMutableArray *sizesArray;
    EAGLContext *context;
    GLKBaseEffect *effect;
    unsigned int vertexArray;
    unsigned int vertexBuffer;
    unsigned int dotsArray;
    unsigned int dotsBuffer;
    void *data;
    struct PPSSignaturePoint SignatureVertexData[100000];
    unsigned int length;
    struct PPSSignaturePoint SignatureDotsData[100000];
    unsigned int dotsLength;
    float penThickness;
    float previousThickness;
    struct CGPoint previousPoint;
    struct CGPoint previousMidPoint;
    struct PPSSignaturePoint previousVertex;
    struct PPSSignaturePoint currentVelocity;
    _Bool _hasSignature;
    int _currentPath;
    UIColor *_strokeColor;
    UIImage *_signatureImage;
    long long _width;
    union _GLKVector3 _penColor;
}

- (void).cxx_destruct;
@property(nonatomic) union _GLKVector3 penColor; // @synthesize penColor=_penColor;
@property(nonatomic) int currentPath; // @synthesize currentPath=_currentPath;
@property(nonatomic) long long width; // @synthesize width=_width;
@property(retain, nonatomic) UIImage *signatureImage; // @synthesize signatureImage=_signatureImage;
@property(nonatomic) _Bool hasSignature; // @synthesize hasSignature=_hasSignature;
@property(nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
- (void)tearDownGL;
- (void)addTriangleStripPointsForPrevious:(struct PPSSignaturePoint)arg1 next:(struct PPSSignaturePoint)arg2;
- (void)setupGL;
- (void)bindShaderAttributes;
- (void)setBackgroundColor:(id)arg1;
- (void)updateStrokeColor;
- (void)pan:(id)arg1;
- (void)longPress:(id)arg1;
- (void)tap:(id)arg1;
- (void)remove;
- (void)erase;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 context:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;

@end

