//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, QYSBluetoothSealBatteryBar, UILabel;

@interface QYSBluetoothSealBatteryView : UIView
{
    unsigned long long _style;
    unsigned long long _batteryValue;
    QYSBluetoothSealBatteryBar *_bar;
    UILabel *_textLabel;
    NSLayoutConstraint *_textW;
    NSLayoutConstraint *_viewW;
    NSLayoutConstraint *_viewH;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *viewH; // @synthesize viewH=_viewH;
@property(retain, nonatomic) NSLayoutConstraint *viewW; // @synthesize viewW=_viewW;
@property(retain, nonatomic) NSLayoutConstraint *textW; // @synthesize textW=_textW;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) QYSBluetoothSealBatteryBar *bar; // @synthesize bar=_bar;
@property(nonatomic) unsigned long long batteryValue; // @synthesize batteryValue=_batteryValue;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void)drawRect:(struct CGRect)arg1;
- (id)displayColor;
- (void)setStyle:(unsigned long long)arg1 withValue:(unsigned long long)arg2;
- (id)init;

@end

