//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint;

@interface QYSBluetoothSealProgressBar : UIView
{
    double _progress;
    UIView *_grayContainer;
    UIView *_blueBar;
    NSLayoutConstraint *_blueWidth;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *blueWidth; // @synthesize blueWidth=_blueWidth;
@property(retain, nonatomic) UIView *blueBar; // @synthesize blueBar=_blueBar;
@property(retain, nonatomic) UIView *grayContainer; // @synthesize grayContainer=_grayContainer;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void)initSubviews;
- (id)init;

@end

