//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCoordinateTool : NSObject
{
}

+ (id)transPoint:(id)arg1 fromInSize:(struct CGSize)arg2 toInSize:(struct CGSize)arg3;
+ (struct CGPoint)transAnch:(struct CGPoint)arg1 inSonRect:(struct CGRect)arg2 toFatherSize:(struct CGSize)arg3;
+ (void)setAnchorPoint:(struct CGPoint)arg1 forView:(id)arg2;
+ (void)setFrame:(struct CGRect)arg1 forView:(id)arg2;
+ (struct CGRect)getFrame:(id)arg1;
+ (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromInSize:(struct CGSize)arg2 toInSize:(struct CGSize)arg3;
+ (struct CGRect)converRect:(struct CGRect)arg1 fromInSize:(struct CGSize)arg2 toInSize:(struct CGSize)arg3;
+ (struct CGSize)sizeWithHypo:(double)arg1 whScale:(double)arg2;
+ (struct CGSize)scaleAddSizeWithSignSize:(struct CGSize)arg1 addSize:(struct CGSize)arg2;
+ (struct CGPoint)rotatePoint:(struct CGPoint)arg1 rotateCenter:(struct CGPoint)arg2 trans:(struct CGAffineTransform)arg3;
+ (id)transPoint:(id)arg1 rotateCo:(struct CGPoint)arg2 to:(struct CGSize)arg3 from:(struct CGRect)arg4 bornRect:(struct CGSize)arg5 trans:(struct CGAffineTransform)arg6;

@end

