//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RCPubNoticeMsgTool : NSObject
{
}

+ (_Bool)updateTableWithPublicNoticeModel:(id)arg1;
+ (id)getUnreadModelWithTargetid:(id)arg1;
+ (id)getModelWithTargetid:(id)arg1;
+ (_Bool)removeAllPublicNoticeModelWithTargetid:(id)arg1;
+ (_Bool)insertPublicNoticeModel:(id)arg1;
+ (void)closeDataBase;
+ (void)createDBWithPath:(id)arg1;
+ (void)changePersonWithPath:(id)arg1;

@end

