//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UILabel;
@protocol ReaderBottomOverlayTipViewDelegate;

@interface ReaderBottomOverlayTipView : UIView
{
    id <ReaderBottomOverlayTipViewDelegate> _delegate;
    NSString *_tipString;
    UILabel *_tipLabel;
    UIButton *_closeButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(copy, nonatomic) NSString *tipString; // @synthesize tipString=_tipString;
@property(nonatomic) __weak id <ReaderBottomOverlayTipViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)closeButtonClick;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

