//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol ReaderBottomToolBarDelegate;

@interface ReaderBottomToolBar : UIView
{
    id <ReaderBottomToolBarDelegate> _delegate;
    UIButton *_pictureButton;
    UIButton *_moreButton;
    UIButton *_backButton;
    UIButton *_writeButton;
    UIButton *_eraserButton;
    UIButton *_signButton;
    UIButton *_dateButton;
    UIButton *_saveButton;
    UIButton *_textButton;
    UIButton *_handWriteButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *handWriteButton; // @synthesize handWriteButton=_handWriteButton;
@property(retain, nonatomic) UIButton *textButton; // @synthesize textButton=_textButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIButton *dateButton; // @synthesize dateButton=_dateButton;
@property(retain, nonatomic) UIButton *signButton; // @synthesize signButton=_signButton;
@property(retain, nonatomic) UIButton *eraserButton; // @synthesize eraserButton=_eraserButton;
@property(retain, nonatomic) UIButton *writeButton; // @synthesize writeButton=_writeButton;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIButton *moreButton; // @synthesize moreButton=_moreButton;
@property(retain, nonatomic) UIButton *pictureButton; // @synthesize pictureButton=_pictureButton;
@property(nonatomic) __weak id <ReaderBottomToolBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void)verticalCenterButtonTitleAndImageWithButton:(id)arg1;
- (id)customButton:(id)arg1 withImage:(id)arg2 withTitle:(id)arg3;
- (void)handWriteClickAction;
- (void)moreButtonClickAction:(id)arg1;
- (void)pictureButtonClickAction;
- (void)textButtonClickAction;
- (void)signButtonAction;
- (void)writeButtonAction;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

