//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;
@protocol ReaderWriteStateBottomViewDelegate;

@interface ReaderWriteStateBottomView : UIView
{
    id <ReaderWriteStateBottomViewDelegate> _delegate;
    UIButton *_confirmButton;
    UIButton *_writeButton;
    UIButton *_eraserButton;
    UIButton *_clearButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *clearButton; // @synthesize clearButton=_clearButton;
@property(retain, nonatomic) UIButton *eraserButton; // @synthesize eraserButton=_eraserButton;
@property(retain, nonatomic) UIButton *writeButton; // @synthesize writeButton=_writeButton;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(nonatomic) __weak id <ReaderWriteStateBottomViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)clearButtonClick:(id)arg1;
- (void)eraserButtonClick:(id)arg1;
- (void)writeButtonClick:(id)arg1;
- (void)confirmButtonClick;
- (void)resetState;
- (void)selectWriteState;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

