//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CreateSealDelegate-Protocol.h"
#import "RSealTempletChooseControlProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WSBottomToolEditBarDelegate-Protocol.h"

@class NSIndexPath, NSMutableArray, NSString, UIButton, UICollectionView, WSBottomToolEditBar;
@protocol RSealTempletChooseControlProtocol;

@interface RSealTempletChooseControl : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, RSealTempletChooseControlProtocol, WSBottomToolEditBarDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, CreateSealDelegate>
{
    _Bool _isCustom;
    _Bool _isManagementState;
    int _chooseType;
    id <RSealTempletChooseControlProtocol> _insertSealDelegate;
    NSMutableArray *_SealTempletArray;
    NSMutableArray *_multiSelectedIndexPaths;
    NSMutableArray *_selectArr;
    UICollectionView *_collectionView;
    UIButton *_sureButton;
    UIButton *_backB;
    unsigned long long _buttonState;
    WSBottomToolEditBar *_editBar;
    NSIndexPath *_singleIndexPath;
}

- (void).cxx_destruct;
@property(nonatomic) int chooseType; // @synthesize chooseType=_chooseType;
@property(retain, nonatomic) NSIndexPath *singleIndexPath; // @synthesize singleIndexPath=_singleIndexPath;
@property(retain, nonatomic) WSBottomToolEditBar *editBar; // @synthesize editBar=_editBar;
@property(nonatomic) _Bool isManagementState; // @synthesize isManagementState=_isManagementState;
@property(nonatomic) unsigned long long buttonState; // @synthesize buttonState=_buttonState;
@property(retain, nonatomic) UIButton *backB; // @synthesize backB=_backB;
@property(retain, nonatomic) UIButton *sureButton; // @synthesize sureButton=_sureButton;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSMutableArray *selectArr; // @synthesize selectArr=_selectArr;
@property(retain, nonatomic) NSMutableArray *multiSelectedIndexPaths; // @synthesize multiSelectedIndexPaths=_multiSelectedIndexPaths;
@property(retain, nonatomic) NSMutableArray *SealTempletArray; // @synthesize SealTempletArray=_SealTempletArray;
@property(nonatomic) _Bool isCustom; // @synthesize isCustom=_isCustom;
@property(nonatomic) __weak id <RSealTempletChooseControlProtocol> insertSealDelegate; // @synthesize insertSealDelegate=_insertSealDelegate;
- (void)WS_Method_reloadData;
- (void)WS_Method_bottomToolEditBardeleteButtonClickAction;
- (void)selectAllButtonClickAction;
- (_Bool)isSelectAllItems;
- (void)editBarHidden;
- (void)editBarShow;
- (void)WS_Method_createSealDidFinishedWith:(id)arg1 withPath:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)openUIImagePickerController;
- (void)enterPhotoLibraryButtonClickAction;
- (void)takePhotoButtonClickAction;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)returnClick;
- (void)deleteSeal:(id)arg1;
- (void)insertSealAction;
- (void)initUI;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

