//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, SPTextView, UIImageView, UILabel;

@interface SendAlertView : UIView <UITextViewDelegate>
{
    NSString *_contentMsg;
    NSString *_replyString;
    CDUnknownBlockType _keyboardWillShow;
    CDUnknownBlockType _textViewHeightDidChange;
    CDUnknownBlockType _textViewDidEndEditting;
    UILabel *_sendtoLabel;
    UIImageView *_userIconView;
    UILabel *_nameLabel;
    UILabel *_contentLabel;
    UIImageView *_groupSecretImageView;
    SPTextView *_textView;
    NSLayoutConstraint *_contentHeightConstraint;
    NSLayoutConstraint *_textViewHeightConstraint;
    double _textH;
}

+ (id)shareSendAlertView;
- (void).cxx_destruct;
@property(nonatomic) double textH; // @synthesize textH=_textH;
@property(nonatomic) __weak NSLayoutConstraint *textViewHeightConstraint; // @synthesize textViewHeightConstraint=_textViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contentHeightConstraint; // @synthesize contentHeightConstraint=_contentHeightConstraint;
@property(nonatomic) __weak SPTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIImageView *groupSecretImageView; // @synthesize groupSecretImageView=_groupSecretImageView;
@property(nonatomic) __weak UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIImageView *userIconView; // @synthesize userIconView=_userIconView;
@property(nonatomic) __weak UILabel *sendtoLabel; // @synthesize sendtoLabel=_sendtoLabel;
@property(copy, nonatomic) CDUnknownBlockType textViewDidEndEditting; // @synthesize textViewDidEndEditting=_textViewDidEndEditting;
@property(copy, nonatomic) CDUnknownBlockType textViewHeightDidChange; // @synthesize textViewHeightDidChange=_textViewHeightDidChange;
@property(copy, nonatomic) CDUnknownBlockType keyboardWillShow; // @synthesize keyboardWillShow=_keyboardWillShow;
@property(copy, nonatomic) NSString *replyString; // @synthesize replyString=_replyString;
@property(copy, nonatomic) NSString *contentMsg; // @synthesize contentMsg=_contentMsg;
- (void)dealloc;
- (void)keyboardWillShow:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)setConversation:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

