//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSNumber, NSString;

@interface SignerInformationJSONModel : NSObject
{
    _Bool _isSelected;
    _Bool _isRefresh;
    NSString *_signerID;
    NSString *_signerName;
    NSString *_Desc;
    NSNumber *_pageNum;
    NSNumber *_type;
    NSDictionary *_signPosition;
    NSString *_signDate;
    NSNumber *_samePageIndex;
    struct CGRect _signRectInPDF;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) NSNumber *samePageIndex; // @synthesize samePageIndex=_samePageIndex;
@property(nonatomic) struct CGRect signRectInPDF; // @synthesize signRectInPDF=_signRectInPDF;
@property(retain, nonatomic) NSString *signDate; // @synthesize signDate=_signDate;
@property(retain, nonatomic) NSDictionary *signPosition; // @synthesize signPosition=_signPosition;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *pageNum; // @synthesize pageNum=_pageNum;
@property(retain, nonatomic) NSString *Desc; // @synthesize Desc=_Desc;
@property(retain, nonatomic) NSString *signerName; // @synthesize signerName=_signerName;
@property(retain, nonatomic) NSString *signerID; // @synthesize signerID=_signerID;
- (id)getBase64JSONData;

@end

