//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol SPDropItemProtocol <NSObject>
@property(copy, nonatomic) CDUnknownBlockType longPressHandler;
@property(copy, nonatomic) CDUnknownBlockType doubleTapHandler;
@property(copy, nonatomic) CDUnknownBlockType tapHandler;
@property(nonatomic, getter=isSelected) _Bool selected;
@property(readonly, nonatomic) UIView *displayView;
@end

