//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString, UIColor;

@interface TextData : NSObject
{
    _Bool _isDate;
    NSMutableDictionary *_textDataDict;
    NSString *_text;
    long long _textAlignment;
    double _fontSize;
    NSString *_fontName;
    UIColor *_textColor;
    double _textDegree;
    double _editTime;
    NSString *_ownerName;
    long long _ownerUid;
    NSString *_desc;
    struct CGPoint _centerRotateInPdf;
    struct CGRect _frameInPDF;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) long long ownerUid; // @synthesize ownerUid=_ownerUid;
@property(retain, nonatomic) NSString *ownerName; // @synthesize ownerName=_ownerName;
@property(nonatomic) double editTime; // @synthesize editTime=_editTime;
@property(nonatomic) struct CGRect frameInPDF; // @synthesize frameInPDF=_frameInPDF;
@property(nonatomic) struct CGPoint centerRotateInPdf; // @synthesize centerRotateInPdf=_centerRotateInPdf;
@property(nonatomic) double textDegree; // @synthesize textDegree=_textDegree;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) _Bool isDate; // @synthesize isDate=_isDate;
@property(retain, nonatomic) NSMutableDictionary *textDataDict; // @synthesize textDataDict=_textDataDict;
- (long long)getOwnerUid;
- (id)getOwnerName;
- (id)getDesc;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

