//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (KGBrush)
+ (id)relevantImageNamed:(id)arg1;
+ (id)imageFromView:(id)arg1 atRect:(struct CGRect)arg2;
- (struct CGAffineTransform)transformForOrientation:(struct CGSize)arg1;
- (id)resizedImage:(struct CGSize)arg1 transform:(struct CGAffineTransform)arg2 drawTransposed:(_Bool)arg3 interpolationQuality:(int)arg4;
- (id)resizedImageWithContentMode:(long long)arg1 bounds:(struct CGSize)arg2 interpolationQuality:(int)arg3;
- (id)resizedImage:(struct CGSize)arg1 interpolationQuality:(int)arg2;
- (id)KGCropAtRect:(struct CGRect)arg1;
- (id)KGScaleToSize:(struct CGSize)arg1;
- (_Bool)reallyHasAlpha;
- (_Bool)hasAlpha;
- (id)JPEGify:(float)arg1;
- (id)downsampleWithMaxDimension:(float)arg1;
- (id)rotatedImage:(int)arg1;
- (void)drawToFillRect:(struct CGRect)arg1;
@end

