//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class LFDrawView, LFStickerView;
@protocol LFEditingProtocol, LFFilterDataProtocol;

@interface UIView (LFEditingProtocol)
- (void)setSplashLineWidth:(double)arg1;
- (void)setSplashStateType:(unsigned long long)arg1;
- (unsigned long long)splashStateType;
- (void)splashUndo;
- (_Bool)splashCanUndo;
- (_Bool)isSplashing;
- (_Bool)splashEnable;
- (void)setSplashEnable:(_Bool)arg1;
- (void)changeSelectSticker:(id)arg1;
- (id)getSelectSticker;
- (void)createSticker:(id)arg1;
- (double)stickerMaxScale;
- (void)setStickerMaxScale:(double)arg1;
- (double)stickerMinScale;
- (void)setStickerMinScale:(double)arg1;
- (double)screenScale;
- (void)setScreenScale:(double)arg1;
- (void)removeSelectStickerView;
- (void)activeSelectStickerView;
- (void)stickerDeactivated;
- (_Bool)stickerEnable;
- (void)setDrawLineWidth:(double)arg1;
- (void)setDrawColor:(id)arg1;
- (void)setDrawBrush:(id)arg1;
- (void)drawUndo;
- (_Bool)drawCanUndo;
- (_Bool)isDrawing;
- (_Bool)drawEnable;
- (void)setDrawEnable:(_Bool)arg1;
- (id)getFilterImage;
- (long long)getFilterType;
- (void)changeFilterType:(long long)arg1;
- (void)photoEditEnable:(_Bool)arg1;
- (id)editDelegate;
- (void)setEditDelegate:(id)arg1;
- (void)setLf_splashLineWidth:(double)arg1;
- (double)lf_splashLineWidth;
- (void)setLf_drawLineColor:(id)arg1;
- (id)lf_drawLineColor;
- (void)setLf_drawLineWidth:(double)arg1;
- (double)lf_drawLineWidth;
- (void)setLf_splashViewEnable:(_Bool)arg1;
- (_Bool)lf_splashViewEnable;
- (void)setLf_stickerViewEnable:(_Bool)arg1;
- (_Bool)lf_stickerViewEnable;
- (void)setLf_drawViewEnable:(_Bool)arg1;
- (_Bool)lf_drawViewEnable;
- (void)setLf_editEnable:(_Bool)arg1;
- (_Bool)lf_editEnable;
- (void)clearProtocolxecutor;
@property(nonatomic) __weak id <LFFilterDataProtocol> lf_displayView;
@property(nonatomic) __weak LFDrawView *lf_splashView;
@property(nonatomic) __weak LFStickerView *lf_stickerView;
@property(nonatomic) __weak LFDrawView *lf_drawView;
@property(nonatomic) __weak UIView<LFEditingProtocol> *lf_protocolxecutor;
@end

