//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (LFDownloadManager)
- (id)dataFromCacheWithURL:(id)arg1;
- (void)lf_downloadCancel;
- (void)lf_downloadImageWithURL:(id)arg1 progress:(CDUnknownBlockType)arg2 completed:(CDUnknownBlockType)arg3;
- (void)setLf_downloadInfo:(id)arg1;
- (id)lf_downloadInfo;
@end

