//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UKeyCAList;

@interface UKeySigner : NSObject
{
    UKeyCAList *_caList;
}

+ (id)signer;
- (void).cxx_destruct;
@property(retain, nonatomic) UKeyCAList *caList; // @synthesize caList=_caList;
- (int)signWithDigest:(id)arg1 cert:(id)arg2 p7:(id *)arg3;

@end

