//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WKScriptMessageHandler-Protocol.h"

@class NSArray, NSString, WKWebView;

@interface UKeyJSAPIRouter : NSObject <WKScriptMessageHandler>
{
    NSArray *_apiArray;
    WKWebView *_webView;
}

+ (void)qysUKeySign_signDigest:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_getStamper:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_verifyPin:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_disconnect:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_connect:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_ukeylist:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_getConnectedDevice:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)qysUKeySign_getBluetoothStatus:(id)arg1:(CDUnknownBlockType)arg2;
+ (void)outputCallbackWithFuncId:(id)arg1 param:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (void)routerWithApiName:(id)arg1 param:(id)arg2 callback:(CDUnknownBlockType)arg3;
+ (id)router;
- (void).cxx_destruct;
@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSArray *apiArray; // @synthesize apiArray=_apiArray;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (_Bool)containsJSAPI:(id)arg1;
- (void)resignUKeyJSAPIAtWebView:(id)arg1;
- (void)resignUKeyJSAPI;
- (void)registerUKeyJSAPIAtWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

