//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WaterMarkView : UIView
{
    int _enableShowChatseting;
    UIView *_backView;
}

+ (id)trimOtherTel:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) int enableShowChatseting; // @synthesize enableShowChatseting=_enableShowChatseting;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
- (id)attrStrWithText1:(id)arg1 font1:(long long)arg2 text2:(id)arg3 font2:(long long)arg4;
- (id)getDate;
- (id)getTime;
- (id)waterDateWith:(id)arg1;
- (id)getWaterAttributedStringWithConfig:(id)arg1;
- (id)getWaterLabelWithConfig:(id)arg1;
- (void)setupOldWaterLabelText:(id)arg1 waterConfig:(id)arg2;
- (void)setupNewVersionLabelText:(id)arg1 waterConfig:(id)arg2;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

