//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LLPDFDocumentARC, NSOperationQueue, YYMemoryCache;

@interface WSDrawManager : NSObject
{
    _Bool _isReloaded;
    LLPDFDocumentARC *_document;
    YYMemoryCache *_cache;
    NSOperationQueue *_drawQueue;
    NSOperationQueue *_cacheQueue;
}

+ (id)drawManagerWithDocument:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool isReloaded; // @synthesize isReloaded=_isReloaded;
@property(retain, nonatomic) NSOperationQueue *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) NSOperationQueue *drawQueue; // @synthesize drawQueue=_drawQueue;
@property(retain, nonatomic) YYMemoryCache *cache; // @synthesize cache=_cache;
@property(retain, nonatomic) LLPDFDocumentARC *document; // @synthesize document=_document;
- (void)updatePageCacheAfterDeletion:(int)arg1;
- (id)thumbPage:(int)arg1 size:(struct CGSize)arg2;
- (id)drawPage:(int)arg1 width:(int)arg2 height:(int)arg3 pdfX:(int)arg4 pdfY:(int)arg5 pdfWidth:(int)arg6 pdfHeight:(int)arg7 priority:(long long)arg8;
- (void)releaseYYCache;
- (void)cancelCacheOperation;
- (void)cachePage:(int)arg1 width:(int)arg2 height:(int)arg3 pdfX:(int)arg4 pdfY:(int)arg5 pdfWidth:(int)arg6 pdfHeight:(int)arg7 priority:(long long)arg8;
- (void)cachePage:(int)arg1 size:(struct CGSize)arg2;
- (id)init;

@end

