//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@class NSString, UIColor;

@interface WSGrowingTextView : UITextView
{
    unsigned long long _maxNumberOfLines;
    CDUnknownBlockType _TextHeightChangeBlock;
    unsigned long long _cornerRadius;
    NSString *_placeholder;
    UIColor *_placeholderColor;
    UITextView *_placeholderView;
    long long _textH;
    long long _maxTextH;
}

- (void).cxx_destruct;
@property(nonatomic) long long maxTextH; // @synthesize maxTextH=_maxTextH;
@property(nonatomic) long long textH; // @synthesize textH=_textH;
@property(nonatomic) __weak UITextView *placeholderView; // @synthesize placeholderView=_placeholderView;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(retain, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(nonatomic) unsigned long long cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(copy, nonatomic) CDUnknownBlockType TextHeightChangeBlock; // @synthesize TextHeightChangeBlock=_TextHeightChangeBlock;
@property(nonatomic) unsigned long long maxNumberOfLines; // @synthesize maxNumberOfLines=_maxNumberOfLines;
- (void)dealloc;
- (void)setText:(id)arg1;
- (void)textDidChange;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

