//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString, UIImage;

@interface WSImageModel : NSObject
{
    _Bool _selected;
    NSString *_selectNum;
    UIImage *_image;
    NSData *_imageData;
    NSString *_imagePath;
    NSString *_objectKey;
}

+ (id)imageMode:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *objectKey; // @synthesize objectKey=_objectKey;
@property(retain, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *selectNum; // @synthesize selectNum=_selectNum;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (id)init;

@end

