//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "IReadLifeCycleListener-Protocol.h"
#import "LLCollectionCellDelegate-Protocol.h"
#import "PdfDisplayHistoryDelegate-Protocol.h"
#import "RSealTempletChooseControlProtocol-Protocol.h"
#import "RSignTempletChooseControlProtocol-Protocol.h"
#import "RWriteBoardControlProtocol-Protocol.h"
#import "ReadDragProtocol-Protocol.h"
#import "ReadTurnPageProtocol-Protocol.h"
#import "ReaderBottomOverlayTipViewDelegate-Protocol.h"
#import "ReaderBottomToolBarDelegate-Protocol.h"
#import "ReaderThickAndColorPanelViewDelegate-Protocol.h"
#import "ReaderWriteStateBottomViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WSHandWriteViewDelegate-Protocol.h"
#import "WSNavigationBarDelegate-Protocol.h"
#import "WSOnlyWriteStateBottomBarDelegate-Protocol.h"
#import "WSPdfDisplayScrolViewDelegate-Protocol.h"
#import "WSPdfDisplayViewDelegate-Protocol.h"
#import "WSReaderInputViewDelegate-Protocol.h"

@class LLCollectionView, LLPDFDocumentARC, NSArray, NSMutableArray, NSMutableDictionary, NSString, PdfHistoryDisplayView, ReaderBottomOverlayTipView, ReaderBottomToolBar, ReaderThickAndColorPanelView, ReaderWriteStateBottomView, UILabel, UIView, WSDrawManager, WSHandWriteView, WSHistoryDataHelp, WSNavigationBar, WSOnlyWriteStateBottomBar, WSPdfDisplayScrolView, WSPdfDisplayView, WSReaderConfiguration, WSReaderInputView, WSReaderManager;

@interface WSReaderViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, ReadDragProtocol, IReadLifeCycleListener, ReadTurnPageProtocol, ReaderBottomToolBarDelegate, ReaderWriteStateBottomViewDelegate, ReaderBottomOverlayTipViewDelegate, RWriteBoardControlProtocol, RSignTempletChooseControlProtocol, ReaderThickAndColorPanelViewDelegate, WSOnlyWriteStateBottomBarDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, WSNavigationBarDelegate, WSReaderInputViewDelegate, LLCollectionCellDelegate, WSPdfDisplayViewDelegate, WSPdfDisplayScrolViewDelegate, PdfDisplayHistoryDelegate, WSHandWriteViewDelegate, RSealTempletChooseControlProtocol>
{
    int count;
    _Bool _isDraggingPDF;
    _Bool _isUsingTurnPageAPI;
    _Bool _didReturnToHomeView;
    _Bool _isRotate;
    _Bool _isLoadFirstCell;
    _Bool _isEnterReader;
    _Bool _isVerticalScreen;
    _Bool _addLockAction;
    _Bool _deleteLockAction;
    _Bool _isCustom;
    _Bool _isFromeNet;
    _Bool _enableVerticalMode;
    _Bool _enableMultipleReader;
    _Bool _clickLock;
    int _currentPdfTotoalPageCount;
    int _totoalPageCount;
    int _currentPage;
    int _lastOffsetIndex;
    int _WS_ReaderCount;
    NSMutableDictionary *_signAdjustViewArray;
    NSMutableDictionary *_allDataModelArrayDict;
    NSString *_WS_filePath;
    WSNavigationBar *_WS_navigationBar;
    LLCollectionView *_WS_collectionView;
    LLPDFDocumentARC *_m_pdfdoc;
    NSString *_WS_passWord;
    long long _WS_retryOpenCount;
    WSDrawManager *_WS_drawManager;
    WSDrawManager *_WS_tempDrawManager;
    UILabel *_pageNumberView;
    double _lastOffset;
    long long _orientation;
    double _currentScale;
    NSMutableArray *_overlayViews;
    ReaderBottomToolBar *_WS_bottomToolBar;
    ReaderBottomOverlayTipView *_WS_bottomOverlayTipView;
    ReaderWriteStateBottomView *_WS_writeStateBottomView;
    ReaderThickAndColorPanelView *_WS_thickColorPanelView;
    WSOnlyWriteStateBottomBar *_WS_onlyWriteBottomBar;
    WSReaderInputView *_WS_inputView;
    NSString *_stencilImagePath;
    NSString *_WS_fileID;
    NSString *_WS_userID;
    NSString *_WS_fileMD5;
    NSString *_WS_fileName;
    NSString *_WS_savePath;
    long long _state;
    unsigned long long _readerType;
    WSReaderConfiguration *_configuration;
    UIView *_tempPdfView;
    WSHistoryDataHelp *_WS_historyHelp;
    WSPdfDisplayView *_WS_PdfDisplayView;
    WSPdfDisplayScrolView *_WS_PdfDisplayScrollView;
    NSMutableArray *_displayArr;
    NSArray *_metaDataArr;
    PdfHistoryDisplayView *_WS_historyDisplayView;
    WSHandWriteView *_WS_handWriteView;
    WSReaderManager *_shareM;
    UIView *_WS_CustomHistoryDisplayView;
    struct CGPoint _tapPoint;
}

+ (void)setConfiguration:(id)arg1;
+ (id)openFiles:(id)arg1 withPassWords:(id)arg2 withFileNames:(id)arg3 withSignCachePathArray:(id)arg4 withReaderConfiguation:(id)arg5;
+ (id)openNetWorkFile:(id)arg1 andFileName:(id)arg2 andUserId:(id)arg3 passWord:(id)arg4;
+ (id)openFile:(id)arg1 withFileName:(id)arg2 passWord:(id)arg3;
- (void).cxx_destruct;
@property(nonatomic) _Bool clickLock; // @synthesize clickLock=_clickLock;
@property(nonatomic) __weak UIView *WS_CustomHistoryDisplayView; // @synthesize WS_CustomHistoryDisplayView=_WS_CustomHistoryDisplayView;
@property(nonatomic) __weak WSReaderManager *shareM; // @synthesize shareM=_shareM;
@property(nonatomic) int WS_ReaderCount; // @synthesize WS_ReaderCount=_WS_ReaderCount;
@property(nonatomic) _Bool enableMultipleReader; // @synthesize enableMultipleReader=_enableMultipleReader;
@property(nonatomic) _Bool enableVerticalMode; // @synthesize enableVerticalMode=_enableVerticalMode;
@property(retain, nonatomic) WSHandWriteView *WS_handWriteView; // @synthesize WS_handWriteView=_WS_handWriteView;
@property(retain, nonatomic) PdfHistoryDisplayView *WS_historyDisplayView; // @synthesize WS_historyDisplayView=_WS_historyDisplayView;
@property(retain, nonatomic) NSArray *metaDataArr; // @synthesize metaDataArr=_metaDataArr;
@property(retain, nonatomic) NSMutableArray *displayArr; // @synthesize displayArr=_displayArr;
@property(retain, nonatomic) WSPdfDisplayScrolView *WS_PdfDisplayScrollView; // @synthesize WS_PdfDisplayScrollView=_WS_PdfDisplayScrollView;
@property(retain, nonatomic) WSPdfDisplayView *WS_PdfDisplayView; // @synthesize WS_PdfDisplayView=_WS_PdfDisplayView;
@property(retain, nonatomic) WSHistoryDataHelp *WS_historyHelp; // @synthesize WS_historyHelp=_WS_historyHelp;
@property(retain, nonatomic) UIView *tempPdfView; // @synthesize tempPdfView=_tempPdfView;
@property(retain, nonatomic) WSReaderConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) unsigned long long readerType; // @synthesize readerType=_readerType;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *WS_savePath; // @synthesize WS_savePath=_WS_savePath;
@property(copy, nonatomic) NSString *WS_fileName; // @synthesize WS_fileName=_WS_fileName;
@property(copy, nonatomic) NSString *WS_fileMD5; // @synthesize WS_fileMD5=_WS_fileMD5;
@property(copy, nonatomic) NSString *WS_userID; // @synthesize WS_userID=_WS_userID;
@property(copy, nonatomic) NSString *WS_fileID; // @synthesize WS_fileID=_WS_fileID;
@property(nonatomic) _Bool isFromeNet; // @synthesize isFromeNet=_isFromeNet;
@property(nonatomic) _Bool isCustom; // @synthesize isCustom=_isCustom;
@property(copy, nonatomic) NSString *stencilImagePath; // @synthesize stencilImagePath=_stencilImagePath;
@property(nonatomic) _Bool deleteLockAction; // @synthesize deleteLockAction=_deleteLockAction;
@property(nonatomic) _Bool addLockAction; // @synthesize addLockAction=_addLockAction;
@property(nonatomic) struct CGPoint tapPoint; // @synthesize tapPoint=_tapPoint;
@property(nonatomic) _Bool isVerticalScreen; // @synthesize isVerticalScreen=_isVerticalScreen;
@property(retain, nonatomic) WSReaderInputView *WS_inputView; // @synthesize WS_inputView=_WS_inputView;
@property(retain, nonatomic) WSOnlyWriteStateBottomBar *WS_onlyWriteBottomBar; // @synthesize WS_onlyWriteBottomBar=_WS_onlyWriteBottomBar;
@property(retain, nonatomic) ReaderThickAndColorPanelView *WS_thickColorPanelView; // @synthesize WS_thickColorPanelView=_WS_thickColorPanelView;
@property(retain, nonatomic) ReaderWriteStateBottomView *WS_writeStateBottomView; // @synthesize WS_writeStateBottomView=_WS_writeStateBottomView;
@property(retain, nonatomic) ReaderBottomOverlayTipView *WS_bottomOverlayTipView; // @synthesize WS_bottomOverlayTipView=_WS_bottomOverlayTipView;
@property(retain, nonatomic) ReaderBottomToolBar *WS_bottomToolBar; // @synthesize WS_bottomToolBar=_WS_bottomToolBar;
@property(nonatomic) _Bool isEnterReader; // @synthesize isEnterReader=_isEnterReader;
@property(retain, nonatomic) NSMutableArray *overlayViews; // @synthesize overlayViews=_overlayViews;
@property(nonatomic) double currentScale; // @synthesize currentScale=_currentScale;
@property(nonatomic) _Bool isLoadFirstCell; // @synthesize isLoadFirstCell=_isLoadFirstCell;
@property(nonatomic) _Bool isRotate; // @synthesize isRotate=_isRotate;
@property(nonatomic) _Bool didReturnToHomeView; // @synthesize didReturnToHomeView=_didReturnToHomeView;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) double lastOffset; // @synthesize lastOffset=_lastOffset;
@property(nonatomic) int lastOffsetIndex; // @synthesize lastOffsetIndex=_lastOffsetIndex;
@property(nonatomic) _Bool isUsingTurnPageAPI; // @synthesize isUsingTurnPageAPI=_isUsingTurnPageAPI;
@property(nonatomic) _Bool isDraggingPDF; // @synthesize isDraggingPDF=_isDraggingPDF;
@property(nonatomic) int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) int totoalPageCount; // @synthesize totoalPageCount=_totoalPageCount;
@property(nonatomic) int currentPdfTotoalPageCount; // @synthesize currentPdfTotoalPageCount=_currentPdfTotoalPageCount;
@property(retain, nonatomic) UILabel *pageNumberView; // @synthesize pageNumberView=_pageNumberView;
@property(retain, nonatomic) WSDrawManager *WS_tempDrawManager; // @synthesize WS_tempDrawManager=_WS_tempDrawManager;
@property(retain, nonatomic) WSDrawManager *WS_drawManager; // @synthesize WS_drawManager=_WS_drawManager;
@property(nonatomic) long long WS_retryOpenCount; // @synthesize WS_retryOpenCount=_WS_retryOpenCount;
@property(copy, nonatomic) NSString *WS_passWord; // @synthesize WS_passWord=_WS_passWord;
@property(retain, nonatomic) LLPDFDocumentARC *m_pdfdoc; // @synthesize m_pdfdoc=_m_pdfdoc;
@property(retain, nonatomic) LLCollectionView *WS_collectionView; // @synthesize WS_collectionView=_WS_collectionView;
@property(retain, nonatomic) WSNavigationBar *WS_navigationBar; // @synthesize WS_navigationBar=_WS_navigationBar;
@property(copy, nonatomic) NSString *WS_filePath; // @synthesize WS_filePath=_WS_filePath;
@property(readonly, nonatomic) NSMutableDictionary *allDataModelArrayDict; // @synthesize allDataModelArrayDict=_allDataModelArrayDict;
@property(readonly, nonatomic) NSMutableDictionary *signAdjustViewArray; // @synthesize signAdjustViewArray=_signAdjustViewArray;
- (void)WS_Method_EnableVerticalSreenMode;
- (void)reloadPageSignDataWithPage:(int)arg1;
- (void)WS_Method_DeleteSignData;
- (_Bool)shouldStopRecursive;
- (_Bool)shouldArchive;
- (void)WS_Method_ArchiveSignData:(_Bool)arg1 complete:(CDUnknownBlockType)arg2;
- (void)WS_Method_SetArchiveInterval:(int)arg1;
- (void)archiveSingDataComplete:(CDUnknownBlockType)arg1;
- (void)WS_Method_RememberLastStrokeState;
- (void)WS_Method_CustomPDFDisPlayViewShow;
- (void)WS_Method_HidePageNumberView:(_Bool)arg1;
- (void)WS_Invoke_SetDefaultPathColor:(long long)arg1 thickNess:(long long)arg2;
- (void)WS_Method_ShowInsertDateButton:(_Bool)arg1 withDateType:(int)arg2;
- (void)WSShowHandWriteView;
- (void)WSHandWriteViewClose;
- (void)shouldDismissHistoryDisplayView;
- (void)didSelecteSignerCardWithPagenum:(int)arg1 withFrameInPDF:(struct CGRect)arg2 isSelected:(_Bool)arg3;
- (void)shrinking;
- (_Bool)haveSavedDataOnPage:(int)arg1;
- (_Bool)haveUnSavedDataOnPage:(int)arg1;
- (void)startZoomOrJumpPageTranscation;
- (void)WS_Method_ZoomingInPage:(long long)arg1 position:(struct CGRect)arg2 isSelected:(_Bool)arg3;
- (void)ZoomingInPage:(long long)arg1 position:(struct CGRect)arg2;
- (void)WSPdfDisplayScrolViewLoadAllDataBeforPage:(int)arg1;
- (void)WSPdfDisplayScrolViewLoadMoreDataWithPage:(int)arg1;
- (void)WSPdfDisplayScrolViewItemClick:(long long)arg1;
- (void)WSPdfDisplayViewLoadAllDataBeforPage:(int)arg1;
- (void)WSPdfDisplayViewLoadMoreDataWithPage:(int)arg1;
- (void)WSPdfDisplayViewClick:(long long)arg1;
- (void)upDateDisplayArrWithUnSaveData:(_Bool)arg1;
- (void)WS_Private_getDisplayDataWithPage:(int)arg1 Complete:(CDUnknownBlockType)arg2;
- (void)WS_Private_getDisplayDataWithTotalPage:(int)arg1 Complete:(CDUnknownBlockType)arg2;
- (void)WS_Private_getDisplayDataWithCount:(int)arg1 Complete:(CDUnknownBlockType)arg2;
- (id)WS_Method_GetSignInfo;
- (id)getSignerModelFromPDFMetadata;
- (void)WS_Method_RegSigner:(id)arg1 signerID:(id)arg2 description:(id)arg3;
- (void)WS_Invoke_Photo;
- (void)addSignDate:(struct CGRect)arg1;
- (void)editTextButtonClick:(id)arg1;
- (void)WS_Method_JumpToPage:(long long)arg1;
- (void)WS_Method_SetStrokeThickness:(long long)arg1;
- (void)WS_Method_SetStrokeColor:(long long)arg1;
- (long long)getState;
- (int)WS_Method_GetCurrentPage;
- (void)setSavePath:(id)arg1;
- (void)reloadPDFView:(id)arg1;
- (void)WS_Invoke_InsertSeal;
- (void)WS_Invoke_InsertPicture;
- (void)WS_Invoke_InsertSign;
- (void)WS_Invoke_InsertDate;
- (void)WS_Invoke_InsertText;
- (void)WS_Invoke_TurnOnApplePencil:(_Bool)arg1;
- (void)WS_Invoke_ReUndoWrite;
- (void)WS_Invoke_UndoWrite;
- (void)WS_Invoke_ClearAll;
- (void)WS_Invoke_EraseMode;
- (void)WS_Invoke_AnnotateMode;
- (void)WS_Invoke_ReadOnlyMode;
- (void)WS_Invoke_SaveSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)WS_Method_TurnToNextPage;
- (void)WS_Method_TurnToPreviousPage;
- (void)chekitout;
- (void)startLiseningSaveButtonState;
- (void)returnButtonAction;
- (void)saveButtonActionSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (id)fixOrientation:(id)arg1;
- (id)createNewImageToReader:(id)arg1;
- (void)insertPhotoFromTakePhoto:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)WS_Method_InsertPicture:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (unsigned long long)preferredScreenEdgesDeferringSystemGestures;
- (void)hideMenuViewOrPanelView;
- (id)setNumberLabelAttributedTextWithPage:(int)arg1;
- (id)setNumberViewTextWithPage:(int)arg1;
- (void)turnPageTo:(int)arg1;
- (_Bool)WS_Method_HaveWriteData;
- (void)didReceiveMemoryWarning;
- (void)readDestroy;
- (void)WS_Method_ReadDestroy;
- (void)closeReadUIFeature;
- (void)openReadUIFeature;
- (void)resetPropertiesAndState;
- (void)WSCollectionCellDataChanged:(id)arg1;
- (void)registListeners;
- (void)copyToDestPath;
- (void)setNavigationBarWithState:(long long)arg1;
- (void)WS_Method_EnterCustomMode;
- (void)WS_Invoke_SetPdfDisplayView:(id)arg1;
- (void)WS_Invoke_SetPdfView:(id)arg1;
- (void)WS_Private_initUI;
- (void)WS_openFileComplete:(CDUnknownBlockType)arg1;
- (void)commitInitPDFDocumentComplete:(CDUnknownBlockType)arg1;
- (void)initPDFDocumentAndWriteDataComplete:(CDUnknownBlockType)arg1;
- (void)addPageButtonClickAction;
- (void)WS_Method_AddOnePage;
- (void)deletePageButtonClickAction;
- (void)WS_Method_DeleteCurrentPage;
- (void)takePhotoButtonClickAction;
- (void)openUIImagePickerController;
- (void)enterPhotoLibraryButtonClickAction;
- (void)choosePictureClickAction;
- (void)onlyNoteButtonClickAction;
- (void)menuTableDidSelectAt:(id)arg1;
- (void)turnPreButtonClickAction;
- (void)turnNextButtonClickAction;
- (void)moreButtonClickAction:(id)arg1;
- (void)clearButtonClickAction;
- (void)eraserButtonClickAction;
- (void)writeButtonClickAction;
- (void)confirmButtonClickAction;
- (void)noteButtonClickAction;
- (void)sureInputText:(id)arg1 color:(id)arg2 textAlignment:(long long)arg3;
- (void)WS_Method_ReloadHistoryRecordData;
- (void)WS_Invoke_SetHistoryRecordingView:(id)arg1;
- (void)displayInputViewAndEditContent:(id)arg1;
- (void)insertPictureButtonClickAction;
- (void)handWriteButtonClickAction;
- (void)textButtonClickAction;
- (void)dateButtonClickAction;
- (void)hideColorPanelView;
- (void)showColorPanelView;
- (void)hideWriteBottomView;
- (void)showWriteBottomView;
- (void)hideBottomTipView;
- (void)showBottomTipView:(long long)arg1;
- (void)signButtonClickAction;
- (void)backButtonClickAction;
- (void)WS_Method_InsertSign:(id)arg1;
- (void)insertSealTemplet:(id)arg1;
- (void)insertTemplet:(id)arg1;
- (void)closeButtonClickAction;
- (void)insertSignWith:(id)arg1;
- (void)thickSliderValueChanged:(long long)arg1;
- (void)colorPanelCollectionViewDidSelect:(long long)arg1;
- (void)backToHomePage;
- (void)solidifyButtonClickSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (void)turnPageToNextPage;
- (void)turnPageToPreviousPage;
- (void)returnClick;
- (void)beginTurnPage;
- (void)handleDoubleTap:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)onEndDragToXPosition:(double)arg1 yPosition:(double)arg2 cell:(id)arg3;
- (void)onBeginDragWithCell:(id)arg1;
- (void)convertRelativeCurrentPageWithIndex:(int)arg1 fromPage:(int)arg2 toPage:(int)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (void)WS_PrivateSetPdfNameHere:(id)arg1 pdfIndex:(int)arg2;
- (void)updatePdfIndexWithCurrentPage:(int)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (int)currentScrollOffsetIndex:(double)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)syncPageIndexWhileUseingTurnPageAPI:(int)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)WS_reloadUI;
- (void)checkIfTheReaderIsChangedFromPage:(int)arg1 toPage:(int)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)WS_Private_initSDKAndUIComplete:(CDUnknownBlockType)arg1;
- (void)WS_Method_finishDownLoadFile;
- (void)viewDidLoad;
- (void)WS_loadNewPdfWithIndex:(int)arg1 Complete:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

