//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "RSignTempletChooseControlProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WSReaderInputViewDelegate-Protocol.h"
#import "WSVOverlayViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UICollectionView, UICollectionViewFlowLayout, UITapGestureRecognizer, UIView, WSDrawManager, WSReaderInputView, WSVDrawContext, WSVerticalReaderManager;
@protocol WSVerticalPDFViewDelegate;

@interface WSVerticalPDFView : UIScrollView <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UINavigationControllerDelegate, UIImagePickerControllerDelegate, WSVOverlayViewDelegate, WSReaderInputViewDelegate, RSignTempletChooseControlProtocol>
{
    _Bool _mIsZooming;
    _Bool _mIsBouncing;
    _Bool _mIsSmallPdf;
    _Bool _mDoubleTapZooming;
    _Bool _mIsUpdateingLayout;
    _Bool _mDidStopRender;
    _Bool _mIsEditingText;
    int _mPageCount;
    int _mCurrentPage;
    int _mCurrentLoadMorePage;
    int _mRetryOpenCount;
    id <WSVerticalPDFViewDelegate> _pdfDelegate;
    double _mPdfViewInitHeight;
    double _mOldContentOffset;
    double _mNewContentOffset;
    UICollectionView *_mReaderCollectionView;
    UICollectionViewFlowLayout *_mReaderFlowLayout;
    UICollectionView *_mZoomingCollectionView;
    NSArray *_mPdfOriginalSizeArray;
    NSArray *_mPdfMatchScaleArray;
    UIView *_mMiddleView;
    WSReaderInputView *_mInputTextView;
    NSArray *_mPdfMatchSizeArray;
    NSArray *_mPdfMatchFrameArray;
    NSArray *_mQuickFindIndexArray;
    NSMutableArray *_mDrawedIndexArray;
    UITapGestureRecognizer *_mDoubleTap;
    UITapGestureRecognizer *_mSingleTap;
    WSDrawManager *_mDrawManager;
    WSVDrawContext *_mDrawContext;
    WSVerticalReaderManager *_shareM;
    NSString *_mFilePath;
    NSString *_mFilePassword;
    long long _mVerticalReaderState;
    struct CGSize _mCurrentViewSize;
    struct CGPoint _mOffsetRatio;
}

- (void).cxx_destruct;
@property(nonatomic) long long mVerticalReaderState; // @synthesize mVerticalReaderState=_mVerticalReaderState;
@property(nonatomic) int mRetryOpenCount; // @synthesize mRetryOpenCount=_mRetryOpenCount;
@property(retain, nonatomic) NSString *mFilePassword; // @synthesize mFilePassword=_mFilePassword;
@property(retain, nonatomic) NSString *mFilePath; // @synthesize mFilePath=_mFilePath;
@property(retain, nonatomic) WSVerticalReaderManager *shareM; // @synthesize shareM=_shareM;
@property(retain, nonatomic) WSVDrawContext *mDrawContext; // @synthesize mDrawContext=_mDrawContext;
@property(nonatomic) __weak WSDrawManager *mDrawManager; // @synthesize mDrawManager=_mDrawManager;
@property(nonatomic) struct CGPoint mOffsetRatio; // @synthesize mOffsetRatio=_mOffsetRatio;
@property(nonatomic) struct CGSize mCurrentViewSize; // @synthesize mCurrentViewSize=_mCurrentViewSize;
@property(retain, nonatomic) UITapGestureRecognizer *mSingleTap; // @synthesize mSingleTap=_mSingleTap;
@property(retain, nonatomic) UITapGestureRecognizer *mDoubleTap; // @synthesize mDoubleTap=_mDoubleTap;
@property(retain, nonatomic) NSMutableArray *mDrawedIndexArray; // @synthesize mDrawedIndexArray=_mDrawedIndexArray;
@property(retain, nonatomic) NSArray *mQuickFindIndexArray; // @synthesize mQuickFindIndexArray=_mQuickFindIndexArray;
@property(retain, nonatomic) NSArray *mPdfMatchFrameArray; // @synthesize mPdfMatchFrameArray=_mPdfMatchFrameArray;
@property(retain, nonatomic) NSArray *mPdfMatchSizeArray; // @synthesize mPdfMatchSizeArray=_mPdfMatchSizeArray;
@property(retain, nonatomic) WSReaderInputView *mInputTextView; // @synthesize mInputTextView=_mInputTextView;
@property(retain, nonatomic) UIView *mMiddleView; // @synthesize mMiddleView=_mMiddleView;
@property(retain, nonatomic) NSArray *mPdfMatchScaleArray; // @synthesize mPdfMatchScaleArray=_mPdfMatchScaleArray;
@property(retain, nonatomic) NSArray *mPdfOriginalSizeArray; // @synthesize mPdfOriginalSizeArray=_mPdfOriginalSizeArray;
@property(retain, nonatomic) UICollectionView *mZoomingCollectionView; // @synthesize mZoomingCollectionView=_mZoomingCollectionView;
@property(retain, nonatomic) UICollectionViewFlowLayout *mReaderFlowLayout; // @synthesize mReaderFlowLayout=_mReaderFlowLayout;
@property(retain, nonatomic) UICollectionView *mReaderCollectionView; // @synthesize mReaderCollectionView=_mReaderCollectionView;
@property(nonatomic) double mNewContentOffset; // @synthesize mNewContentOffset=_mNewContentOffset;
@property(nonatomic) double mOldContentOffset; // @synthesize mOldContentOffset=_mOldContentOffset;
@property(nonatomic) int mCurrentLoadMorePage; // @synthesize mCurrentLoadMorePage=_mCurrentLoadMorePage;
@property(nonatomic) int mCurrentPage; // @synthesize mCurrentPage=_mCurrentPage;
@property(nonatomic) int mPageCount; // @synthesize mPageCount=_mPageCount;
@property(nonatomic) double mPdfViewInitHeight; // @synthesize mPdfViewInitHeight=_mPdfViewInitHeight;
@property(nonatomic) _Bool mIsEditingText; // @synthesize mIsEditingText=_mIsEditingText;
@property(nonatomic) _Bool mDidStopRender; // @synthesize mDidStopRender=_mDidStopRender;
@property(nonatomic) _Bool mIsUpdateingLayout; // @synthesize mIsUpdateingLayout=_mIsUpdateingLayout;
@property(nonatomic) _Bool mDoubleTapZooming; // @synthesize mDoubleTapZooming=_mDoubleTapZooming;
@property(nonatomic) _Bool mIsSmallPdf; // @synthesize mIsSmallPdf=_mIsSmallPdf;
@property(nonatomic) _Bool mIsBouncing; // @synthesize mIsBouncing=_mIsBouncing;
@property(nonatomic) _Bool mIsZooming; // @synthesize mIsZooming=_mIsZooming;
@property(nonatomic) __weak id <WSVerticalPDFViewDelegate> pdfDelegate; // @synthesize pdfDelegate=_pdfDelegate;
- (void)dealloc;
- (void)WS_Method_SaveFile:(CDUnknownBlockType)arg1;
- (void)WS_Method_InsertText;
- (void)dealWithImageAndInsert:(id)arg1;
- (void)insertPhotoFromTakePhoto:(id)arg1;
- (void)WS_Method_InsertPhotoFromCamera;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)openUIImagePickerController;
- (void)WS_Method_InsertPhotoFromAlbum;
- (void)insertTemplet:(id)arg1;
- (void)WS_Method_InsertSign;
- (int)WS_Method_GetPdfPageCount;
- (void)WS_Method_ClearCurrentPageLines;
- (void)WS_Method_SetPenThickness:(long long)arg1;
- (void)WS_Method_SetPenColor:(long long)arg1;
- (void)WS_Method_SetPenType:(long long)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)getSelectedAdjustView;
- (struct CGRect)caculateAdjustviewRectWithSize:(struct CGSize)arg1;
- (void)sureInputText:(id)arg1 color:(id)arg2 textAlignment:(long long)arg3;
- (void)showInputTextViewWithText:(id)arg1;
- (double)caculateViewSize;
- (void)updateCollectionViewFrame;
- (void)loadMorePagesIfNeeded;
- (id)getCurrentPageCell;
- (id)getVisiableCells;
- (id)getSortedZoomingCells;
- (id)getSortedReaderCells;
- (void)checkIfDrawPage:(id)arg1;
- (int)getCurrentPage:(id)arg1;
- (void)loadPdfThumbIfNeeded;
- (void)pageIndexDidChanged:(int)arg1;
- (void)recycleCellImage;
- (void)bounceCenterVerticalIfNeeded;
- (void)reloadVisiableCells;
- (void)refreshVisiableCellsBezier2ImageIfNeeded;
- (void)needUnSelectAllCellAdjustViews;
- (void)onEditText:(id)arg1;
- (void)onHandWrite:(int)arg1;
- (void)overlayViewThumbImageDidChanged:(id)arg1 atPage:(int)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGRect)getRectWithScale:(double)arg1 andCenter:(struct CGPoint)arg2;
- (void)unSelectAdjustViewIfNeeded;
- (void)handleSignleTap;
- (void)handleDoubleTap:(id)arg1;
- (void)initView;
- (id)viewController;
- (void)initPdfData;
- (void)updateLayout;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)initCenterChangedObserver;
- (id)initWithFrame:(struct CGRect)arg1 filePath:(id)arg2 password:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

